// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/html dojo/_base/array dojo/_base/declare ./BaseDijit moment/moment jimu/dijit/StatisticsChart jimu/DataSourceManager jimu/LayerInfos/LayerInfos".split(" "),function(f,k,l,m,n,g,p,q,r){window.makeTwix(g);return m([n],{templateString:'\x3cdiv\x3e\x3cdiv data-dojo-attach-point\x3d"noDataDiv" class\x3d"no-data-tip"\x3e${nls.noData}\x3c/div\x3e\x3c/div\x3e',type:"chart",baseClass:"infographic-chart-dijit",layerInfosObj:null,dataSourceManager:null,featuresCountForPreview:50,
dataSource:null,config:null,map:null,dataSourceType:"",featureLayer:null,constructor:function(a){this.config=a.config;this.layerInfosObj=r.getInstanceSync();this.dataSourceManager=q.getInstance()},postCreate:function(){this.inherited(arguments);this.domNode.style.width="100%";this.domNode.style.height="100%";var a={_legendNls:this.nls.legend,theme:this._getChartTheme(),map:null,isBigPreview:!1,showSettingIcon:!1,showZoomIcon:!1,zoomToFeaturesWhenClick:!1};this.inSettingPage||(a.map=this.map);this.chart=
new p(a);this.chart.placeAt(this.domNode);this._updateBackgroundColor()},_getChartTheme:function(){return this.isDarkTheme()?"dark":"light"},clearChart:function(){this._showNodata()},startup:function(){this.inherited(arguments);setTimeout(f.hitch(this,function(){this.chart.resizeByParent();this.inSettingPage?this._tryUpdateStatisticsChart():this.dataSource&&this.setDataSource(this.dataSource)}),200)},destroy:function(){this.chart&&this.chart.destroy();this.chart=null;this.inherited(arguments)},resize:function(){this.chart&&
this.chart.resizeByParent()},setDataSource:function(a){this.dataSourceType="";this.featureLayer=null;this.inherited(arguments);if(a)if(a.layerId)this._setDataSourceForLayerId(a);else if(a.frameWorkDsId){var b=this._getDsTypeInfoAndDsMeta(a.frameWorkDsId),c=b.dsTypeInfo,b=b.dsMeta;c&&b&&("Features"===b.type?this._setDataSourceForFrameworkFeatures(a,c,b):"FeatureStatistics"===b.type&&this._setDataSourceForFeatureStatistics(a,c,b))}},_getDsTypeInfoAndDsMeta:function(a){var b={dsTypeInfo:null,dsMeta:null};
b.dsTypeInfo=this.dataSourceManager.parseDataSourceId(a);var c=this.appConfig.dataSource&&this.appConfig.dataSource.dataSources;c&&(b.dsMeta=c[a]);return b},_updateBackgroundColor:function(){this.config&&this.config.backgroundColor&&this.setBackgroundColor(this.config.backgroundColor)},setBackgroundColor:function(a){this.domNode.style.backgroundColor=a},setConfig:function(a){this.config=a;this._updateBackgroundColor();this._tryUpdateStatisticsChart()},onDataSourceDataUpdate:function(a){this.inherited(arguments);
"CLIENT_FEATURES"===this.dataSourceType?this._onDataUpdateForClientFeatures(a):"FRAMEWORK_STATISTICS"===this.dataSourceType?this._onDataUpdateForFrameworkStatistics(a):"FRAMEWORK_FEATURES"===this.dataSourceType&&this._onDataUpdateForFrameworkFeatures(a)},_tryUpdateStatisticsChart:function(){this._hideNodata();var a=this._getChartConfigFromConfig();a?this.domNode.parentNode?this.data?(this.data.features||(this.data.features=[]),"CLIENT_FEATURES"===this.dataSourceType?this._tryUpdateStatisticsChartForClientFeatures(a):
"FRAMEWORK_FEATURES"===this.dataSourceType?this._tryUpdateStatisticsChartForFrameworkFeatures(a):"FRAMEWORK_STATISTICS"===this.dataSourceType&&this._tryUpdateStatisticsChartForFrameworkStatistics(a)):this._showNodata():this._showNodata():this._showNodata()},_getNodataTextColor:function(){var a="";this.config&&(a="pie"===this.config.type?this.config.dataLabelColor:this.config.horizontalAxisTextColor||this.config.verticalAxisTextColor);a||(a="#666");return a},_getChartConfigFromConfig:function(){var a=
null;if(this.config&&this.config.mode&&this.config.type){var a=f.clone(this.config),b=a.type,c=["backgroundColor","colors","showLegend","legendTextColor"],c="pie"===b?c.concat(["showDataLabel","dataLabelColor"]):c.concat(["showHorizontalAxis","horizontalAxisTextColor","showVerticalAxis","verticalAxisTextColor"]),d={};a.types=[{type:b,display:d}];l.forEach(c,f.hitch(this,function(b){d[b]=a[b];delete a[b]}))}return a},_hasFeatures:function(){return this.data&&this.data.features&&0<=this.data.features.length},
_showNodata:function(a){k.addClass(this.domNode,"no-data");"max"===a&&(this.noDataDiv.innerHTML="Failed to compute. Too many time intervals due to the short parsing period.");this.chart.clear()},_hideNodata:function(){k.removeClass(this.domNode,"no-data")},_showMockData:function(a){a=f.clone(a);var b=[];a.labelField&&b.push(a.labelField);a.categoryField&&b.push(a.categoryField);a.valueFields&&(b=b.concat(a.valueFields));var c={fields:[]},d={attributes:{}};c.fields=l.map(b,f.hitch(this,function(a){d.attributes[a]=
0;return{name:a,type:"esriFieldTypeInteger",alias:a}}));this.chart.resizeByParent();if(this._checkIsMaxLabels([d],a))return this._showNodata("max");this.chart.createClientCharts(c,[d],a,this.popupFieldInfosObj)},_setDataSourceForLayerId:function(a){this.dataSourceType="CLIENT_FEATURES";var b=this.layerInfosObj.getLayerInfoById(a.layerId);b&&b.getLayerObject().then(f.hitch(this,function(a){this.popupFieldInfosObj=b.getPopupInfo();this.featureLayer=a;this._tryUpdateStatisticsChart()}))},_onDataUpdateForClientFeatures:function(){this._tryUpdateStatisticsChart()},
_tryUpdateStatisticsChartForClientFeatures:function(a){if(this.featureLayer){var b=this.data.features;b&&this.inSettingPage&&(b=b.slice(0,this.featuresCountForPreview));this.chart.resizeByParent();if(this._checkIsMaxLabels(b,a))return this._showNodata("max");var c=this._getFeatureLayerForSymbolRenderChart();this.chart.createClientCharts(this.featureLayer,b,a,this.popupFieldInfosObj,c)}else this._showNodata()},_setDataSourceForFrameworkFeatures:function(){this.dataSourceType="FRAMEWORK_FEATURES";this._tryUpdateStatisticsChart()},
_onDataUpdateForFrameworkFeatures:function(){this._tryUpdateStatisticsChart()},_getFeatureLayerForSymbolRenderChart:function(a){var b=null;this.map&&"undefined"!==typeof a?b=this.map.getLayer(a):this.featureLayer&&(b=this.featureLayer);return b},_tryUpdateStatisticsChartForFrameworkFeatures:function(a){var b=this._getDsTypeInfoAndDsMeta(this.dataSource.frameWorkDsId).dsMeta;if(b){var c=this.data.features;c&&this.inSettingPage&&(c=c.slice(0,this.featuresCountForPreview));this.chart.resizeByParent();
if(this._checkIsMaxLabels(c,a))return this._showNodata("max");var d=null;if("undefined"!==a.useLayerSymbology){var e=this.dataSourceManager.parseDataSourceId(b.id);"undefined"!==typeof e.layerId&&(d=this._getFeatureLayerForSymbolRenderChart(e.layerId))}this.chart.createClientCharts(b.dataSchema,c,a,this.popupFieldInfosObj,d)}else this._showNodata()},_setDataSourceForFeatureStatistics:function(){this.dataSourceType="FRAMEWORK_STATISTICS";this._tryUpdateStatisticsChart()},_onDataUpdateForFrameworkStatistics:function(){this._tryUpdateStatisticsChart()},
_tryUpdateStatisticsChartForFrameworkStatistics:function(a){var b=this._getDsTypeInfoAndDsMeta(this.dataSource.frameWorkDsId).dsMeta;if(b){this.chart.resizeByParent();if(this._checkIsMaxLabels(this.data.features,a))return this._showNodata("max");this.chart.createServerStatisticsCharts(b.dataSchema,this.data.features,a)}else this._showNodata()},_checkIsMaxLabels:function(a,b){var c=b.dateConfig;if(!c||"automatic"===c.minPeriod)return!1;var d=b.categoryField,e=a.map(f.hitch(this,function(a){return a.attributes[d]})),
e=e.filter(function(a){return!!a}),h=Math.min.apply(Math,e),e=Math.max.apply(Math,e),h=g(h).subtract(1,"seconds").local(),e=g(e).add(1,"seconds").local();return 1E4<=Math.round(e.diff(h,c.minPeriod,!0))}})});