// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html ./BaseDijit jimu/utils jimu/dijit/Chart ./utils".split(" "),function(p,l,m,q,k,r,n){return p([q],{templateString:'\x3cdiv style\x3d"height:100%;"\x3e\x3cdiv data-dojo-attach-point\x3d"gauge"\x3e\x3c/div\x3e\x3c/div\x3e',type:"gauge",config:null,postCreate:function(){this.inherited(arguments);this.features=[];this.DEFAULT_GAUGE_CONFIG={type:"gauge",confine:!0,shape:"curved",min:0,max:100,series:[{data:[0]}]};this.config&&(this.DEFAULT_GAUGE_CONFIG.shape=
this.config.shape);this.isDarkTheme()?this.DEFAULT_GAUGE_CONFIG.theme="dark":this.DEFAULT_GAUGE_CONFIG.theme="light";this._initChart();this.setConfig(this.config)},onDataSourceDataUpdate:function(a){this.features=a.features;this._updateStatisticsValue()},resize:function(a,b){this.chart&&(a&&b?this.chart.resize(a,b):this.chart.resize())},_updateStatisticsValue:function(){if(this.config.statistic&&this.dataSource){var a=n.getSingleValueFromFeatures(this.config.statistic,this.dataSource,this.features),
a=this._getVaildValue(a);"number"===typeof a&&(this.value=a,this._setValue(this.config))}},setConfig:function(a){a&&(this.config=a,this.config.display&&this.config.display.backgroundColor&&m.setStyle(this.domNode,"backgroundColor",this.config.display.backgroundColor),this._updateStatisticsValue())},_setValue:function(a){var b={};b.series=[{data:[this.value]}];var e=!1;"undefined"!==typeof a.max&&"undefined"!==typeof a.min&&(b.max=a.max,b.min=a.min);var g={},h=this._getIndicatorInfo(a);if(k.isNotEmptyObject(a.display)){var d=
a.display;d.backgroundColor&&m.setStyle(this.domNode,"backgroundColor",d.backgroundColor);d.gaugeColor&&(g.columnColor=d.gaugeColor);d.bgColor&&(g.bgColor=d.bgColor);if(k.isNotEmptyObject(d.dataLabels)&&d.dataLabels.state){var c=d.dataLabels;g.showDataRangeLabel=!!c.dataRange;g.showTargetValueLabel=!!c.targetValue;e=g.showTargetValueLabel;g.labelColor=c.textColor||""}c={state:!0,isRatio:!1,font:{font:{fontFamily:"Arial",bold:!1,italic:!1,underline:!1},textColor:"#59bad8"},dataFormat:{unit:"none",
decimalPlaces:"",prefix:"",suffix:""}};c=d.currentValue.state?d.currentValue:c;if(k.isNotEmptyObject(c)){var d={},f=c.dataFormat;f&&""!==f.decimalPlaces&&"undefined"!==typeof f.decimalPlaces&&(d.decimalPlaces=Number(f.decimalPlaces));f=l.hitch(this,function(c,g){var b,d,f="";c.isRatio?(b=g/a.max,b*=100,f="%"):b=g;if(c.dataFormat){var e=c.dataFormat;c.isRatio||("percentage"===e.unit?(b*=100,f="%"):"thousand"===e.unit?(f=this.nls.thousandAbbreviation,b/=1E3):"million"===e.unit?(f=this.nls.millionAbbreviation,
b/=1E6):"billion"===e.unit&&(f=this.nls.billionAbbreviation,b/=1E9));""!==e.decimalPlaces&&"undefined"!==typeof e.decimalPlaces&&(b=b.toFixed(Number(e.decimalPlaces)));d=b+f;e.prefix&&(d=e.prefix+" "+d);e.suffix&&(d+=" "+e.suffix)}return d},c,this.value);d.formatter=f;c.font&&(f={},"undefined"!==typeof c.font.fontSize&&(f.fontSize=Number(c.font.fontSize)),c.font.textColor&&(f.color=c.font.textColor),h.valueColor&&(f.color=h.valueColor),c.font&&c.font.font&&(c=c.font.font,f.fontWeight=c.bold?"bold":
"normal",c.fontFamily&&(f.fontFamily=c.fontFamily),f.fontStyle=c.italic?"italic":"normal"),d.textStyle=f);g.valueStyle=d}}h.targetValue&&(g.targetValue=e?h.targetValue:[]);h.columnColor&&(g.columnColor=h.columnColor);b.gaugeOption=g;this.chart.updateConfig(b)},_getIndicatorInfo:function(a){var b=!1,e=!1,g=!1,h=this._getIndicatorValues(a);k.isNotEmptyObject(h,!0)&&(b=h);if(h=a.indicators)(a=n.getVaildIndicator(this.value,h,a.max))&&a.gaugeColor&&(e=a.gaugeColor),a&&a.valueColor&&(g=a.valueColor);return{targetValue:b,
columnColor:e,valueColor:g}},_initChart:function(){this.chart=new r({chartDom:this.domNode,config:this.DEFAULT_GAUGE_CONFIG});this.chart.placeAt(this.domNode);setTimeout(l.hitch(this,function(){this.chart.resize()}),300)},_getVaildValue:function(a){if("undefined"!==typeof a)return Number(a)},_getIndicatorValues:function(a){var b=[];a.indicators&&(a.indicators.forEach(function(e){e.value&&e.value.forEach(l.hitch(this,function(g){b.push(e.isRatio?g/100*a.max:g)}))}),b.sort(function(a,b){return a-b}),
b=k.uniqueArray(b));return b}})});