// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/_base/lang dojo/_base/array esri/geometry/geometryEngine jimu/utils jimu/DataSourceManager jimu/statisticsUtils".split(" "),function(l,g,k,m,n,p,q){return{getClientFeaturesFromMap:function(a,b,f,e){var c=[],d=!1;f?0<b.getSelectedFeatures().length?(c=b.getSelectedFeatures(),d=!0):c=b.graphics:c=b.graphics;e&&(c=this._filterFeaturesByExtent(a.extent,c));if(0<c.length){var h=n.getObjectIdField(b);h&&(a=c[0])&&a.attributes&&a.attributes.hasOwnProperty(h)&&c.sort(function(a,c){a.attributes||
(a.attributes={});c.attributes||(c.attributes={});var b=a.attributes[h],d=c.attributes[h];return b<d?-1:b>d?1:0})}c.isSelectedFeatures=d;return c},listenClientFeaturesFromMap:function(a,b,f,e,c){var d=[];f&&(d.push(l(b,"selection-complete",g.hitch(this,function(){c(this.getClientFeaturesFromMap(a,b,f,e))}))),d.push(l(b,"selection-clear",g.hitch(this,function(){c(this.getClientFeaturesFromMap(a,b,f,e))}))));e&&d.push(l(a,"extent-change",g.hitch(this,function(){0<b.graphics.length&&c(this.getClientFeaturesFromMap(a,
b,f,e))})));d.push(l(b,"update-end",g.hitch(this,function(){c(this.getClientFeaturesFromMap(a,b,f,e))})));c(this.getClientFeaturesFromMap(a,b,f,e));return{remove:function(){d&&k.forEach(d,g.hitch(this,function(a){a.remove()}));d=null}}},getVaildIndicator:function(a,b,f){var e=[];b.map(g.hitch(this,function(c){(c=this._handleOperator(c,a,f))&&e.push(c)}));if(0<e.length)return e[e.length-1]},getSingleValueFromFeatures:function(a,b,f){var e=p.getInstance(),c=0;if("Features"===a.type){if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===
b.dataSourceType||"Features"===e.getDataSourceConfig(b.frameWorkDsId).type)return f.length;c=0;k.forEach(f,function(a){c+=a.attributes.count});return c}if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===b.dataSourceType||"Features"===e.getDataSourceConfig(b.frameWorkDsId).type)return this._getStatsFromFeatures(f,a.fieldName,a.statisticsType);var d=0,h=0,c=0;k.forEach(f,function(b){var e=b.attributes[a.fieldName+"_"+a.statisticsType];switch(a.statisticsType){case "sum":d+=e;break;case "min":d=Math.min(d,e);
break;case "max":d=Math.max(d,e);break;case "avg":h+=b.attributes[a.fieldName+"_sum"],c+=b.attributes.count}});"avg"===a.statisticsType&&(d=0===c?0:h/c);return d},filterFeaturesByDataSourceSetting:function(a,b,f){if(0===a.length)return[];if(b.useSelection){var e=a[0].getLayer();if(e){var c=e.getSelectedFeatures();0<c.length&&(a=k.filter(a,function(a){return-1<c.indexOf(a)}))}}b.filterByExtent&&(a=this._filterFeaturesByExtent(f.extent,a));return a},_getStatsFromFeatures:function(a,b,f){return q.getStatisticsResultFromClientSync({featureSet:{features:a},
fieldName:b,statisticTypes:[f]})[f+"Field"]},_filterFeaturesByExtent:function(a,b){var f=a.normalize();return b=k.filter(b,g.hitch(this,function(a){try{if(a.geometry){var b="point"===a.geometry.type||"multipoint"===a.geometry;return k.some(f,g.hitch(this,function(c){return b?c.contains(a.geometry):m.intersects(c,a.geometry)}))}}catch(d){console.error(d)}return!1}))},_handleOperator:function(a,b,f){function e(a){c={};a.valueColor&&(c.valueColor=a.valueColor);a.gaugeColor&&(c.gaugeColor=a.gaugeColor);
a.iconInfo&&(c.iconInfo=a.iconInfo)}var c,d=a.value.map(g.hitch(this,function(b){return a.isRatio?b/100*f:b}));"greater"===a.operator&&b>d[0]?e(a):"smaller"===a.operator&&b<d[0]?e(a):"between"===a.operator&&b>d[0]&&b<d[1]?e(a):"equal"===a.operator&&b===d[0]?e(a):"notEqual"===a.operator&&b!==d[0]&&e(a);return c},isInteger:function(a){return"number"===typeof a&&0===a%1}}});