// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["dojo/_base/declare","dojo/_base/array","dojo/_base/Deferred","esri/tasks/GeometryService"],function(g,h,f,k){return g(null,{constructor:function(c){this.appConfig=c.appConfig;this.nls=c.nls;(c=this.appConfig.geometryService)||(c="//utility.arcgisonline.com/arcgis/rest/services/Geometry/GeometryServer");this.geomService=new k(c)},getCleanInput:function(c){c=c.replace(/\n/g,"");c=c.replace(/\s+/g," ").trim();return c.toUpperCase()},getCoordValues:function(c,d,b){var a=new f;c={sr:4326,coordinates:[[c.x,
c.y]],conversionType:d.name?d.name:d,numOfDigits:b||6,rounding:!0,addSpaces:!1};switch(d){case "DD":c.numOfDigits=6;break;case "USNG":c.numOfDigits=5;break;case "MGRS":c.conversionMode="mgrsDefault";c.numOfDigits=5;break;case "UTM (H)":c.conversionType="utm";c.conversionMode="utmNorthSouth";c.addSpaces=!0;break;case "UTM":c.conversionType="utm";c.conversionMode="utmDefault";c.addSpaces=!0;break;case "GARS":c.conversionMode="garsDefault"}this.geomService.toGeoCoordinateString(c).then(function(b){a.resolve(b)},
function(){a.resolve(null)});return a.promise},getXYNotation:function(c,d){var b=new f,a;a=d.name?d.name:d;var e={sr:4326,conversionType:a,strings:[]};switch(a){case "DD":case "DDM":case "DMS":e.numOfDigits=2;a=c.replace(/[\u00b0\u02da\u00ba^~*"'\u2032\u00a8\u02dd]/g,"");e.strings.push(a);break;case "DDrev":e.conversionType="DD";e.numOfDigits=2;a=c.replace(/[\u00b0\u02da\u00ba^~*"'\u2032\u00a8\u02dd]/g,"");e.strings.push(a);break;case "DDMrev":e.conversionType="DDM";e.numOfDigits=2;a=c.replace(/[\u00b0\u02da\u00ba^~*"'\u2032\u00a8\u02dd]/g,
"");e.strings.push(a);break;case "DMSrev":e.conversionType="DMS";e.numOfDigits=2;a=c.replace(/[\u00b0\u02da\u00ba^~*"'\u2032\u00a8\u02dd]/g,"");e.strings.push(a);break;case "USNG":e.strings.push(c);e.addSpaces="false";break;case "MGRS":e.conversionMode="mgrsNewStyle";e.strings.push(c);e.addSpaces="false";break;case "UTM (H)":e.conversionType="utm";e.conversionMode="utmNorthSouth";e.strings.push(c);break;case "UTM":e.conversionType="utm";e.conversionMode="utmDefault";e.strings.push(c);break;case "GARS":e.conversionMode=
"garsCenter";e.strings.push(c);break;case "GEOREF":e.strings.push(c)}this.geomService.fromGeoCoordinateString(e).then(function(a){b.resolve(a)},function(){b.resolve(null)});return b.promise},getNotations:function(){return[{name:"DD",pattern:/^(([NS\+\-\s])*([0-8]?\d([,.]\d*)?|90([,.]0*)?)([\u00b0\u02da\u00ba^~*]*)([NS\+\-\s])*)([,:;\s|\/\\]+)(([EW\+\-\s])*([0]?\d?\d([,.]\d*)?|1[0-7]\d([,.]\d*)?|180([,.]0*)?)([\u00b0\u02da\u00ba^~*]*)([EW\+\-\s])*)$/,notationType:this.nls.DDLatLongNotation,conversionType:"DD"},
{name:"DDrev",pattern:/^(([EW\+\-\s])*([0]?\d?\d([,.]\d*)?|1[0-7]\d([,.]\d*)?|180([,.]0*)?)([\u00b0\u02da\u00ba^~*]*)([EW\+\-\s])*)([,:;\s|\/\\]+)(([NS\+\-\s])*([0-8]?\d([,.]\d*)?|90([,.]0*)?)([\u00b0\u02da\u00ba^~*]*)([NS\+\-\s])*)$/,notationType:this.nls.DDLongLatNotation,conversionType:"DD"},{name:"DDM",pattern:/^(([NS\+\-\s])*([0-8]?\d|90)[\u00b0\u02da\u00ba^~*\s\-_]+(([0-5]?\d|\d)([,.]\d*)?)['\u2032\s_]*([NS\+\-\s])*)([,:;\s|\/\\]+)(([EW\+\-\s])*([0]?\d?\d|1[0-7]\d|180)[\u00b0\u02da\u00ba^~*\s\-_]+(([0-5]\d|\d)([,.]\d*)?)['\u2032\s_]*([EW\+\-\s])*)[\s]*$/,
notationType:this.nls.DDMLatLongNotation,conversionType:"DDM"},{name:"DDMrev",pattern:/^(([EW\+\-\s])*([0]?\d?\d|1[0-7]\d|180)[\u00b0\u02da\u00ba^~*\s\-_]+(([0-5]\d|\d)([,.]\d*)?)['\u2032\s_]*([EW\+\-\s])*)([,:;\s|\/\\]+)(([NS\+\-\s])*([0-8]?\d|90)[\u00b0\u02da\u00ba^~*\s\-_]+(([0-5]?\d|\d)([,.]\d*)?)['\u2032\s_]*([NS\+\-\s])*)[\s]*$/,notationType:this.nls.DDMLongLatNotation,conversionType:"DDM"},{name:"DMS",pattern:/^(([NS\+\-\s])*([0-8]?\d|90)[\u00b0\u02da\u00ba^~*\s\-_]+([0-5]?\d|\d)['\u2032\s\-_]+(([0-5]?\d|\d)([,.]\d*)?)["\u00a8\u02dd\s_]*([NS\+\-\s])*)([,:;\s|\/\\]+)(([EW\+\-\s])*([0]?\d?\d|1[0-7]\d|180)[\u00b0\u02da\u00ba^~*\s\-_]+([0-5]\d|\d)['\u2032\s\-_]+(([0-5]?\d|\d)([,.]\d*)?)["\u00a8\u02dd\s_]*([EW\+\-\s])*)[\s]*$/,
notationType:this.nls.DMSLatLongNotation,conversionType:"DMS"},{name:"DMSrev",pattern:/^(([EW\+\-\s])*([0]?\d?\d|1[0-7]\d|180)[\u00b0\u02da\u00ba^~*\s\-_]+([0-5]\d|\d)['\u2032\s\-_]+(([0-5]?\d|\d)([,.]\d*)?)["\u00a8\u02dd\s_]*([EW\+\-\s])*)([,:;\s|\/\\]+)(([NS\+\-\s])*([0-8]?\d|90)[\u00b0\u02da\u00ba^~*\s\-_]+([0-5]?\d|\d)['\u2032\s\-_]+(([0-5]?\d|\d)([,.]\d*)?)["\u00a8\u02dd\s_]*([NS\+\-\s])*)[\s]*$/,notationType:this.nls.DMSLongLatNotation,conversionType:"DMS"},{name:"GARS",pattern:/^\d{3}[a-zA-Z]{2}[1-4]?[1-9]?$/,
notationType:this.nls.GARSNotation,conversionType:"GARS"},{name:"GEOREF",pattern:/^[a-zA-Z]{4}\d{1,8}$/,notationType:this.nls.GEOREFNotation,conversionType:"GEOREF"},{name:"MGRS",pattern:/^\d{1,2}[-,;:\s]*[C-HJ-NP-X][-,;:\s]*[A-HJ-NP-Z]{2}[-,;:\s]*(\d[-,;:\s]+\d|\d{2}[-,;:\s]+\d{2}|\d{3}[-,;:\s]+\d{3}|\d{4}[-,;:\s]+\d{4}|\d{5}[-,;:\s]+\d{5})$|^(\d{1,2}[-,;:\s]*[C-HJ-NP-X][-,;:\s]*[A-HJ-NP-Z]{2}[-,;:\s]*)(\d{2}|\d{4}|\d{6}|\d{8}|\d{10})?$|^[ABYZ][-,;:\s]*[A-HJ-NP-Z]{2}[-,;:\s]*(\d[-,;:\s]+\d|\d{2}[-,;:\s]+\d{2}|\d{3}[-,;:\s]+\d{3}|\d{4}[-,;:\s]+\d{4}|\d{5}[-,;:\s]+\d{5})$|^[ABYZ][-,;:\s]*[A-HJ-NP-Z]{2}[-,;:\s]*(\d{2}|\d{4}|\d{6}|\d{8}|\d{10})?$/,
notationType:this.nls.MGRSNotation,conversionType:"MGRS"},{name:"UTM",pattern:/^\d{1,2}[-,;:\s]*[c-hj-np-xC-HJ-NP-X][-,;:\s]*\d{1,6}\.?\d*[mM]?[-,;:\s]?\d{1,7}\.?\d*[mM]?$/,notationType:this.nls.UTMBandNotation,conversionType:"UTM"},{name:"UTM (H)",pattern:/^\d{1,2}[-,;:\s]*[NnSs][-,;:\s]*\d{1,6}\.?\d*[mM]?[-,;:\s]+\d{1,7}\.?\d*[mM]?$/,notationType:this.nls.UTMHemNotation,conversionType:"UTM (H)"}]},getCoordinateType:function(c){var d=this.getCleanInput(c);c=new f;var b=this.getNotations(),d=h.filter(b,
function(a){return a.pattern.test(this.v)},{v:d});0<d.length?c.resolve(d):c.resolve(null);return c.promise},getFormattedDDStr:function(c,d,b){var a={};a.sourceValue=c;a.sourceFormatString=d;c=c[0].split(/[ ,]+/);a.latdeg=c[0].replace(/[nNsS]/,"");a.londeg=c[1].replace(/[eEwW]/,"");b&&("N"===c[0].slice(-1)?a.latdeg="+"+a.latdeg:a.latdeg="-"+a.latdeg,"W"===c[1].slice(-1)?a.londeg="-"+a.londeg:a.londeg="+"+a.londeg);d=d.replace(/X/,a.londeg);d=d.replace(/[eEwW]/,c[1].slice(-1));d=d.replace(/[nNsS]/,
c[0].slice(-1));d=d.replace(/Y/,a.latdeg);a.formatResult=d;return a},getFormattedDDMStr:function(c,d,b){var a={};a.sourceValue=c;a.sourceFormatString=d;a.parts=c[0].split(/[ ,]+/);a.latdeg=a.parts[0];a.latmin=a.parts[1].replace(/[nNsS]/,"");a.londeg=a.parts[2];a.lonmin=a.parts[3].replace(/[eEwW]/,"");b&&("N"===a.parts[1].slice(-1)?a.latdeg="+"+a.latdeg:a.latdeg="-"+a.latdeg,"W"===a.parts[3].slice(-1)?a.londeg="-"+a.londeg:a.londeg="+"+a.londeg);c=d.replace(/[EeWw]/,a.parts[3].slice(-1));c=c.replace(/Y/,
a.lonmin);c=c.replace(/X/,a.londeg);c=c.replace(/[NnSs]/,a.parts[1].slice(-1));c=c.replace(/B/,a.latmin);c=c.replace(/A/,a.latdeg);a.formatResult=c;return a},getFormattedDMSStr:function(c,d,b){var a={};a.sourceValue=c;a.sourceFormatString=d;a.parts=c[0].split(/[ ,]+/);a.latdeg=a.parts[0];a.latmin=a.parts[1];a.latsec=a.parts[2].replace(/[NnSs]/,"");a.londeg=a.parts[3];a.lonmin=a.parts[4];a.parts[5]&&(a.lonsec=a.parts[5].replace(/[EWew]/,""));b&&("N"===a.parts[2].slice(-1)?a.latdeg="+"+a.latdeg:a.latdeg=
"-"+a.latdeg,"W"===a.parts[5].slice(-1)?a.londeg="-"+a.londeg:a.londeg="+"+a.londeg);c=d.replace(/A/,a.latdeg);c=c.replace(/B/,a.latmin);c=c.replace(/C/,a.latsec);c=c.replace(/X/,a.londeg);c=c.replace(/Y/,a.lonmin);c=c.replace(/Z/,a.lonsec);c=c.replace(/[NnSs]/,a.parts[2].slice(-1));a.parts[5]&&(c=c.replace(/[EeWw]/,a.parts[5].slice(-1)));a.formatResult=c;return a},getFormattedUSNGStr:function(c,d){var b={};b.sourceValue=c;b.sourceFormatString=d;c[0].match(/^[ABYZ]/)?b.gzd=c[0].match(/[ABYZ]/)[0].trim():
b.gzd=c[0].match(/\d{1,2}[C-HJ-NP-X]/)[0].trim();c[0].replace(b.gzd,"").match(/[a-hJ-zA-HJ-Z]{2}/)&&(b.grdsq=c[0].replace(b.gzd,"").match(/[a-hJ-zA-HJ-Z]{2}/)[0].trim());c[0].replace(b.gzd+b.grdsq,"").match(/^\d{1,5}/)&&(b.easting=c[0].replace(b.gzd+b.grdsq,"").match(/^\d{1,5}/)[0].trim());c[0].replace(b.gzd+b.grdsq,"").match(/\d{1,5}$/)&&(b.northing=c[0].replace(b.gzd+b.grdsq,"").match(/\d{1,5}$/)[0].trim());var a=d.replace(/Y/,b.northing),a=a.replace(/X/,b.easting),a=a.replace(/S/,b.grdsq),a=a.replace(/Z/,
b.gzd);b.formatResult=a;return b},getFormattedMGRSStr:function(c,d){var b={};b.sourceValue=c;b.sourceFormatString=d;c[0].match(/^[ABYZ]/)?b.gzd=c[0].match(/[ABYZ]/)[0].trim():b.gzd=c[0].match(/\d{1,2}[C-HJ-NP-X]/)[0].trim();b.grdsq=c[0].replace(b.gzd,"").match(/[a-hJ-zA-HJ-Z]{2}/)[0].trim();b.easting=c[0].replace(b.gzd+b.grdsq,"").match(/^\d{1,5}/)[0].trim();b.northing=c[0].replace(b.gzd+b.grdsq,"").match(/\d{1,5}$/)[0].trim();var a=d.replace(/Y/,b.northing),a=a.replace(/X/,b.easting),a=a.replace(/S/,
b.grdsq),a=a.replace(/Z/,b.gzd);b.formatResult=a;return b},getFormattedGARSStr:function(c,d){var b={};b.sourceValue=c;b.sourceFormatString=d;b.lon=c[0].match(/\d{3}/);b.lat=c[0].match(/[a-zA-Z]{2}/);var a=c[0].match(/\d*$/);b.quadrant=a[0][0];b.key=a[0][1];a=d.replace(/K/,b.key);a=a.replace(/Q/,b.quadrant);a=a.replace(/Y/,b.lat);a=a.replace(/X/,b.lon);b.formatResult=a;return b},getFormattedGEOREFStr:function(c,d){var b={};b.sourceValue=c;b.sourceFormatString=d;b.lon=c[0].match(/[a-zA-Z]{1}/)[0].trim();
b.lat=c[0].replace(b.lon,"").match(/[a-zA-Z]{1}/)[0].trim();b.quadrant15lon=c[0].replace(b.lon+b.lat,"").match(/[a-zA-Z]{1}/)[0].trim();b.quadrant15lat=c[0].replace(b.lon+b.lat+b.quadrant15lon,"").match(/[a-zA-Z]{1}/)[0].trim();var a=c[0].replace(b.lon+b.lat+b.quadrant15lon+b.quadrant15lat,"");b.quadrant1lon=a.substr(0,a.length/2);b.quadrant1lat=a.substr(a.length/2,a.length);a=d.replace(/Y/,b.quadrant1lat);a=a.replace(/X/,b.quadrant1lon);a=a.replace(/D/,b.quadrant15lat);a=a.replace(/C/,b.quadrant15lon);
a=a.replace(/B/,b.lat);a=a.replace(/A/,b.lon);b.formatResult=a;return b},getFormattedUTMStr:function(c,d){var b={};b.sourceValue=c;b.sourceFormatString=d;b.parts=c[0].split(/[ ,]+/);b.zone=b.parts[0].replace(/[A-Z]/,"");b.bandLetter=b.parts[0].slice(-1);b.easting=b.parts[1];b.westing=b.parts[2];var a=d.replace(/Y/,b.westing),a=a.replace(/X/,b.easting),a=a.replace(/B/,b.bandLetter),a=a.replace(/Z/,b.zone);b.formatResult=a;return b},getFormattedUTMHStr:function(c,d){var b={};b.sourceValue=c;b.sourceFormatString=
d;b.parts=c[0].split(/[ ,]+/);b.zone=b.parts[0].replace(/[A-Z]/,"");b.hemisphere=b.parts[0].slice(-1);b.easting=b.parts[1];b.westing=b.parts[2];var a=d.replace(/Y/,b.westing),a=a.replace(/X/,b.easting),a=a.replace(/H/,b.hemisphere),a=a.replace(/Z/,b.zone);b.formatResult=a;return b}})});