// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"jimu/layoutManagers/BaseLayoutManager":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dijit/_WidgetBase dojo/Deferred dojo/promise/all ../utils ../WidgetPlaceholder ../OnScreenWidgetIcon".split(" "),function(q,e,b,f,g,r,h,m,v,k){var t=null,p;p=q([g],{constructor:function(){this.widgetPlaceholders=[];this.onScreenWidgetIcons=[];this.invisibleWidgetIds=[]},name:"BaseLayoutManager",mapId:"map",map:null,layoutId:"jimu-layout-manager",postCreate:function(){this.containerNode=
this.domNode;this.layoutId=jimuConfig.layoutId},resize:function(){},isSupportEdit:function(){return!1},getMapDiv:function(){},setMap:function(a){this.map=a},onEnter:function(a,c){this.appConfig=a;this.mapId=c},onLeave:function(){},onThemeLoad:function(){},loadAndLayout:function(a){},openWidget:function(a){},onLayoutChange:function(a){},onWidgetChange:function(a,c){},onGroupChange:function(a,c){},onWidgetPoolChange:function(a,c){this.reloadControllerWidget(a,c.controllerId)},onActionTriggered:function(a){},
onLayoutDefinitionChange:function(a,c){},onOnScreenGroupsChange:function(a,c){},destroyOnScreenWidgetsAndGroups:function(a){},loadOnScreenWidgets:function(a){var c=[];b.forEach(a.widgetOnScreen.widgets,function(d){!1===d.visible?this.invisibleWidgetIds.push(d.id):c.push(this.loadOnScreenWidget(d,a))},this);return h(c)},loadOnScreenWidget:function(a,c){var d=new r;if("config"===c.mode&&!a.uri){var b=this._createOnScreenWidgetPlaceHolder(a);d.resolve(b);return d}if(!a.uri)return d.resolve(null),d;a.inPanel||
a.closeable?(b=this._createOnScreenWidgetIcon(a),d.resolve(b)):this.widgetManager.loadWidget(a).then(e.hitch(this,function(l){try{l.setPosition(l.position),this.widgetManager.openWidget(l)}catch(n){console.log(console.error("fail to startup widget "+l.name+". "+n.stack))}l.configId=a.id;d.resolve(l)}),function(a){d.reject(a)});return d},onOnScreenWidgetChange:function(a,c){c=a.getConfigElementById(c.id);c.isController?this.reloadControllerWidget(a,c.id):(b.forEach(this.widgetPlaceholders,function(d){d.configId===
c.id&&(d.destroy(),this.loadOnScreenWidget(c,a))},this),this.removeDestroyed(this.widgetPlaceholders),this._updatePlaceholder(a),b.forEach(this.onScreenWidgetIcons,function(d){if(d.configId===c.id){var b=d.state;d.destroy();this.loadOnScreenWidget(c,a).then(function(a){if(c.uri&&"opened"===b)a.onClick()})}},this),this.removeDestroyed(this.onScreenWidgetIcons),b.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(d){d.configId===c.id&&(d.destroy(),!1===c.visible?0>this.invisibleWidgetIds.indexOf(c.id)&&
this.invisibleWidgetIds.push(c.id):this.loadOnScreenWidget(c,a))},this),b.forEach(this.invisibleWidgetIds,function(d){d===c.id&&!1!==c.visible&&(this.loadOnScreenWidget(c,a),d=this.invisibleWidgetIds.indexOf(c.id),this.invisibleWidgetIds.splice(d,1))},this),c.isOnScreen||b.forEach(this.widgetManager.getControllerWidgets(),function(d){d.widgetIsControlled(c.id)&&this.reloadControllerWidget(a,d.id)},this))},destroyOnScreenWidgetIcons:function(){b.forEach(this.onScreenWidgetIcons,function(a){a.destroy()},
this);this.onScreenWidgetIcons=[]},destroyOnScreenOffPanelWidgets:function(){b.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(a){this.widgetManager.destroyWidget(a)},this)},destroyWidgetPlaceholders:function(){b.forEach(this.widgetPlaceholders,function(a){a.destroy()},this);this.widgetPlaceholders=[]},removeDestroyed:function(a){var c=[];b.forEach(a,function(a){a._destroyed&&c.push(a)});b.forEach(c,function(c){c=a.indexOf(c);a.splice(c,1)})},_createOnScreenWidgetPlaceHolder:function(a){var c;
c="map"===a.position.relativeTo?this.mapId:this.layoutId;var d=e.clone(a);d.position.width=40;d.position.height=40;var b=m.getPositionStyle(d.position);a=new v({index:d.placeholderIndex,configId:a.id});f.setStyle(a.domNode,b);f.place(a.domNode,c);this.widgetPlaceholders.push(a);return a},_createOnScreenWidgetIcon:function(a){var c=new k({panelManager:this.panelManager,widgetManager:this.widgetManager,widgetConfig:a,configId:a.id,map:this.map});"map"===a.position.relativeTo?f.place(c.domNode,this.mapId):
f.place(c.domNode,this.layoutId);f.setStyle(c.domNode,m.getPositionStyle({top:a.position.top,left:a.position.left,right:a.position.right,bottom:a.position.bottom,width:40,height:40}));c.startup();!this.openAtStartWidget&&a.openAtStart&&(c.switchToOpen(),this.openAtStartWidget=a.name);this.onScreenWidgetIcons.push(c);return c},reloadControllerWidget:function(a,c){var d=this.widgetManager.getWidgetById(c);if(d){var b=d.getOpenedIds(),l=d.windowState;this._destroyControllerWidget(d);this._loadControllerWidget(a,
c,b,l)}else this._loadControllerWidget(a,c)},_destroyControllerWidget:function(a){b.forEach(a.getAllConfigs(),function(a){if(a.widgets)this.panelManager.destroyPanel(a.id+"_panel"),b.forEach(a.widgets,function(a){this.panelManager.destroyPanel(a.id+"_panel")},this);else{var c=this.widgetManager.getWidgetById(a.id);c&&(a.inPanel?this.panelManager.destroyPanel(c.getPanel()):this.widgetManager.destroyWidget(c))}},this);this.widgetManager.destroyWidget(a)},_loadControllerWidget:function(a,c,d,b){c=a.getConfigElementById(c);
!1!==c.visible&&this.loadOnScreenWidget(c,a).then(e.hitch(this,function(a){b&&this.widgetManager.changeWindowStateTo(a,b);d&&a.setOpenedIds(d)}))},_updatePlaceholder:function(a){b.forEach(this.widgetPlaceholders,function(c){c.setIndex(a.getConfigElementById(c.configId).placeholderIndex)},this)}});p.getInstance=function(){null===t&&(t=new p);return t};return p})},"jimu/WidgetPlaceholder":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/html","dijit/_WidgetBase","./utils"],function(q,
e,b,f,g){return q(f,{"class":"jimu-widget-placeholder",postCreate:function(){this.inherited(arguments);this.indexNode=b.create("div",{"class":"inner",innerHTML:this.index},this.domNode);b.setAttr(this.domNode,"title",window.jimuNls.widgetPlaceholderTooltip)},moveTo:function(f){var h={left:"auto",right:"auto",bottom:"auto",top:"auto",width:"auto",height:"auto"},h=e.mixin(h,g.getPositionStyle(f));delete h.width;delete h.height;b.setStyle(this.domNode,h)},setIndex:function(b){this.index=b;this.indexNode.innerHTML=
b}})})},"jimu/OnScreenWidgetIcon":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dijit/_WidgetBase ./utils".split(" "),function(q,e,b,f,g,r,h){return q(r,{"class":"jimu-widget-onscreen-icon",postCreate:function(){this.inherited(arguments);this.iconNode=f.create("img",{src:this.widgetConfig.icon},this.domNode);f.setAttr(this.domNode,"title",this.widgetConfig.label);f.setAttr(this.domNode,"data-widget-name",this.widgetConfig.name);this.own(g(this.domNode,
"click",e.hitch(this,function(){this.onClick()})));this.position=e.clone(this.widgetConfig.position);"map"===this.widgetConfig.position.relativeTo&&this.own(g(this.map,"resize",e.hitch(this,function(){var b=e.clone(this.position);delete b.width;delete b.height;this.panel&&this.panel.setPosition(b)})));this.state="closed"},startup:function(){this.inherited(arguments)},onClick:function(){"closed"===this.state?this.switchToOpen():this.switchToClose()},moveTo:function(b){var m={left:"auto",right:"auto",
bottom:"auto",top:"auto",width:"auto",height:"auto"},m=e.mixin(m,h.getPositionStyle(b));delete m.width;delete m.height;f.setStyle(this.domNode,m);this.position=e.clone(b);this.widgetConfig&&this.widgetConfig.panel&&(this.widgetConfig.panel.position=e.clone(b),this.widgetConfig.position=e.clone(b));this.panel&&this.panel.setPosition(e.clone(b));this.widget&&this.widget.setPosition(this.getOffPanelWidgetPosition(this.widget))},destroy:function(){this.panel?this.panelManager.destroyPanel(this.panel):
this.widget&&this.widgetManager.destroyWidget(this.widget);this.inherited(arguments)},switchToOpen:function(){this.state="opened";this.panelManager.closeAllPanelsInGroup(this.widgetConfig.gid);b.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(b){b.closeable&&this.widgetManager.closeWidget(b)},this);f.addClass(this.domNode,"jimu-state-selected");this._showLoading();!1===this.widgetConfig.inPanel?this.widgetManager.loadWidget(this.widgetConfig).then(e.hitch(this,function(b){this.widget=
b;b.setPosition(this.getOffPanelWidgetPosition(b));this.widgetManager.openWidget(b);this.own(g(b,"close",e.hitch(this,function(){this.switchToClose()})));this._hideLoading()})):this.panelManager.showPanel(e.clone(this.widgetConfig)).then(e.hitch(this,function(b){this.panel=b;this.own(g(b,"close",e.hitch(this,function(){this.switchToClose()})));this._hideLoading()}))},switchToClose:function(){this.state="closed";f.removeClass(this.domNode,"jimu-state-selected");!1===this.widgetConfig.inPanel?this.widgetManager.closeWidget(this.widget):
this.panelManager.closePanel(this.panel)},getOffPanelWidgetPosition:function(b){var e={relativeTo:b.position.relativeTo},k=f.getMarginBox(this.domNode);b=this.widgetManager.getWidgetMarginBox(b);var g=f.getMarginBox("map"===e.relativeTo?this.map.id:jimuConfig.layoutId),h=k.t+k.h+1;h+b.h>g.h?e.bottom=g.h-k.t+1:e.top=h;window.isRTL?e.right=0>k.l+k.w-b.w?0:k.l+k.w-b.w:k.l+b.w>g.w?e.right=0:e.left=k.l;return e},_showLoading:function(){f.setAttr(this.iconNode,"src",require.toUrl("jimu")+"/images/loading_circle.gif")},
_hideLoading:function(){f.setAttr(this.iconNode,"src",this.widgetConfig.icon)}})})},"*noref":1}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/topic dojo/dom-construct dojo/dom-geometry dojo/promise/all dojo/when ../WidgetManager ../PanelManager ../utils ../dijit/LoadingShelter ./BaseLayoutManager".split(" "),function(q,e,b,f,g,r,h,m,v,k,t,p,a,c){var d=null,u;u=q([c],{name:"AbsolutePositionLayoutManager",constructor:function(){this.widgetManager=k.getInstance();this.panelManager=t.getInstance();g.subscribe("changeMapPosition",e.hitch(this,this.onChangeMapPosition));
this.onScreenGroupPanels=[]},map:null,resize:function(){b.forEach(this.widgetManager.getAllWidgets(),function(a){!1===a.inPanel&&a.resize()},this)},setMap:function(a){this.inherited(arguments);this.panelManager.setMap(a)},getMapDiv:function(){return f.byId(this.mapId)?f.byId(this.mapId):f.create("div",{id:this.mapId,style:e.mixin({position:"absolute",backgroundColor:"#EEEEEE",overflow:"hidden",minWidth:"1px",minHeight:"1px"},p.getPositionStyle(this.appConfig.map.position))},this.layoutId)},loadAndLayout:function(c){console.time("Load widgetOnScreen");
this.setMapPosition(c.map.position);var n=new a,l=[];n.placeAt(this.layoutId);n.startup();l.push(this.loadOnScreenWidgets(c));b.forEach(c.widgetOnScreen.groups,function(a){l.push(this._loadOnScreenGroup(a,c))},this);m(l).then(e.hitch(this,function(){n&&(n.destroy(),n=null);console.timeEnd("Load widgetOnScreen");g.publish("preloadWidgetsLoaded")}),e.hitch(this,function(){n&&(n.destroy(),n=null);console.timeEnd("Load widgetOnScreen");g.publish("preloadWidgetsLoaded")}))},destroyOnScreenWidgetsAndGroups:function(){this.panelManager.destroyAllPanels();
this.destroyOnScreenOffPanelWidgets();this.destroyWidgetPlaceholders();this.destroyOnScreenWidgetIcons()},openWidget:function(a){b.forEach(this.onScreenWidgetIcons,function(b){b.configId===a&&b.switchToOpen()},this);b.forEach(this.widgetManager.getControllerWidgets(),function(b){b.widgetIsControlled(a)&&b.setOpenedIds([a])},this)},onLayoutChange:function(a){this._changeMapPosition(a);b.forEach(this.widgetPlaceholders,function(b){b.moveTo(a.getConfigElementById(b.configId).position)},this);b.forEach(this.onScreenWidgetIcons,
function(b){b.moveTo(a.getConfigElementById(b.configId).position)},this);b.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(b){if(!b.closeable){var c=a.getConfigElementById(b.id).position;b.setPosition(c)}},this);b.forEach(this.onScreenGroupPanels,function(b){var c=a.getConfigElementById(b.config.id).panel.position;b.setPosition(c)},this)},onWidgetChange:function(a,c){c=a.getConfigElementById(c.id);this.onOnScreenWidgetChange(a,c);b.forEach(this.onScreenGroupPanels,function(a){a.reloadWidget(c)},
this)},onGroupChange:function(a,c){c=a.getConfigElementById(c.id);c.isOnScreen?(this.panelManager.destroyPanel(c.id+"_panel"),this.removeDestroyed(this.onScreenGroupPanels),this._loadOnScreenGroup(c,a)):(b.forEach(this.widgetManager.getControllerWidgets(),function(b){b.isControlled(c.id)&&this.reloadControllerWidget(a,b.id)},this),b.forEach(this.panelManager.panels,function(a){a.config.id===c.id&&a.updateConfig(c)},this))},onActionTriggered:function(a){"highLight"===a.action&&(b.forEach(this.widgetPlaceholders,
function(b){b.configId===a.elementId&&this._highLight(b)},this),b.forEach(this.onScreenWidgetIcons,function(b){b.configId===a.elementId&&this._highLight(b)},this),b.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(b){b.configId===a.elementId&&this._highLight(b)},this),b.forEach(this.onScreenGroupPanels,function(b){b.configId===a.elementId&&this._highLight(b)},this));"removeHighLight"===a.action&&this._removeHighLight();"showLoading"===a.action&&(f.setStyle(jimuConfig.loadingId,"display",
"block"),f.setStyle(jimuConfig.mainPageId,"display","none"));"showApp"===a.action&&(f.setStyle(jimuConfig.loadingId,"display","none"),f.setStyle(jimuConfig.mainPageId,"display","block"))},onChangeMapPosition:function(a){var b=e.clone(this.mapPosition);e.mixin(b,a);this.setMapPosition(b)},setMapPosition:function(a){this.mapPosition=a;a=p.getPositionStyle(a);f.setStyle(this.mapId,a);this.map&&this.map.resize&&this.map.resize()},getMapPosition:function(){return this.mapPosition},_highLight:function(a){if(a.domNode){this.hlDiv&&
this._removeHighLight(a);var b=h.getMarginBox(a.domNode);this.hlDiv=r.create("div",{style:{position:"absolute",left:b.l+"px",top:b.t+"px",width:b.w+"px",height:b.h+"px"},"class":"icon-highlight"},a.domNode,"before")}},_removeHighLight:function(){this.hlDiv&&(r.destroy(this.hlDiv),this.hlDiv=null)},_changeMapPosition:function(a){this.map&&(p.isEqual(this.getMapPosition(),a.map.position)||this.setMapPosition(a.map.position))},_loadOnScreenGroup:function(a,b){return b.mode||a.widgets&&0!==a.widgets.length?
this.panelManager.showPanel(a).then(e.hitch(this,function(b){b.configId=a.id;this.onScreenGroupPanels.push(b);return b})):v(null)}});u.getInstance=function(){null===d&&(d=new u,window._absolutLayoutManager=d);return d};return u});