// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"jimu/layoutManagers/BaseLayoutManager":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dijit/_WidgetBase dojo/Deferred dojo/promise/all ../utils ../WidgetPlaceholder ../OnScreenWidgetIcon".split(" "),function(r,a,d,h,l,p,f,m,k,u){var q=null,t;t=r([l],{constructor:function(){this.widgetPlaceholders=[];this.onScreenWidgetIcons=[];this.invisibleWidgetIds=[]},name:"BaseLayoutManager",mapId:"map",map:null,layoutId:"jimu-layout-manager",postCreate:function(){this.containerNode=
this.domNode;this.layoutId=jimuConfig.layoutId},resize:function(){},isSupportEdit:function(){return!1},getMapDiv:function(){},setMap:function(a){this.map=a},onEnter:function(a,e){this.appConfig=a;this.mapId=e},onLeave:function(){},onThemeLoad:function(){},loadAndLayout:function(a){},openWidget:function(a){},onLayoutChange:function(a){},onWidgetChange:function(a,e){},onGroupChange:function(a,e){},onWidgetPoolChange:function(a,e){this.reloadControllerWidget(a,e.controllerId)},onActionTriggered:function(a){},
onLayoutDefinitionChange:function(a,e){},onOnScreenGroupsChange:function(a,e){},destroyOnScreenWidgetsAndGroups:function(a){},loadOnScreenWidgets:function(a){var e=[];d.forEach(a.widgetOnScreen.widgets,function(g){!1===g.visible?this.invisibleWidgetIds.push(g.id):e.push(this.loadOnScreenWidget(g,a))},this);return f(e)},loadOnScreenWidget:function(n,e){var g=new p;if("config"===e.mode&&!n.uri){var d=this._createOnScreenWidgetPlaceHolder(n);g.resolve(d);return g}if(!n.uri)return g.resolve(null),g;n.inPanel||
n.closeable?(d=this._createOnScreenWidgetIcon(n),g.resolve(d)):this.widgetManager.loadWidget(n).then(a.hitch(this,function(a){try{a.setPosition(a.position),this.widgetManager.openWidget(a)}catch(v){console.log(console.error("fail to startup widget "+a.name+". "+v.stack))}a.configId=n.id;g.resolve(a)}),function(a){g.reject(a)});return g},onOnScreenWidgetChange:function(a,e){e=a.getConfigElementById(e.id);e.isController?this.reloadControllerWidget(a,e.id):(d.forEach(this.widgetPlaceholders,function(g){g.configId===
e.id&&(g.destroy(),this.loadOnScreenWidget(e,a))},this),this.removeDestroyed(this.widgetPlaceholders),this._updatePlaceholder(a),d.forEach(this.onScreenWidgetIcons,function(g){if(g.configId===e.id){var d=g.state;g.destroy();this.loadOnScreenWidget(e,a).then(function(a){if(e.uri&&"opened"===d)a.onClick()})}},this),this.removeDestroyed(this.onScreenWidgetIcons),d.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(g){g.configId===e.id&&(g.destroy(),!1===e.visible?0>this.invisibleWidgetIds.indexOf(e.id)&&
this.invisibleWidgetIds.push(e.id):this.loadOnScreenWidget(e,a))},this),d.forEach(this.invisibleWidgetIds,function(g){g===e.id&&!1!==e.visible&&(this.loadOnScreenWidget(e,a),g=this.invisibleWidgetIds.indexOf(e.id),this.invisibleWidgetIds.splice(g,1))},this),e.isOnScreen||d.forEach(this.widgetManager.getControllerWidgets(),function(g){g.widgetIsControlled(e.id)&&this.reloadControllerWidget(a,g.id)},this))},destroyOnScreenWidgetIcons:function(){d.forEach(this.onScreenWidgetIcons,function(a){a.destroy()},
this);this.onScreenWidgetIcons=[]},destroyOnScreenOffPanelWidgets:function(){d.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(a){this.widgetManager.destroyWidget(a)},this)},destroyWidgetPlaceholders:function(){d.forEach(this.widgetPlaceholders,function(a){a.destroy()},this);this.widgetPlaceholders=[]},removeDestroyed:function(a){var e=[];d.forEach(a,function(a){a._destroyed&&e.push(a)});d.forEach(e,function(e){e=a.indexOf(e);a.splice(e,1)})},_createOnScreenWidgetPlaceHolder:function(d){var e;
e="map"===d.position.relativeTo?this.mapId:this.layoutId;var g=a.clone(d);g.position.width=40;g.position.height=40;var n=m.getPositionStyle(g.position);d=new k({index:g.placeholderIndex,configId:d.id});h.setStyle(d.domNode,n);h.place(d.domNode,e);this.widgetPlaceholders.push(d);return d},_createOnScreenWidgetIcon:function(a){var e=new u({panelManager:this.panelManager,widgetManager:this.widgetManager,widgetConfig:a,configId:a.id,map:this.map});"map"===a.position.relativeTo?h.place(e.domNode,this.mapId):
h.place(e.domNode,this.layoutId);h.setStyle(e.domNode,m.getPositionStyle({top:a.position.top,left:a.position.left,right:a.position.right,bottom:a.position.bottom,width:40,height:40}));e.startup();!this.openAtStartWidget&&a.openAtStart&&(e.switchToOpen(),this.openAtStartWidget=a.name);this.onScreenWidgetIcons.push(e);return e},reloadControllerWidget:function(a,e){var d=this.widgetManager.getWidgetById(e);if(d){var m=d.getOpenedIds(),k=d.windowState;this._destroyControllerWidget(d);this._loadControllerWidget(a,
e,m,k)}else this._loadControllerWidget(a,e)},_destroyControllerWidget:function(a){d.forEach(a.getAllConfigs(),function(a){if(a.widgets)this.panelManager.destroyPanel(a.id+"_panel"),d.forEach(a.widgets,function(a){this.panelManager.destroyPanel(a.id+"_panel")},this);else{var e=this.widgetManager.getWidgetById(a.id);e&&(a.inPanel?this.panelManager.destroyPanel(e.getPanel()):this.widgetManager.destroyWidget(e))}},this);this.widgetManager.destroyWidget(a)},_loadControllerWidget:function(d,e,g,m){e=d.getConfigElementById(e);
!1!==e.visible&&this.loadOnScreenWidget(e,d).then(a.hitch(this,function(a){m&&this.widgetManager.changeWindowStateTo(a,m);g&&a.setOpenedIds(g)}))},_updatePlaceholder:function(a){d.forEach(this.widgetPlaceholders,function(e){e.setIndex(a.getConfigElementById(e.configId).placeholderIndex)},this)}});t.getInstance=function(){null===q&&(q=new t);return q};return t})},"jimu/WidgetPlaceholder":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/html","dijit/_WidgetBase","./utils"],function(r,
a,d,h,l){return r(h,{"class":"jimu-widget-placeholder",postCreate:function(){this.inherited(arguments);this.indexNode=d.create("div",{"class":"inner",innerHTML:this.index},this.domNode);d.setAttr(this.domNode,"title",window.jimuNls.widgetPlaceholderTooltip)},moveTo:function(h){var f={left:"auto",right:"auto",bottom:"auto",top:"auto",width:"auto",height:"auto"},f=a.mixin(f,l.getPositionStyle(h));delete f.width;delete f.height;d.setStyle(this.domNode,f)},setIndex:function(a){this.index=a;this.indexNode.innerHTML=
a}})})},"jimu/OnScreenWidgetIcon":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dijit/_WidgetBase ./utils".split(" "),function(r,a,d,h,l,p,f){return r(p,{"class":"jimu-widget-onscreen-icon",postCreate:function(){this.inherited(arguments);this.iconNode=h.create("img",{src:this.widgetConfig.icon},this.domNode);h.setAttr(this.domNode,"title",this.widgetConfig.label);h.setAttr(this.domNode,"data-widget-name",this.widgetConfig.name);this.own(l(this.domNode,
"click",a.hitch(this,function(){this.onClick()})));this.position=a.clone(this.widgetConfig.position);"map"===this.widgetConfig.position.relativeTo&&this.own(l(this.map,"resize",a.hitch(this,function(){var d=a.clone(this.position);delete d.width;delete d.height;this.panel&&this.panel.setPosition(d)})));this.state="closed"},startup:function(){this.inherited(arguments)},onClick:function(){"closed"===this.state?this.switchToOpen():this.switchToClose()},moveTo:function(d){var k={left:"auto",right:"auto",
bottom:"auto",top:"auto",width:"auto",height:"auto"},k=a.mixin(k,f.getPositionStyle(d));delete k.width;delete k.height;h.setStyle(this.domNode,k);this.position=a.clone(d);this.widgetConfig&&this.widgetConfig.panel&&(this.widgetConfig.panel.position=a.clone(d),this.widgetConfig.position=a.clone(d));this.panel&&this.panel.setPosition(a.clone(d));this.widget&&this.widget.setPosition(this.getOffPanelWidgetPosition(this.widget))},destroy:function(){this.panel?this.panelManager.destroyPanel(this.panel):
this.widget&&this.widgetManager.destroyWidget(this.widget);this.inherited(arguments)},switchToOpen:function(){this.state="opened";this.panelManager.closeAllPanelsInGroup(this.widgetConfig.gid);d.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(a){a.closeable&&this.widgetManager.closeWidget(a)},this);h.addClass(this.domNode,"jimu-state-selected");this._showLoading();!1===this.widgetConfig.inPanel?this.widgetManager.loadWidget(this.widgetConfig).then(a.hitch(this,function(d){this.widget=
d;d.setPosition(this.getOffPanelWidgetPosition(d));this.widgetManager.openWidget(d);this.own(l(d,"close",a.hitch(this,function(){this.switchToClose()})));this._hideLoading()})):this.panelManager.showPanel(a.clone(this.widgetConfig)).then(a.hitch(this,function(d){this.panel=d;this.own(l(d,"close",a.hitch(this,function(){this.switchToClose()})));this._hideLoading()}))},switchToClose:function(){this.state="closed";h.removeClass(this.domNode,"jimu-state-selected");!1===this.widgetConfig.inPanel?this.widgetManager.closeWidget(this.widget):
this.panelManager.closePanel(this.panel)},getOffPanelWidgetPosition:function(a){var d={relativeTo:a.position.relativeTo},f=h.getMarginBox(this.domNode);a=this.widgetManager.getWidgetMarginBox(a);var l=h.getMarginBox("map"===d.relativeTo?this.map.id:jimuConfig.layoutId),m=f.t+f.h+1;m+a.h>l.h?d.bottom=l.h-f.t+1:d.top=m;window.isRTL?d.right=0>f.l+f.w-a.w?0:f.l+f.w-a.w:f.l+a.w>l.w?d.right=0:d.left=f.l;return d},_showLoading:function(){h.setAttr(this.iconNode,"src",require.toUrl("jimu")+"/images/loading_circle.gif")},
_hideLoading:function(){h.setAttr(this.iconNode,"src",this.widgetConfig.icon)}})})},"jimu/layoutManagers/GridMobileController":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/aspect dojo/dom-construct dojo/dom-geometry dojo/dom-class dijit/_WidgetBase dijit/_TemplatedMixin jimu/PanelManager jimu/WidgetManager".split(" "),function(r,a,d,h,l,p,f,m,k,u,q,t,n){return r([u,q],{baseClass:"jimu-dnd-mobile-controller",templateString:'\x3cdiv\x3e\x3cdiv class\x3d"icon-section" data-dojo-attach-point\x3d"iconNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"container-section" data-dojo-attach-point\x3d"containerNode"\x3e\x3c/div\x3e\x3c/div\x3e',
appConfig:null,panelContainerNode:null,openIds:null,toolsCount:0,postCreate:function(){this.inherited(arguments);this.panelManager=t.getInstance();this.widgetManager=n.getInstance();this.openIds=[];this.createWidgetIcons();0===this.toolsCount&&h.setStyle(this.domNode,"display","none");this.own(l(this.iconNode,"click",a.hitch(this,function(a){a.stopPropagation();k.contains(this.containerNode,"in")?(k.remove(this.containerNode,"in"),k.add(this.containerNode,"out")):(k.remove(this.containerNode,"out"),
k.add(this.containerNode,"in"))})));this.own(l(document.body,"click",a.hitch(this,function(a){k.contains(this.containerNode,"in")&&!this.isPartOfPopup(a.target||a.srcElement)&&(k.remove(this.containerNode,"in"),k.add(this.containerNode,"out"))})))},destroyOnScreenWidgets:function(){d.forEach(this.appConfig.widgetOnScreen.widgets,function(a){a.inPanel?this.panelManager.destroyPanel(a.id+"_panel"):this.widgetManager.destroyWidget(a.id)},this)},isPartOfPopup:function(a){var d=this.containerNode;return a===
d||h.isDescendant(a,d)},setConfig:function(a){this.appConfig=a;this.createWidgetIcons()},createWidgetIcons:function(){this.toolsCount=0;f.empty(this.containerNode);this.appConfig&&this.appConfig.widgetOnScreen&&d.forEach(this.appConfig.widgetOnScreen.widgets,function(a){a.uri&&a.closeable&&(this._addItem(a),this.toolsCount++)},this)},_addItem:function(d){var e=a.clone(d),h=f.create("div",{"class":"row"},this.containerNode);f.create("div",{"class":"widget-icon column",style:"background: url("+d.icon+
") no-repeat;"},h);f.create("div",{"class":"widget-label jimu-ellipsis column",title:d.label,innerHTML:d.label},h);this.own(l(h,"click",a.hitch(this,function(g){var f;g.stopPropagation();d.inPanel?(f=m.getMarginBox(this.panelContainerNode),e.panel={uri:"themes/DashboardTheme/panels/OnScreenPanel/Panel",position:{relativeTo:"browser",left:f.l,top:f.t,width:f.w,height:f.h}},this.panelManager.showPanel(e).then(a.hitch(this,function(a){this.activePanel=a;a.setPosition({relativeTo:"browser",left:f.l,top:f.t,
width:f.w,height:f.h});return a})).then(a.hitch(this,function(a){this.panelManager.openPanel(a)}))):(f=m.getMarginBox(h),this._toggleOffPanelWidget(d,f.l+f.w,f.t));k.remove(this.containerNode,"in");k.add(this.containerNode,"out")})))},_toggleOffPanelWidget:function(d,f,h){var e=this.openIds.indexOf(d.id);0<=e?(this.widgetManager.closeWidget(d.id),this.openIds.splice(e,1)):this.widgetManager.loadWidget(d).then(a.hitch(this,function(g){this.openIds.push(d.id);g.setPosition({left:f,top:h,zIndex:100,
relativeTo:"map"});this.widgetManager.openWidget(g);this.own(p.after(g,"onClose",a.hitch(this,function(){e=this.openIds.indexOf(d.id);0<=e&&this.openIds.splice(e,1)})))}))},setPanelPosition:function(a){this.activePanel&&(a.relativeTo="layout",this.activePanel.setPosition(a))}})})},"*noref":1}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/topic dojo/on dojo/dom-construct dojo/dom-geometry dojo/Deferred dojo/debounce require ../WidgetManager ../PanelManager ../utils ../dijit/LoadingShelter ./BaseLayoutManager ./GridMobileController".split(" "),function(r,a,d,h,l,p,f,m,k,u,q,t,n,e,g,A,y){var v=null,x;x=r([A],{isEditing:!1,maxStackId:0,dashboardWidgets:[],dashboardPanels:{},currentMode:0,_createLayoutDeferred:null,_isLastLayoutMobile:!1,_isDestroying:!1,
nls:null,_addWidgetTipTemplate:'\x3cdiv class\x3d"tip"\x3e\x3cdiv class\x3d"idx"\x3e${groupIndex}\x3c/div\x3e\x3cdiv class\x3d"label"\x3e${this.nls.addWidgetTip}\x3c/div\x3e\x3c/div\x3e',name:"GridLayoutManager",constructor:function(b,c){this.widgetManager=t.getInstance();this.panelManager=n.getInstance();this.widgetPlaceholders=[];this.preloadWidgetIcons=[];this.preloadGroupPanels=[];this.invisibleWidgetIds=[];e.isMobileUa()?this.own(p(window,"orientationchange",a.hitch(this,this.resize))):this.own(p(window,
"resize",a.hitch(this,this.resize)));this.id=c;this._createLayoutDeferred=null},postMixInProperties:function(){this.inherited(arguments);this.nls={};a.mixin(this.nls,window.jimuNls.gridLayout,window.jimuNls.common);this._addWidgetTipTemplate=this._addWidgetTipTemplate.replace("${this.nls.addWidgetTip}",this.nls.addWidgetTip)},isSupportEdit:function(){return!0},postCreate:function(){this.containerNode=this.domNode;this._isLastLayoutMobile=window.appInfo.isRunInMobile},layout:null,map:null,mapContainer:null,
mapId:"map",hlDiv:null,animTime:500,resize:function(){this._resizeLayout();d.forEach(this.widgetManager.getAllWidgets(),function(a){!1===a.inPanel&&a.resize()},this)},setMap:function(a){this.inherited(arguments);this.panelManager.setMap(a)},_resizeLayout:function(){if(window.appInfo.isRunInMobile){var a=m.getMarginBox(window.jimuConfig.layoutId),a=a.w>a.h?2:1;this.mobilePanel&&(this.currentMode!==a&&(this.currentMode=a,this.mobilePanel.setMobileLayout(a)),this.mobilePanel.resize())}var c;!this.isEditing&&
this.layout?(c=$(this.layoutContainer),a=c.width(),c=c.height(),this.layout.updateSize(a,c)):this.isEditing&&this.editingLayout&&(c=$(this.editLayoutDiv),a=c.width(),c=c.height(),this.editingLayout.updateSize(a,c))},loadAndLayout:function(b){this.appConfig=b;var c=new g;c.placeAt(this.layoutId);c.startup();this._createLayoutDeferred&&!this._createLayoutDeferred.isResolved()?b=this._createLayoutDeferred:(b=new k,b.resolve());b.then(a.hitch(this,this._loadOnScreenGroups)).then(a.hitch(this,this._reArrangeWidgetsLayout,
!0)).then(a.hitch(this,function(){c&&(c.destroy(),c=null);console.timeEnd("Load widgetOnScreen");l.publish("preloadWidgetsLoaded")}),a.hitch(this,function(){c&&(c.destroy(),c=null);console.timeEnd("Load widgetOnScreen");l.publish("preloadWidgetsLoaded")}))},createMapDiv:function(b){h.byId(b)?this.mapDiv=h.byId(b):this.mapDiv=h.create("div",{id:b,style:a.mixin({position:"absolute",backgroundColor:"#EEEEEE",overflow:"hidden",minWidth:"1px",minHeight:"1px"},e.getPositionStyle(this.appConfig.map.position))},
this.layoutId)},getMapDiv:function(){return this.mapDiv},onThemeLoad:function(){this._resizeLayout()},_enableEditing:function(){this.isEditing||(this._createEditingLayout(),$(this.layoutContainer).addClass("hidden"),$(this.editContainer).removeClass("hidden"),$(this.modifyLayoutBtn).addClass("hidden"),this.isEditing=!0,this._resizeLayout())},_disableEditing:function(){$(this.layoutContainer).removeClass("hidden");$(this.editContainer).addClass("hidden");$(this.modifyLayoutBtn).removeClass("hidden");
this.isEditing=!1;this._resizeLayout()},_resetLayoutDefinition:function(){this._disableEditing();this._createLayout(!1,!1);l.publish("editLayoutCancelled")},_saveLayoutDefinition:function(){var b=a.clone(this.editingLayout.toConfig()),c=a.clone(this.appConfig.layoutDefinition);this._simplifyLayoutDefinition(b.content[0]);this._disableEditing();var w=this.editingLayout.root.contentItems[0].getItemsByType("stack"),e=[];d.forEach(w,function(b){!d.some(b.contentItems,a.hitch(this,function(a){if(a.isComponent&&
"map"===a.config.componentName)return!0}))&&/^dd_group_\d+$/.test(b.config.id)&&e.push(b.config.id)});c.layout.config.content=b.content;l.publish("layoutDefinitionChanged",{layoutDefinition:c,groupIds:e})},_simplifyLayoutDefinition:function(b){if("component"!==b.type)if("stack"===b.type){var c;b.activeItemIndex=0;d.some(b.content,a.hitch(this,function(a){if("component"===a.type&&"map"===a.componentName)return c=a,!0}));c?(b.id="map",b.content=[c]):b.content=[]}else d.forEach(b.content,a.hitch(this,
function(a){this._simplifyLayoutDefinition(a)}))},_bindLayoutEvents:function(){this.editingLayout.on("initialised",a.hitch(this,function(){this.editingLayout.createDragSource($(this.dragCreateBtn),{title:" ",type:"component",reorderEnabled:!1,componentName:"widget panel"});var a=this.editingLayout.root.contentItems[0].getItemsByType("stack"),c=[];d.forEach(a,function(a){/^dd_group_\d+$/.test(a.config.id)&&(a=parseInt(a.config.id.split("_")[2],10),c.push(a))});0<c.length?(c=c.sort(function(a,b){return a>
b}),this.maxStackId=c[c.length-1]):this.maxStackId=0;this._arrangeWidgetsInEditingLayout()}));this.editingLayout.on("stackCreated",a.hitch(this,function(a){this.maxStackId++;a.config.id||(a.config.id="dd_group_"+this.maxStackId)}))},_arrangeWidgetsInEditingLayout:function(){d.forEach(this.appConfig.widgetOnScreen.groups,a.hitch(this,function(b){b=this.appConfig.getConfigElementById(b.id);var c=this.editingLayout.root.contentItems[0].getItemsById(b.id),e;c&&0<c.length&&"stack"===c[0].type&&(e=c[0]);
e&&d.forEach(b.widgets,a.hitch(this,function(a,b){var c={id:a.id,type:"component",title:a.label,reorderEnabled:!1,componentName:"widget panel",componentState:{label:a.label}};e.contentItems.length>b?(c=e.contentItems[b],c.config.id=a.id,c.setTitle(a.label)):e.addChild(c)}))}))},_createActionBar:function(b){if(!this.actionBar){this.actionBar=f.create("div",{"class":"layout-actionbar"},b);this.dragCreateBtn=f.create("div",{"class":"jimu-btn jimu-float-leading jimu-leading-margin2 add-btn",innerHTML:this.nls.dragToAdd},
this.actionBar);b=f.create("div",{"class":"jimu-btn-vacation jimu-float-trailing jimu-trailing-margin2 cancel-btn",innerHTML:this.nls.cancel},this.actionBar);var c=f.create("div",{"class":"jimu-btn jimu-float-trailing save-btn",innerHTML:this.nls.ok},this.actionBar);this.own(p(b,"click",a.hitch(this,this._resetLayoutDefinition)));this.own(p(c,"click",a.hitch(this,this._saveLayoutDefinition)))}},_destroyActionBar:function(){f.destroy(this.actionBar);this.actionBar=null},_createLayout:function(b,c,
d){return this._createLayoutDeferred&&!this._createLayoutDeferred.isResolved()?this._createLayoutDeferred.then(a.hitch(this,function(){return this._doCreateLayout(b,c,d)})):this._doCreateLayout(b,c,d)},_doCreateLayout:function(b,c,d){var e,w=new k;this._createLayoutDeferred=new k;if(this.isEditing)return this._createEditingLayout();window.appInfo.isRunInMobile?e=a.hitch(this,this._createMobileLayout):(this.mobileController&&(this.mobileController.destroyOnScreenWidgets(),this.mobileController.destroy(),
this.mobileController=null),e=a.hitch(this,this._createNormalLayout));d?e().then(a.hitch(this,function(){this._createLayoutDeferred.resolve();w.resolve()})):b?e().then(a.hitch(this,this._loadOnScreenGroups)).then(a.hitch(this,this._reArrangeWidgetsLayout,c)).then(a.hitch(this,function(){this._createLayoutDeferred.resolve();w.resolve()})):e().then(a.hitch(this,this._reArrangeWidgetsLayout,c)).then(a.hitch(this,function(){this._createLayoutDeferred.resolve();w.resolve()}));return w},_detachWidgets:function(b){if("stack"===
b.type){for(;1<b.contentItems.length;)b.removeChild(b.contentItems[0],!0);var c=b.contentItems[0];b.addChild({type:"component",componentName:"widget panel",title:" ",isClosable:!1});b.removeChild(c,!0)}else d.forEach(b.contentItems,a.hitch(this,function(a){this._detachWidgets(a)}))},_setupWidgets:function(b,c){b.isClosable=c;"component"!==b.type&&("stack"===b.type?0===b.content.length&&(b.content=[{type:"component",componentName:"widget panel",title:" ",isClosable:c}]):d.forEach(b.content,a.hitch(this,
function(a){this._setupWidgets(a)})))},_onActivePanelChanged:function(b){var c;if(!this._isDestroying&&"widget panel"===b.componentName&&b.config.id){(c=this.dashboardPanels[b.config.id])&&c.domNode?(0===b.container.getElement().find(".jimu-panel").length&&(b.container.getElement().html(c.domNode),b.container.on("resize",u(a.hitch(this,function(){0<b.container.width&&0<b.container.height&&c&&c.resize()}),200))),c.resize(),this.panelManager.openPanel(c)):this._loadDashboardWidget(b.config.id).then(a.hitch(this,
function(c){c&&(b.container.getElement().html(c.domNode),b.container.on("resize",u(a.hitch(this,function(){0<b.container.width&&0<b.container.height&&c.resize()}),200)),c.resize(),this.panelManager.openPanel(c))}));var e=b.parent.config.id,f;d.some(this.appConfig.widgetOnScreen.groups,a.hitch(this,function(a){if(a.id===e)return f=a.widgets,!0}));d.forEach(f,a.hitch(this,function(a){a.id!==b.config.id&&(c=this.dashboardPanels[a.id])&&this.panelManager.closePanel(c)}))}},_createNormalLayout:function(){var b=
new k;this._isDestroying=!1;this.layoutContainer||(this.layoutContainer=f.create("div",{"class":"config"===this.appConfig.mode?"jimu-dnd-layout config":"jimu-dnd-layout"},this.layoutId),"config"===this.appConfig.mode&&(this.modifyLayoutBtn=f.create("div",{"class":"jimu-dnd-layout modify-btn",innerHTML:'\x3cdiv class\x3d"jimu-ellipsis"\x3e\x3cspan class\x3d"feature-action icon-edit"\x3e\x3c/span\x3e'+this.nls.modifyLayout+"\x3c/div\x3e"},this.layoutId),this.own(p(this.modifyLayoutBtn,"click",a.hitch(this,
function(){l.publish("editLayout")})))));d.some(this.appConfig.widgetOnScreen.widgets,function(a){if("themes/DashboardTheme/widgets/Header/Widget"===a.uri)return a.visible?h.setStyle(this.layoutContainer,"top","80px"):(this._removeHighLight(a.id),h.setStyle(this.layoutContainer,"top",0)),!0},this);var c=this.layout,e=a.clone(this.appConfig.layoutDefinition.layout.config);"config"===this.appConfig.mode&&(e.settings.reorderEnabled=!1,e.settings.resizeEnabled=!1,e.settings.enableHeaderDragging=!1,e.dimensions=
{borderWidth:5,dragProxyWidth:0,dragProxyHeight:0});this._setupWidgets(e.content[0],!1);q(["libs/goldenlayout/goldenlayout"],a.hitch(this,function(f){"config"===this.appConfig.mode&&$(this.modifyLayoutBtn).removeClass("hidden");this.layout=new f(e,this.layoutContainer);this.layout.registerComponent("widget panel",a.hitch(this,function(a,b){var c=a.parent.parent.config.id,e,f;b.widgetId||(f=this._addWidgetTipTemplate,d.some(this.appConfig.widgetOnScreen.groups,function(a){if(a.id===c)return"config"===
this.appConfig.mode&&0===a.widgets.length&&(e=a.placeholderIndex),!0},this),e&&(f=f.replace("${groupIndex}",e),a.getElement().html(f)))}));this.layout.registerComponent("map",a.hitch(this,function(a){this.mapContainer=a.getElement();$("#"+this.mapId).appendTo(this.mapContainer);c&&(this._isDestroying=!0,this._detachWidgets(c.root.contentItems[0]),c.destroy(),this._isDestroying=!1);this.mobilePanel&&(this.mobilePanel.destroy(),this.mobilePanel=null)}));this.layout.on("initialised",a.hitch(this,function(){b.resolve()}));
this.layout.on("stackCreated",a.hitch(this,function(b){b.on("activeContentItemChanged",a.hitch(this,function(a){this._onActivePanelChanged(a)}))}));this.layout.init()}));return b},_createMobileLayout:function(){var b=new k;this.modifyLayoutBtn&&$(this.modifyLayoutBtn).addClass("hidden");if(this.mobilePanel)this.mobilePanel.clearPanels(),b.resolve();else{this.layout&&(this._isDestroying=!0,this._detachWidgets(this.layout.root.contentItems[0]),this._isDestroying=!1);var c=m.getMarginBox(window.jimuConfig.layoutId);
this._loadMobilePanel(this.layoutId,c.w>c.h?2:1).then(a.hitch(this,function(){this.layout&&(this.layout.destroy(),this.layout=null);b.resolve()}))}return b},_createEditingLayout:function(){this.editContainer||(this.editContainer=f.create("div",{"class":"jimu-edit-layout hidden"},this.layoutId),this._createActionBar(this.editContainer),this.editLayoutDiv=f.create("div",{"class":"layout-container"},this.editContainer));var b=this.editingLayout,c=a.clone(this.appConfig.layoutDefinition.layout.config);
c.settings.enableHeaderDropping=!1;c.settings.reorderEnabled=!1;c.dimensions={borderWidth:5,dragProxyWidth:0,dragProxyHeight:0};this._setupWidgets(c.content[0],!0);q(["libs/goldenlayout/goldenlayout"],a.hitch(this,function(d){this.editingLayout=new d(c,this.editLayoutDiv);this.editingLayout.registerComponent("widget panel",a.hitch(this,function(a){a.getElement().html("")}));this.editingLayout.registerComponent("map",a.hitch(this,function(a){a.getElement().html('\x3cdiv class\x3d"maptip"\x3e'+this.nls.mapArea+
"\x3c/div\x3e");b&&b.destroy()}));this._bindLayoutEvents();this.editingLayout.init()}))},_destroyLayout:function(){$("#"+this.mapId).appendTo("#"+this.layoutId);this.layout&&(this.layout.destroy(),this.layout=null,f.destroy(this.layoutContainer),this.layoutContainer=null,this.modifyLayoutBtn&&(f.destroy(this.modifyLayoutBtn),this.modifyLayoutBtn=null));this.editingLayout&&(this._destroyActionBar(),this.editingLayout.destroy(),this.editingLayout=null,f.destroy(this.editContainer),this.editContainer=
null)},destroyOnScreenWidgetsAndGroups:function(){this._destroyOnScreenWidgets();this._destroyOnScreenGroups()},onActionTriggered:function(a){if(!window.appInfo.isRunInMobile)if("editLayout"===a.action)this._enableEditing();else if("highLight"===a.action){var b=this._findContentItemById(a.elementId);b?b.isStack?$(b.element).addClass("highlight"):b.isComponent&&$(b.tab.element).addClass("highlight"):(d.forEach(this.widgetPlaceholders,function(b){b.configId===a.elementId&&this._highLight(b)},this),
d.forEach(this.onScreenWidgetIcons,function(b){b.configId===a.elementId&&this._highLight(b)},this),d.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(b){b.configId===a.elementId&&this._highLight(b)},this))}else"removeHighLight"===a.action?this._removeHighLight(a.elementId):"showLoading"===a.action?(h.setStyle(jimuConfig.loadingId,"display","block"),h.setStyle(jimuConfig.mainPageId,"display","none")):"showApp"===a.action&&(h.setStyle(jimuConfig.loadingId,"display","none"),h.setStyle(jimuConfig.mainPageId,
"display","block"))},_findContentItemById:function(a,c){var b=this.layout.root.contentItems[0].getItemsById(a);return b&&0<b.length&&(!c||c===b[0].type)?b[0]:null},_highLight:function(a){if(a.domNode){this.hlDiv&&this._removeHighLight(a);var b=m.getMarginBox(a.domNode);this.hlDiv=f.create("div",{style:{position:"absolute",left:b.l+"px",top:b.t+"px",width:b.w+"px",height:b.h+"px"},"class":"icon-highlight"},a.domNode,"before")}},_removeHighLight:function(a){/^dd_group_\d+$/.test(a)?(a=this._findContentItemById(a,
"stack"))&&$(a.element).removeClass("highlight"):/^widgets_\w+_\d+$/.test(a)&&(a=this._findContentItemById(a,"component"))&&$(a.tab.element).removeClass("highlight");this.hlDiv&&(f.destroy(this.hlDiv),this.hlDiv=null)},onEnter:function(a,c){this.appConfig=a;this.isEditing=!1;this.createMapDiv(c);this._createLayout(!1,!1,!0)},onLeave:function(){this._destroyLayout();this.map=null},onWidgetChange:function(a,c){this.appConfig=a;"themes/DashboardTheme/widgets/Header/Widget"===c.uri&&(c.visible?h.setStyle(this.layoutContainer,
"top","80px"):(this._removeHighLight(c.id),h.setStyle(this.layoutContainer,"top",0)),this._resizeLayout());c=a.getConfigElementById(c.id);var b=this.dashboardPanels[c.id];b?(b.reloadWidget(c),(b=this.layout.root.contentItems[0].getItemsByType("component"))&&0<b.length&&b.forEach(function(a){a.config.id===c.id&&a.config.title!==c.label&&(a.config.title=c.label,a.setTitle(c.label))})):(this.mobileController&&(this.mobileController.destroy(),this.mobileController=new y({appConfig:this.appConfig,panelContainerNode:this.mobilePanel.widgetContainerNode}),
this.mobileController.placeAt(this.mapId)),this.onOnScreenWidgetChange(a,c))},onOnScreenGroupsChange:function(a){this.appConfig=a;this._createLayout(!0,!1)},onGroupChange:function(a,c){this.appConfig=a;c=a.getConfigElementById(c.id);c.isOnScreen?this._createLayout(!0,!1):(d.forEach(this.widgetManager.getControllerWidgets(),function(b){b.isControlled(c.id)&&this.reloadControllerWidget(a,b.id)},this),d.forEach(this.panelManager.panels,function(a){a.config.id===c.id&&a.updateConfig(c)},this))},_reArrangeWidgetsLayout:function(a){a&&
this._destroyOnScreenWidgets();window.appInfo.isRunInMobile?(a&&this._loadMobileOnScreenWidgets(),this.mobilePanel.setPanels(this.dashboardWidgets,this.dashboardPanels)):(a&&this.loadOnScreenWidgets(this.appConfig),this._reArrangeWidgetsInDesktopLayout())},_reArrangeWidgetsInDesktopLayout:function(){d.forEach(this.appConfig.widgetOnScreen.groups,a.hitch(this,function(b){b=this.appConfig.getConfigElementById(b.id);var c=this._findContentItemById(b.id,"stack");c&&d.forEach(b.widgets,a.hitch(this,function(a,
b){var d={id:a.id,type:"component",title:a.label,componentName:"widget panel",componentState:{widgetId:a.id}};c.contentItems.length>b?(d=c.contentItems[b],d.config.id=a.id,d.config.title=a.label,d.config.componentState={widgetId:a.id},d.setTitle(a.label),c.setActiveContentItem(d)):c.addChild(d)}))}))},_loadMobileOnScreenWidgets:function(){this.mobileController=new y({appConfig:this.appConfig,panelContainerNode:this.mobilePanel.widgetContainerNode});this.mobileController.placeAt(this.mapId);d.forEach(this.appConfig.widgetOnScreen.widgets,
function(a){a.uri&&a.visible&&!a.closeable&&this.loadOnScreenWidget(a,this.appConfig)},this)},_loadMobilePanel:function(b,c){var d=this.appConfig.layoutDefinition.mobileLayout.panel,e=new k;q([d.uri],a.hitch(this,function(d){this.mobilePanel=new d({layoutId:this.layoutId,mapId:this.mapId,mobileLayout:c,config:{},layoutManager:this});this.own(p(this.mobilePanel,"resized",a.hitch(this,function(a){this.mobileController&&this.mobileController.setPanelPosition(a)})));f.place(this.mobilePanel.domNode,b);
e.resolve()}));return e},_loadDashboardWidget:function(b){var c=new k,e=this.dashboardPanels[b];if(e&&e.domNode)return c.resolve(this.dashboardPanels[b]),c;var f;d.some(this.appConfig.widgetOnScreen.groups,a.hitch(this,function(c){return d.some(c.widgets,a.hitch(this,function(a){if(a.id===b)return f=a,!0}))}));if(!f)return c.resolve(null),c;var g=this.appConfig.layoutDefinition.layout.panel;q([g.uri],a.hitch(this,function(d){var e={config:f,uri:g.uri,map:this.map,widgetManager:this.widgetManager,
panelManager:this.panelManager,id:b+"_panel",position:{}},h;a.mixin(e,f.options);try{h=new d(e),this.dashboardPanels[b]=h,c.resolve(h),console.log("panel ["+e.id+"] created.")}catch(z){console.log("create panel error: "+z+", panelId: "+e.id),c.reject(z)}}));return c},onLayoutDefinitionChange:function(a){this.appConfig=a;this._createLayout(!1,!1)},onLayoutChange:function(b){var c=window.appInfo.isRunInMobile,e=!1;this.isEditing||(c!==this._isLastLayoutMobile&&(e=!0,this._isLastLayoutMobile=c),this.appConfig=
b,this._createLayout(!1,e).then(a.hitch(this,function(){d.forEach(this.widgetPlaceholders,function(a){a.moveTo(b.getConfigElementById(a.configId).position)},this);d.forEach(this.onScreenWidgetIcons,function(a){a.moveTo(b.getConfigElementById(a.configId).position)},this);d.forEach(this.widgetManager.getOnScreenOffPanelWidgets(),function(a){if(!a.closeable){var c=b.getConfigElementById(a.id).position;a.setPosition(c)}},this)})))},openWidget:function(a){var b;(a=this._findContentItemById(a,"component"))&&
(b=a.parent)&&b.isStack&&b.setActiveContentItem(a)},_loadOnScreenGroups:function(){var b=this.appConfig.widgetOnScreen.groups,c=[],e=new k;d.forEach(b,a.hitch(this,function(a){a=this.appConfig.getConfigElementById(a.id);d.forEach(a.widgets,function(a){c.push(a.id)})}));d.forEach(this.dashboardWidgets,a.hitch(this,function(a){if(0>c.indexOf(a)){var b=this.dashboardPanels[a];b&&(this.panelManager.closePanel(b),b.destroy());this.dashboardPanels[a]=null}}));this.dashboardWidgets=c;e.resolve();return e},
_destroyOnScreenWidgets:function(){this.destroyOnScreenOffPanelWidgets();this.destroyWidgetPlaceholders();this.destroyOnScreenWidgetIcons();this.mobileController&&(this.mobileController.destroy(),this.mobileController=null)},_destroyOnScreenGroups:function(){d.forEach(this.dashboardWidgets,a.hitch(this,function(a){if(a=this.dashboardPanels[a])this.panelManager.closePanel(a),a.destroy(),a=null}));this.panelManager.destroyAllPanels();this.dashboardWidgets=[];this.dashboardPanels={};this.mobilePanel&&
this.mobilePanel.clearPanels()}});x.getInstance=function(a,c){null===v&&(v=new x(a,c),window._layoutManager=v);return v};return x});