// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/aspect dojo/dom-construct dojo/dom-geometry dojo/dom-class dijit/_WidgetBase dijit/_TemplatedMixin jimu/PanelManager jimu/WidgetManager".split(" "),function(p,d,k,l,h,q,g,m,c,r,t,u,v){return p([r,t],{baseClass:"jimu-dnd-mobile-controller",templateString:'\x3cdiv\x3e\x3cdiv class\x3d"icon-section" data-dojo-attach-point\x3d"iconNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"container-section" data-dojo-attach-point\x3d"containerNode"\x3e\x3c/div\x3e\x3c/div\x3e',
appConfig:null,panelContainerNode:null,openIds:null,toolsCount:0,postCreate:function(){this.inherited(arguments);this.panelManager=u.getInstance();this.widgetManager=v.getInstance();this.openIds=[];this.createWidgetIcons();0===this.toolsCount&&l.setStyle(this.domNode,"display","none");this.own(h(this.iconNode,"click",d.hitch(this,function(a){a.stopPropagation();c.contains(this.containerNode,"in")?(c.remove(this.containerNode,"in"),c.add(this.containerNode,"out")):(c.remove(this.containerNode,"out"),
c.add(this.containerNode,"in"))})));this.own(h(document.body,"click",d.hitch(this,function(a){c.contains(this.containerNode,"in")&&!this.isPartOfPopup(a.target||a.srcElement)&&(c.remove(this.containerNode,"in"),c.add(this.containerNode,"out"))})))},destroyOnScreenWidgets:function(){k.forEach(this.appConfig.widgetOnScreen.widgets,function(a){a.inPanel?this.panelManager.destroyPanel(a.id+"_panel"):this.widgetManager.destroyWidget(a.id)},this)},isPartOfPopup:function(a){var c=this.containerNode;return a===
c||l.isDescendant(a,c)},setConfig:function(a){this.appConfig=a;this.createWidgetIcons()},createWidgetIcons:function(){this.toolsCount=0;g.empty(this.containerNode);this.appConfig&&this.appConfig.widgetOnScreen&&k.forEach(this.appConfig.widgetOnScreen.widgets,function(a){a.uri&&a.closeable&&(this._addItem(a),this.toolsCount++)},this)},_addItem:function(a){var n=d.clone(a),f=g.create("div",{"class":"row"},this.containerNode);g.create("div",{"class":"widget-icon column",style:"background: url("+a.icon+
") no-repeat;"},f);g.create("div",{"class":"widget-label jimu-ellipsis column",title:a.label,innerHTML:a.label},f);this.own(h(f,"click",d.hitch(this,function(e){var b;e.stopPropagation();a.inPanel?(b=m.getMarginBox(this.panelContainerNode),n.panel={uri:"themes/DashboardTheme/panels/OnScreenPanel/Panel",position:{relativeTo:"browser",left:b.l,top:b.t,width:b.w,height:b.h}},this.panelManager.showPanel(n).then(d.hitch(this,function(a){this.activePanel=a;a.setPosition({relativeTo:"browser",left:b.l,top:b.t,
width:b.w,height:b.h});return a})).then(d.hitch(this,function(a){this.panelManager.openPanel(a)}))):(b=m.getMarginBox(f),this._toggleOffPanelWidget(a,b.l+b.w,b.t));c.remove(this.containerNode,"in");c.add(this.containerNode,"out")})))},_toggleOffPanelWidget:function(a,c,f){var e=this.openIds.indexOf(a.id);0<=e?(this.widgetManager.closeWidget(a.id),this.openIds.splice(e,1)):this.widgetManager.loadWidget(a).then(d.hitch(this,function(b){this.openIds.push(a.id);b.setPosition({left:c,top:f,zIndex:100,
relativeTo:"map"});this.widgetManager.openWidget(b);this.own(q.after(b,"onClose",d.hitch(this,function(){e=this.openIds.indexOf(a.id);0<=e&&this.openIds.splice(e,1)})))}))},setPanelPosition:function(a){this.activePanel&&(a.relativeTo="layout",this.activePanel.setPosition(a))}})});