// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:jimu/dijit/_filter/ListValueProvider.html":'\x3cdiv\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"valuesSelect" data-dojo-type\x3d"dijit/form/FilteringSelect" data-dojo-props\x3d\'searchAttr:"label",required:false,intermediateChanges:true\' style\x3d"width:100%;" data-dojo-attach-event\x3d"input:_onFilteringSelectInput"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/aspect dojo/Deferred dojo/_base/lang dojo/_base/html dojo/_base/array dojo/_base/declare ./ValueProvider dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./ListValueProvider.html dojo/store/Memory jimu/utils dijit/form/FilteringSelect".split(" "),function(l,h,e,f,g,m,n,p,q,r,t,u){return m([n,p,q],{templateString:r,codedValues:null,staticValues:null,showNullValues:!1,postCreate:function(){this.inherited(arguments);f.addClass(this.domNode,"jimu-filter-list-value-provider");
this._uniqueValueCache={};var a=new t({idProperty:"id",data:[]});this.valuesSelect.set("store",a);this.staticValues||"function"!==typeof this.valuesSelect._onDropDownMouseDown||(!this.codedValues||this.codedValues&&this.filterCodedValue)&&this.own(l.before(this.valuesSelect,"_onDropDownMouseDown",e.hitch(this,this._onBeforeDropDownMouseDown)))},_onFilteringSelectInput:function(){this.emit("change")},_onBeforeDropDownMouseDown:function(){this._tryUpdatingUniqueValues(void 0,!0);return arguments},getDijits:function(){return[this.valuesSelect]},
setValueObject:function(a){return this.staticValues?this._setValueForStaticValues(a.value,this.staticValues):this.codedValues?this.filterCodedValue?this._tryUpdatingUniqueValues(a.value,!1):this._setValueForStaticValues(a.value,this.codedValues):this._tryUpdatingUniqueValues(a.value,!1)},getValueObject:function(){if(this.isValidValue()){var a=this.valuesSelect.get("item").value;return{isValid:!0,type:this.partObj.valueObj.type,value:a}}return null},tryGetValueObject:function(){return this.isValidValue()?
this.getValueObject():this.isEmptyValue()?{isValid:!0,type:this.partObj.valueObj.type,value:"string"===this.shortType?"":null}:null},setRequired:function(a){this.valuesSelect.set("required",a)},_setValueForStaticValues:function(a,c){var b=null,d=-1,b=null;c&&(b=g.map(c,e.hitch(this,function(b,c){var k={id:c,value:b.value,label:b.label};k.value===a&&(d=c);return k})),this.valuesSelect.store.setData(b),0<=d&&(b=this.valuesSelect.store.get(d))&&this.valuesSelect.set("item",b))},_uniqueValueLoadingDef:null,
_uniqueValueLoadingExpr:"",_uniqueValueCache:null,_tryUpdatingUniqueValues:function(a,c){var b=new h;if(this.valuesSelect._opened)b.resolve();else{var d=this.getDropdownFilterExpr();d!==this._uniqueValueLoadingExpr?(this.valuesSelect.readOnly=!0,this._uniqueValueLoadingDef&&(this._uniqueValueLoadingDef.reject(),this._uniqueValueLoadingDef=null),this._uniqueValueLoadingExpr=d,this._uniqueValueLoadingDef=this._getUniqueValues(d),this._uniqueValueLoadingDef.then(e.hitch(this,function(d){this.domNode&&
(this._uniqueValueLoadingDef=null,this.valuesSelect.readOnly=!1,this._setValueForUniqueValues(a,d),this._hideLoadingIcon(),c&&this.valuesSelect.toggleDropDown(),b.resolve())}),e.hitch(this,function(a){console.error(a);this.domNode&&(this._uniqueValueLoadingDef=null,this.valuesSelect.readOnly=!1,this._hideLoadingIcon(),b.reject(a))}))):b.resolve()}return b},_setValueForUniqueValues:function(a,c){c.sort(function(a,b){return a.value<b.value?-1:a.value===b.value?0:1});this.showNullValues||(c=g.filter(c,
e.hitch(this,function(a){return"\x3cNull\x3e"!==a.value&&null!==a.value})));if(void 0===a){var b=this.getValueObject();b&&(a=b.value)}var d=-1,b=null,f=g.map(c,e.hitch(this,function(b,c){var e={id:c,value:b.value,label:b.label};b.value===a&&(d=c);return e}));this.valuesSelect.store.setData(f);0<=d&&(b=this.valuesSelect.store.get(d));this.valuesSelect.set("item",b)},_showLoadingIcon:function(){f.addClass(this.valuesSelect.domNode,"loading")},_hideLoadingIcon:function(){f.removeClass(this.valuesSelect.domNode,
"loading")},_getUniqueValues:function(a){var c=new h;this._uniqueValueCache[a]?c.resolve(this._uniqueValueCache[a]):(this._showLoadingIcon(),u.getUniqueValues(this.url,this.fieldName,a,this.layerDefinition,this.fieldPopupInfo).then(e.hitch(this,function(b){this.domNode&&(this._uniqueValueCache[a]=b,c.resolve(b),this._hideLoadingIcon())}),e.hitch(this,function(a){this.domNode&&(c.reject(a),this._hideLoadingIcon())})));return c}})});