// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/Evented dojo/_base/lang dojo/_base/html dojo/_base/array dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin jimu/utils esri/lang".split(" "),function(f,g,c,h,d,k,l,m,e,n){return k([l,m,g],{baseClass:"jimu-filter-value-provider",fieldName:null,shortType:null,_enabled:!1,cascade:"none",filterCodedValue:!1,fieldPopupInfo:null,nls:null,url:null,layerDefinition:null,fieldInfo:null,partObj:null,runtime:!0,staticValues:null,codedValues:null,layerInfo:null,popupInfo:null,operatorInfo:null,
filterCodedValueIfPossible:!1,postMixInProperties:function(){this.inherited(arguments);this.shortType=this.partObj.fieldObj.shortType;this.fieldName=this.partObj.fieldObj.name;this.cascade=this.partObj.interactiveObj&&this.partObj.interactiveObj.cascade;this.runtime&&this.codedValues&&this.filterCodedValueIfPossible&&e.isCodedValuesSupportFilter(this.layerDefinition,this.codedValues.length)?this.filterCodedValue=!0:this.filterCodedValue=!1;this.popupInfo&&this.popupInfo.fieldInfos&&0<this.popupInfo.fieldInfos.length&&
d.some(this.popupInfo.fieldInfos,c.hitch(this,function(a){return a.fieldName===this.fieldName?(this.fieldPopupInfo=a,!0):!1}))},getDijits:function(){return[]},bindChangeEvents:function(){var a=this.getDijits();d.forEach(a,c.hitch(this,function(a){a.declaredClass&&0===a.declaredClass.indexOf("dijit.")&&h.addClass(a.domNode,a.declaredClass.replace(/\./g,"-"));this.own(f(a,"change",c.hitch(this,this._onChanged)))}))},_onChanged:function(){this.emit("change")},tryLocaleNumber:function(a){var b=e.localizeNumber(a);
if(null===b||void 0===b)b=a;return b},getPartObject:function(){var a=this.getValueObject();if(!a)return null;var b=c.clone(this.partObj);b.valueObj=a;return b},setValueObject:function(){},getValueObject:function(){},tryGetValueObject:function(){return this.getValueObject()},setRequired:function(){},getStatus:function(){var a=1,b=this.getDijits();0<b.length&&(a=d.map(b,c.hitch(this,function(a){return this.getStatusForDijit(a)})),a=Math.min.apply(a,a));return a},getStatusForDijit:function(a){return a.validate()?
a.get("DisplayedValue")?1:0:-1},isInvalidValue:function(){return 0>this.getStatus()},isEmptyValue:function(){return 0===this.getStatus()},isValidValue:function(){return 0<this.getStatus()},isBlankValueProvider:function(){return!1},getFilterExpr:function(){var a="1\x3d1",a=this.getLayerFilterExpr();if("all"===this.cascade||"previous"===this.cascade)var b=this.getCascadeFilterExpr(),a="("+a+") AND ("+b+")";return a},getLayerFilterExpr:function(){var a="1\x3d1";this.layerInfo&&(a=this.layerInfo.getFilter());
a||(a="1\x3d1");return a},_getWebMapFilterExpr:function(){var a="";this.runtime?(this.layerInfo&&(a=this.layerInfo.getFilterOfWebmap()),a||(a="1\x3d1")):a="1\x3d1";return a},getDropdownFilterExpr:function(){var a="1\x3d1",a=this._getWebMapFilterExpr();if("all"===this.cascade||"previous"===this.cascade)var b=this.getCascadeFilterExpr(),a="("+a+") AND ("+b+")";return a},getCascadeFilterExpr:function(){return"1\x3d1"},isDefined:function(a){return n.isDefined(a)},disable:function(){this._enabled=!1},
enable:function(){this._enabled=!0},isEnabled:function(){return this._enabled}})});