// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/string dojo/number esri/request esri/layers/RasterFunction ./rasterFunctions".split(" "),function(v,m,k,p,w,r,t,x){var y=function(a,c){var b;if(!a||!c)return!1;b=a.length;if(b!==c.length)return!1;for(var d=0;d<b;d++)if(a[d]instanceof Array&&c[d]instanceof Array){if(!a[d].compare(c[d]))return!1}else if(a[d]!==c[d])return!1;return!0},z=function(a){try{if(a.attributes&&"ForestFragmentation_US_USFS_2002"===a.attributes.Name&&"Forest Fragmentation"===
a.attributes.Title&&49===a.attributes.OBJECTID)return null}catch(h){}a=a.attributes;var c,b,d,f,e,g;a&&(g={id:a.OBJECTID,name:a.Name,title:a.Title,url:a.Url,metadata:a.Metadata},a.InputRanges&&a.InputRanges.split&&"undefined"!==typeof a.OutputValues&&a.OutputValues.split&&(c=k.map(a.InputRanges.split(","),function(a){return parseFloat(a.trim())}),b=k.map(a.OutputValues.split(","),function(a){return parseInt(a.trim(),10)}),a.RangeLabels&&a.RangeLabels.split&&(f=k.map(a.RangeLabels.split(","),function(a){return a.trim()}))),
a.NoDataRanges&&a.NoDataRanges.split&&(d=k.map(a.NoDataRanges.split(","),function(a){return parseFloat(a.trim())}),a.NoDataRangeLabels&&a.NoDataRangeLabels.split&&(e=k.map(a.NoDataRangeLabels.split(","),function(a){return a.trim()}))),g.remapRanges=n.createRemapRanges(c,b,d,{labels:f,noDataLabels:e}));return g},u=function(a){return k.map(a.colors,function(a){return[a.value].concat(a.rgb)})},q=function(a,c){var b=[],d=0;a&&a.overlayLayers&&a.overlayLayers.push?0<a.overlayLayers.length?(k.forEach(a.overlayLayers,
function(a,e){d+=a.weight;a.remapRanges&&a.remapRanges.push&&0<a.remapRanges.length?k.forEach(a.remapRanges,function(a,d){(isNaN(a.outputValue)||null===a.outputValue)&&b.push(p.substitute(c.wro.validation.overlayLayerOutputInvalid,[e,d]));(isNaN(a.inputMin)||null===a.inputMin||isNaN(a.inputMax)||null===a.inputMax||a.inputMin>a.inputMax)&&b.push(p.substitute(c.wro.validation.overlayLayerInputInvalid,[e,d]))}):b.push(p.substitute(c.wro.validation.overlayLayerRangesMissing,[e]))}),100!==d&&b.push(c.wro.validation.overlayLayerWeight)):
b.push(c.wro.validation.overlayLayerRequired):b.push(c.wro.validation.overlayLayerNotDefined);return b},A=function(a,c,b){a+="/computeHistograms";var d={geometryType:"esriGeometryPolygon",f:"json"};d.geometry=window.JSON.stringify(c);b&&(b.renderingRule&&(d.renderingRule=window.JSON.stringify(b.renderingRule)),b.pixelSize&&(d.pixelSize=window.JSON.stringify(b.pixelSize)));return r({url:a,content:d,handleAs:"json",callbackParamName:"callback"})},n={rasterFunctionArgumentsToRemapRanges:function(a,c){var b,
d,f,e,g;a&&(d=m.mixin({inputRangesArgumentName:"InputRanges",outputValuesArgumentName:"OutputValues",noDataRangesArgumentName:"NoDataRanges",labelsArgumentName:"Labels",noDataLabelsArgumentName:"NoDataLabels"},c),b=a[d.inputRangesArgumentName],f=a[d.outputValuesArgumentName],e=a[d.noDataRangesArgumentName],g=a[d.labelsArgumentName],d=a[d.noDataLabelsArgumentName],b=this.createRemapRanges(b,f,e,{labels:g,noDataLabels:d,sortBy:"inputMin"}));return b},createRemapRanges:function(a,c,b,d){var f=[],e=!1,
g,h,l;d&&(g=d.labels,h=d.noDataLabels,l=d.sortBy);a&&a.push&&c&&c.push&&a.length===2*c.length&&(e=g&&g.push&&g.length===c.length,k.forEach(c,function(b,d){var c=2*d,c={inputMin:a[c],inputMax:a[c+1],outputValue:b,originalOutputValue:b};c.label=e?g[d]:this.getRangeString(c.inputMin,c.inputMax);f.push(c)},this));b&&b.push&&0<b.length&&(e=h&&h.push&&h.length===b.length/2,k.forEach(b,function(a,d){if(0===d%2){var c={inputMin:a,inputMax:b[d+1],outputValue:0,originalOutputValue:0};c.label=e?h[d]:this.getRangeString(c.inputMin,
c.inputMax);f.push(c)}},this));if(0<f.length)return l&&f.sort(function(a,b){return a[l]<b[l]?-1:a[l]>b[l]?1:0}),f},getRangeString:function(a,c){return a===c?a+"":a+" - "+c},remapRangesToRasterFunctionArguments:function(a,c){var b,d,f,e,g,h,l;a&&(b={},d=m.mixin({includeLabels:!0,inputRangesArgumentName:"InputRanges",outputValuesArgumentName:"OutputValues",noDataRangesArgumentName:"NoDataRanges",labelsArgumentName:"Labels",noDataLabelsArgumentName:"NoDataLabels"},c),f=[],e=[],g=[],h=[],l=[],k.forEach(a,
function(a){var b=a.label||this.getRangeString(a.inputMin,a.inputMax);a.outputValue?(f.push(a.inputMin),f.push(a.inputMax),e.push(a.outputValue),h.push(b)):(g.push(a.inputMin),g.push(a.inputMax),l.push(b))},this),0<e.length&&(b[d.inputRangesArgumentName]=f,b[d.outputValuesArgumentName]=e,d.includeLabels&&(b[d.labelsArgumentName]=h)),0<g.length&&(b[d.noDataRangesArgumentName]=g,d.includeLabels&&(b[d.noDataLabelsArgumentName]=l)));return b},getRemapRangeByValue:function(a,c){var b;(c||0===c)&&k.some(a,
function(a){return c===a.inputMin&&c===a.inputMax||c>=a.inputMin&&c<a.inputMax?(b=a,!0):!1});return b},findRemapRange:function(a,c){var b,d;if(a&&c)return k.some(a,function(a){if((c.inputMin||0===c.inputMin)&&(c.inputMax||0===c.inputMax))return(b=a.inputMin===c.inputMin&&a.inputMax===c.inputMax)&&(d=a),b}),d}};return v([],{context:null,i18n:null,constructor:function(a,c){var b=c||{};this.imageServiceLayer=a;this.rasterFunctionName=b.rasterFunctionName||"";this.histogramRasterFunctionName=b.histogramRasterFunctionName||
"";this.rastersInFunction=b.rastersInFunction||0;this.variableName=b.variableName||"Raster";this.colorMapArgName=b.colorMapArgName||"Colormap";this.dummyRasterId=b.dummyRasterId||1;this.colormapDefinitions=b.colormapDefinitions||[];this.argumentNamePrefixes=m.mixin({id:"Raster",weight:"Weight_Raster",inputRanges:"InputRanges_Raster",outputValues:"OutputValues_Raster",noDataRanges:"NoDataRanges_Raster",labels:"Labels_Raster",noDataLabels:"NoDataLabels"},b.argumentNamePrefixes);this.queryParameters=
m.mixin({where:"1\x3d1",outFields:["*"],returnGeometry:!1},b.queryParameters);this.rasterLayers=b.rasterLayers||[]},initRasterLayers:function(a){var c=this;return this.queryRasters().then(function(b){return c._initRasterLayers(b.features,a)})},queryRasters:function(a){var c=this.imageServiceLayer.url+"/query";a=m.mixin(m.mixin({f:"json"},a),this.queryParameters);a.outFields&&a.outFields.join&&(a.outFields=a.outFields.join(","));return r({url:c,content:a,handleAs:"json",callbackParamName:"callback"})},
_initRasterLayers:function(a,c){var b=this.context;try{this.dummyRasterId=1,this.imageServiceLayer&&this.imageServiceLayer.url&&-1!==this.imageServiceLayer.url.indexOf("//landscape3.arcgis.com")&&(this.dummyRasterId=53)}catch(g){}var d=this,f,e=(c||{}).featureCompareFunc||function(a,b){return a.attributes.Title<b.attributes.Title?-1:a.attributes.Title>b.attributes.Title?1:0};a&&a.length&&0<a.length&&a[0].attributes&&(d.rasterLayers&&d.rasterLayers.push?d.rasterLayers.length=0:d.rasterLayers=[],e&&
a.sort(e),k.forEach(a,function(a){if(f=z(a))f.url=b.checkMixedContent(f.url),d.rasterLayers.push(f)}));return d.rasterLayers},createNewModel:function(){var a={overlayLayers:[]};this.colormapDefinitions&&this.colormapDefinitions instanceof Array&&0<this.colormapDefinitions.length&&(a.colormapDefinition=this.colormapDefinitions[0]);return a},getRasterLayer:function(a){var c;k.some(this.rasterLayers,function(b){if(b.id===a)return c=b,!1});return c},setOverlayLayerDefaults:function(a,c){c&&(c.remapRanges&&
a.remapRanges&&k.forEach(c.remapRanges,function(b){var d;b.label&&(d=n.findRemapRange(a.remapRanges,{inputMin:b.inputMin,inputMax:b.inputMax}))&&(d.label=b.label)},this),a.title=c.title)},operationalLayersToModel:function(a){var c,b=this.rasterFunctionName;b&&k.some(a,function(a){return a.renderingRule&&a.renderingRule&&a.renderingRule.rasterFunction===b?(c=a,!0):!1},this);return this.imageServiceLayerToModel(c)},imageServiceLayerToModel:function(a){var c=this,b,d,f,e,g;e=a.renderingRule;if(a&&e){b=
{overlayLayers:[]};if(this.rasterFunctionName===e.rasterFunction){f=new RegExp("^"+this.argumentNamePrefixes.id+"[1-9]+$");e=e.rasterFunctionArguments;a.remapRangeLabels&&m.mixin(e,a.remapRangeLabels);a.noDataRangeLabels&&m.mixin(e,a.noDataRangeLabels);for(var h in e)h.match(f)?(g=h.replace(this.argumentNamePrefixes.id,""),d={id:parseInt(e[h].replace("$",""),10)},a=this.argumentNamePrefixes.weight+g,d.weight=e[a],d.weight&&0<d.weight&&(d.weight*=100,d=m.mixin(this.getRasterLayer(d.id)||{},d),d.remapRanges=
n.rasterFunctionArgumentsToRemapRanges(e,{inputRangesArgumentName:this.argumentNamePrefixes.inputRanges+g,outputValuesArgumentName:this.argumentNamePrefixes.outputValues+g,noDataRangesArgumentName:this.argumentNamePrefixes.noDataRanges+g,labelsArgumentName:this.argumentNamePrefixes.labels+g,noDataLabelsArgumentName:this.argumentNamePrefixes.noDataLabels+g}),b.overlayLayers.push(d))):h===this.colorMapArgName&&(b.colormapDefinition=this.findColormapDefinition(e[h]))}else f=e,e=f.rasterFunctionArguments,
"Colormap"===f.rasterFunction&&(b.colormapDefinition=this.findColormapDefinition(e.Colormap),f=e.Raster,e=f.rasterFunctionArguments),"Local"===f.rasterFunction&&49===e.Operation?(f=e.Rasters[0],e=f.rasterFunctionArguments):"Local"===f.rasterFunction&&48===e.Operation&&(e.Operation=49,f=e.Rasters[0],e=f.rasterFunctionArguments),"Local"===f.rasterFunction&&55===e.Operation&&(b.overlayLayers=k.map(e.Rasters,function(a){var b={};k.forEach(a.rasterFunctionArguments.Rasters,function(a){isNaN(a)?(b.id=parseInt(a.rasterFunctionArguments.Raster.substr(1),
10),b=m.mixin(c.getRasterLayer(b.id)||{},b),b.remapRanges=n.rasterFunctionArgumentsToRemapRanges(a.rasterFunctionArguments)):b.weight=100*a});return b}));return b}},findColormapDefinition:function(a){var c;k.some(this.colormapDefinitions,function(b){var d=!1;return(d=k.every(b.colors,function(b,c){return y([b.value].concat(b.rgb),a[c])}))?(c=b,!0):!1});return c},modelToOperationalLayers:function(a,c){return[this.modelToImageServiceLayer(a,c)]},modelToImageServiceLayer:function(a,c){var b={id:this.imageServiceLayer.id,
url:this.imageServiceLayer.url,opacity:this.imageServiceLayer.opacity,title:"Weighted Overlay Model"},d=this.getRasterFunction(a.overlayLayers,a.colormapDefinition,{includeLabels:!0}),f={},e={},g;for(g in d.arguments)0===g.indexOf(this.argumentNamePrefixes.labels)?(f[g]=d.arguments[g],delete d.arguments[g]):0===g.indexOf(this.argumentNamePrefixes.noDataLabels)&&(e[g]=d.arguments[g],delete d.arguments[g]);b.renderingRule=d.toJson();b.remapRangeLabels=f;b.noDataRangeLabels=e;c&&c.modelTitle&&(b.title=
c.modelTitle);return b},getRasterFunction:function(a,c,b){var d=[];k.forEach(a,function(a){0<a.weight&&d.push(a)});if(10.3<=this.imageServiceLayer.version){var f=k.map(d,function(a){var b=n.remapRangesToRasterFunctionArguments(a.remapRanges);b.Raster="$"+a.id;b.weight=a.weight/100;return b}),e;c&&(e=u(c));c=x.createWeightedSumParams(f,e);return new t(c)}e=new t;a=d.length;var g={};b=m.mixin({rasterFunctionName:this.rasterFunctionName,rastersInFunction:this.rastersInFunction,argumentNamePrefixes:this.argumentNamePrefixes,
variableName:this.variableName,dummyRasterId:this.dummyRasterId,includeLabels:!1},b);var h;e.functionName=b.rasterFunctionName;b.variableName&&(e.variableName=b.variableName);for(var l=1;l<=b.rastersInFunction;l++)h=l<=a?d[l-1]:{id:b.dummyRasterId,weight:0},g[b.argumentNamePrefixes.id+l]="$"+h.id,g[b.argumentNamePrefixes.weight+l]=w.round(h.weight/100,2),0<h.weight&&h.remapRanges&&(h=n.remapRangesToRasterFunctionArguments(h.remapRanges,{includeLabels:b.includeLabels,inputRangesArgumentName:b.argumentNamePrefixes.inputRanges+
l,outputValuesArgumentName:b.argumentNamePrefixes.outputValues+l,noDataRangesArgumentName:b.argumentNamePrefixes.noDataRanges+l,labelsArgumentName:b.argumentNamePrefixes.labels+l,noDataLabelsArgumentName:b.argumentNamePrefixes.noDataLabels+l}),m.mixin(g,h));if(this.colorMapArgName){c&&(f=u(c));if(!f)throw this.i18n.wro.validation.requiresColormap;g[this.colorMapArgName]=f}e.arguments=g;return e},validateModel:function(a){a=q(a,this.i18n);return{isValid:1>a.length,modelErrors:a}},runModel:function(a){var c;
if(this.imageServiceLayer)if(c=q(a,this.i18n),1>c.length)this.imageServiceLayer.setRenderingRule(this.getRasterFunction(a.overlayLayers,a.colormapDefinition));else throw this.context.showMessages(this.i18n.wro.validation.createModelError,"",c),this.wro.validation.invalidModel+":\n\n"+c.join("\n");else throw this.i18n.wro.validation.imageServiceNotDefined;},clearModel:function(){this.imageServiceLayer&&null!==this.imageServiceLayer.renderingRule&&this.imageServiceLayer.setRenderingRule(null)},getHistogram:function(a,
c,b){var d=m.mixin({},b);if(this.histogramRasterFunctionName){if(this.imageServiceLayer){b=q(a,this.i18n);if(1>b.length)return d.renderingRule=this.getRasterFunction(a.overlayLayers,a.colormapDefinition,{rasterFunctionName:this.histogramRasterFunctionName}).toJson(),A(this.imageServiceLayer.url,c,d).then(function(a){return a.histograms[0]});throw this.i18n.wro.validation.invalidModel+":\n\n"+b.join("\n");}throw this.i18n.wro.validation.imageLayerNotDefined;}throw this.i18n.wro.validation.histogramNotDefined;
},getModelPixelSize:function(a,c){var b=this.imageServiceLayer,d=m.mixin({width:b.maxImageWidth,height:b.maxImageHeight},c),f=Math.max(b.pixelSizeX,Math.ceil(a.getWidth()/d.width)),b=Math.max(b.pixelSizeY,Math.ceil(a.getHeight()/d.height));d.forceSquare?(d={x:Math.max(f,b)},d.y=d.x):d={x:f,y:b};return d},getColormapDefinition:function(a){var c;k.some(this.colormapDefinitions,function(b){if(b.id===a)return c=b,!1});return c}})});