// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Asetukset",titleSettings:"Tekstiasetukset",imageSettings:"Kuvan asetukset",backgroundColor:"Taustav\u00e4ri",alignment:"Kohdistus",textSize:"Tekstin koko",textColor:"Tekstin v\u00e4ri",dataSource:"Aineistol\u00e4hde",chartSettings:"Kaavion asetukset",data:"Aineisto",dataLabels:"Aineiston tunnustekstit",displayMode:"N\u00e4ytt\u00f6tila",featureOption:"N\u00e4yt\u00e4 arvot kohteittain",categoryOption:"N\u00e4yt\u00e4 arvot luokittain",countOption:"N\u00e4yt\u00e4 kohdem\u00e4\u00e4r\u00e4t luokittain",
fieldOption:"N\u00e4yt\u00e4 ominaisuustietoarvot kaavioina",categoryField:"Luokkakentt\u00e4",labelField:"Tunnustekstikentt\u00e4",valueFields:"Arvokent\u00e4t",operation:"Toiminto",sumOption:"Summa",averageOption:"Keskiarvo",minOption:"Minimi",maxOption:"Maksimi",dataFormat:"Aineistomuoto",decimalPlaces:"Desimaalit",prefix:"Etuliite",suffix:"J\u00e4lkiliite",dataType:"Aineistotyyppi",featureCount:"Kohteiden m\u00e4\u00e4r\u00e4",fieldStatistics:"Kent\u00e4n tilastotiedot",display:"N\u00e4yt\u00e4",
chartColor:"Kaavion v\u00e4ri",horizontalAxis:"Vaaka-akseli",verticalAxis:"Pystyakseli",legend:"Selite",position:"Sijainti",top:"Yl\u00e4osa",bottom:"Alaosa",useDataSourceSelection:"K\u00e4yt\u00e4 valintaa",dataSourceFilterByExtent:"Suodata laajuuden mukaan",changeTemplate:"Vaihda mallia",numberSettings:"Numeroasetukset",gaugeSettings:"Mittarin asetukset",indicators:"Ilmaisimet",ifValue:"Jos arvo",and:"ja",numberOperatorIsLessThan:"on v\u00e4hemm\u00e4n kuin",numberOperatorIsGreaterThan:"on suurempi kuin",
numberOperatorIsBetween:"on v\u00e4lill\u00e4",numberOperatorIsEqual:"yht\u00e4 suuri kuin",numberOperatorIsNotEqual:"on erisuuri kuin",then:"Sitten",ratio:"Suhde",trueValue:"Tosi-arvo",changeValueColor:"muuta arvon v\u00e4riksi",changeGaugeColor:"muuta mittarin v\u00e4riksi",setIndicatorIcon:"m\u00e4\u00e4rit\u00e4 ilmaisinkuvakkeeksi",icons:"Icons",style:"Tyyli",placement:"Sijoittaminen",left:"Vasen",replace:"Korvaa",right:"Oikea",color:"V\u00e4ri",sortBy:"Lajitteluperuste",labelAxis:"Tunnusteksti",
valueAxis:"Arvo",minPeriod:"V\u00e4himm\u00e4isaikav\u00e4li",automatic:"Automaattinen",periodsWithOutRecords:"Aikav\u00e4lit ilman tietueita",nullValue:"Nolla-arvo",calculatedAsZero:"Lasketaan nollana",ignored:"Ohitettu",maxCategories:"Enimm\u00e4isluokat",useLayerSymbology:"K\u00e4yt\u00e4 karttatason symboleja",dataRange:"Aineistoalue",targetValue:"Kohdearvo",currentValue:"Nykyinen arvo",gaugeColor:"Mittarin arvo",min:"Minimi",max:"Maksimi",displayValueIn:"N\u00e4yt\u00e4 arvo kohteessa",noData:"Ei tietoja",
thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Varoitus",noSettingWaring1:"Voit m\u00e4\u00e4ritt\u00e4\u00e4 elementin ominaisuudet napsauttamalla sit\u00e4.",noSettingWaring2:"Muuta elementin kokoa tai j\u00e4rjest\u00e4 elementit uudelleen vet\u00e4m\u00e4ll\u00e4.",donNotShowAgain:"\u00c4l\u00e4 n\u00e4yt\u00e4 uudelleen",changeTemplateWarning:"T\u00e4m\u00e4 poistaa kaikki asetuksesi ja avaa uuden tyhj\u00e4n mallin.",requiredFieldWarning:"Arvo on pakollinen:",
dataSourceNotSet:"M\u00e4\u00e4rit\u00e4 aineistol\u00e4hde.",addIndicatorTip:"Lis\u00e4\u00e4 ilmaisin",chooseTemplatePopupTitle:"Valitse malli",stringsInTemplate:{name_number:"Numero",name_gauge:"Mittari",name_vertical_gauge:"Pystysuuntainen mittari",name_horizontal_gauge:"Vaakasuuntainen mittari",name_pie_chart:"Ympyr\u00e4kaavio",name_column_chart:"Pylv\u00e4skaavio",name_bar_chart:"Palkkikaavio",name_line_chart:"Viivakaavio",titleOfTheInfographic:"INFOGRAFIIKAN OTSIKKO",description:"Kuvaus: lis\u00e4tietoja t\u00e4st\u00e4 infografiikasta."},
_localized:{}}});