// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Parametrai",titleSettings:"Teksto parametrai",imageSettings:"Atvaizdo parametrai",backgroundColor:"Fono spalva",alignment:"Lygiuot\u0117",textSize:"Teksto dydis",textColor:"Teksto spalva",dataSource:"Duomen\u0173 \u0161altinis",chartSettings:"Diagramos nustatymai",data:"Duomenys",dataLabels:"Duomen\u0173 \u017eym\u0117s",displayMode:"Rodymo re\u017eimas",featureOption:"Rodyti reik\u0161mes po vien\u0105 element\u0105",categoryOption:"Rodyti reik\u0161mes pagal kategorij\u0105",
countOption:"Rodyti element\u0173 skai\u010di\u0173 kiekvienoje kategorijoje",fieldOption:"Rodyti atributo reik\u0161mes kaip diagramas",categoryField:"Kategorijos laukas",labelField:"\u017dym\u0117s laukas",valueFields:"Reik\u0161m\u0117s laukai",operation:"Veiksmas",sumOption:"Suma",averageOption:"Vidurkis",minOption:"Minimumas",maxOption:"Maksimumas",dataFormat:"Datos formatas",decimalPlaces:"De\u0161imtain\u0117s dalys",prefix:"Prefiksas",suffix:"Sufiksas",dataType:"Duomen\u0173 tipas",featureCount:"Element\u0173 skai\u010dius",
fieldStatistics:"Lauk\u0173 statistika",display:"Rodyti",chartColor:"Diagramos spalva",horizontalAxis:"Horizontali a\u0161is",verticalAxis:"Vertikali a\u0161is",legend:"Legenda",position:"Pad\u0117tis",top:"Vir\u0161us",bottom:"Apa\u010dia",useDataSourceSelection:"Naudoti pasirinkim\u0105",dataSourceFilterByExtent:"Filtruoti pagal apr\u0117pt\u012f",changeTemplate:"Keisti \u0161ablon\u0105",numberSettings:"Skai\u010diaus parametrai",gaugeSettings:"Matuoklio parametrai",indicators:"Indikatoriai",ifValue:"Jei reik\u0161m\u0117",
and:"ir",numberOperatorIsLessThan:"yra ma\u017eiau nei",numberOperatorIsGreaterThan:"yra daugiau nei",numberOperatorIsBetween:"yra tarp",numberOperatorIsEqual:"lygu",numberOperatorIsNotEqual:"nelygu",then:"Tada",ratio:"Santykis",trueValue:"Tikra reik\u0161m\u0117",changeValueColor:"keisti reik\u0161m\u0117s spalv\u0105 \u012f",changeGaugeColor:"keisti matuoklio spalv\u0105 \u012f",setIndicatorIcon:"nustatyti indikatoriaus piktogram\u0105 kaip",icons:"Piktogramos",style:"Stilius",placement:"Vieta",
left:"Kair\u0117je",replace:"Pakeisti",right:"De\u0161in\u0117je",color:"Spalva",sortBy:"R\u016b\u0161iuoti pagal",labelAxis:"U\u017era\u0161as",valueAxis:"Reik\u0161m\u0117",minPeriod:"Min. laikotarpis",automatic:"Automatinis",periodsWithOutRecords:"Laikotarpiai be \u012fra\u0161\u0173",nullValue:"Nulin\u0117 reik\u0161m\u0117",calculatedAsZero:"Apskai\u010diuota kaip nulis",ignored:"Ignoruojama",maxCategories:"Maks. kategorijos",useLayerSymbology:"Naudoti sluoksnio simbolius",dataRange:"Datos intervalas",
targetValue:"Paskirties vietos reik\u0161m\u0117",currentValue:"Dabartin\u0117 reik\u0161m\u0117:",gaugeColor:"Matuoklio spalva",min:"Minimumas",max:"Maksimumas",displayValueIn:"Rodyti reik\u0161m\u0119",noData:"N\u0117ra duomen\u0173",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"\u012esp\u0117jimas",noSettingWaring1:"Paspauskite element\u0105, kad nustatytum\u0117te jo savybes.",noSettingWaring2:"Nuvilkti norint pakeisti elemento dyd\u012f arba j\u012f pertvarkyti.",
donNotShowAgain:"Daugiau nerodyti",changeTemplateWarning:"Tai i\u0161trins visus j\u016bs\u0173 parametrus ir atidarys nauj\u0105 tu\u0161\u010di\u0105 \u0161ablon\u0105.",requiredFieldWarning:"\u0160i reik\u0161m\u0117 privaloma:",dataSourceNotSet:"Nustatykite duomen\u0173 \u0161altin\u012f.",addIndicatorTip:"Prid\u0117ti indikatori\u0173",chooseTemplatePopupTitle:"Pasirinkite \u0161ablon\u0105",stringsInTemplate:{name_number:"Skai\u010diai",name_gauge:"Matuoklis",name_vertical_gauge:"Vertikalus matuoklis",
name_horizontal_gauge:"Horizontalus matuoklis",name_pie_chart:"Skritulin\u0117 diagrama",name_column_chart:"Stulpelin\u0117 diagrama",name_bar_chart:"Juostin\u0117 diagrama",name_line_chart:"Linijin\u0117 diagrama",titleOfTheInfographic:"INFOGRAFIKO PAVADINIMAS",description:"Apra\u0161ymas: papildoma informacija apie \u0161\u012f infografik\u0105"},_localized:{}}});