// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Einstellungen",titleSettings:"Texteinstellungen",imageSettings:"Bildeinstellungen",backgroundColor:"Hintergrundfarbe",alignment:"Ausrichtung",textSize:"Textgr\u00f6\u00dfe",textColor:"Textfarbe",dataSource:"Datenquelle",chartSettings:"Diagrammeinstellungen",data:"Daten",dataLabels:"Datenbeschriftungen",displayMode:"Anzeigemodus",featureOption:"Werte auf Feature-Ebene anzeigen",categoryOption:"Werte nach Kategorie anzeigen",countOption:"Feature-Anzahl nach Kategorie anzeigen",
fieldOption:"Attributwerte als Diagramme anzeigen",categoryField:"Kategoriefeld",labelField:"Beschriftungsfeld",valueFields:"Wertefelder",operation:"Operation",sumOption:"Summe",averageOption:"Durchschnitt",minOption:"Minimum",maxOption:"Maximum",dataFormat:"Datenformat",decimalPlaces:"Dezimalstellen",prefix:"Pr\u00e4fix",suffix:"Suffix",dataType:"Datentyp",featureCount:"Feature-Anzahl",fieldStatistics:"Feldstatistik",display:"Anzeige",chartColor:"Diagrammfarbe",horizontalAxis:"Horizontale Achse",
verticalAxis:"Vertikale Achse",legend:"Legende",position:"Position",top:"Oben",bottom:"Unten",useDataSourceSelection:"Auswahl verwenden",dataSourceFilterByExtent:"Nach Ausdehnung filtern",changeTemplate:"Vorlage \u00e4ndern",numberSettings:"Einstellungen f\u00fcr Zahlen",gaugeSettings:"Skaleneinstellungen",indicators:"Indikatoren",ifValue:"Wenn Wert",and:"und",numberOperatorIsLessThan:"ist kleiner als",numberOperatorIsGreaterThan:"ist gr\u00f6\u00dfer als",numberOperatorIsBetween:"liegt zwischen",
numberOperatorIsEqual:"ist gleich",numberOperatorIsNotEqual:"ist nicht gleich",then:"Dann",ratio:"Verh\u00e4ltnis",trueValue:"Wahrer Wert",changeValueColor:"Farbe des Werts \u00e4ndern in",changeGaugeColor:"Farbe der Skala \u00e4ndern in",setIndicatorIcon:"Indikatorsymbol festlegen als",icons:"Symbole",style:"Style",placement:"Platzierung",left:"Links",replace:"Ersetzen",right:"Rechts",color:"Farbe",sortBy:"Sortieren nach",labelAxis:"Beschriftung",valueAxis:"Wert",minPeriod:"Mindestzeitraum",automatic:"Automatisch",
periodsWithOutRecords:"Zeitr\u00e4ume ohne Datens\u00e4tze",nullValue:"NULL-Wert",calculatedAsZero:"Als Null berechnet",ignored:"Ignoriert",maxCategories:"Maximale Kategorien",useLayerSymbology:"Layer-Symbolisierung verwenden",dataRange:"Datenbereich",targetValue:"Zielwert",currentValue:"Aktueller Wert",gaugeColor:"Farbe der Skala",min:"Minimum",max:"Maximum",displayValueIn:"Wert anzeigen als",noData:"Keine Daten",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Warnung",
noSettingWaring1:"Klicken Sie auf ein Element, um dessen Eigenschaften festzulegen.",noSettingWaring2:"Zum Anpassen der Gr\u00f6\u00dfe oder Neuanordnen eines Elements ziehen.",donNotShowAgain:"Nicht erneut anzeigen",changeTemplateWarning:"Damit werden alle Ihre Einstellungen gel\u00f6scht und es wird eine neue, leere Vorlage ge\u00f6ffnet.",requiredFieldWarning:"Dieser Wert ist erforderlich:",dataSourceNotSet:"Legen Sie die Datenquelle fest.",addIndicatorTip:"Indikator hinzuf\u00fcgen",chooseTemplatePopupTitle:"Vorlage ausw\u00e4hlen",
stringsInTemplate:{name_number:"Zahl",name_gauge:"Skala",name_vertical_gauge:"Vertikale Skala",name_horizontal_gauge:"Horizontale Skala",name_pie_chart:"Kreisdiagramm",name_column_chart:"Spaltendiagramm",name_bar_chart:"Balkendiagramm",name_line_chart:"Liniendiagramm",titleOfTheInfographic:"TITEL DER INFOGRAFIK",description:"Beschreibung: zus\u00e4tzliche Informationen \u00fcber diese Infografik."},_localized:{}}});