// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Inst\u00e4llningar",titleSettings:"Textinst\u00e4llningar",imageSettings:"Bildinst\u00e4llningar",backgroundColor:"Bakgrundsf\u00e4rg",alignment:"Justering",textSize:"Textstorlek",textColor:"Textf\u00e4rg",dataSource:"Datak\u00e4lla",chartSettings:"Diagraminst\u00e4llningar",data:"Data",dataLabels:"Dataetiketter",displayMode:"Visningsl\u00e4ge",featureOption:"Visa v\u00e4rden geoobjekt f\u00f6r geoobjekt",categoryOption:"Visa v\u00e4rden efter kategori",
countOption:"Visa geoobjektantal efter kategori",fieldOption:"Visa attributv\u00e4rden som diagram",categoryField:"Kategorif\u00e4lt",labelField:"Etikettf\u00e4lt",valueFields:"V\u00e4rdef\u00e4lt",operation:"\u00c5tg\u00e4rd",sumOption:"Summa",averageOption:"Genomsnitt",minOption:"Minimum",maxOption:"Maximalt",dataFormat:"Dataformat",decimalPlaces:"Decimaler",prefix:"Prefix",suffix:"Suffix",dataType:"Datatyp",featureCount:"Antal geoobjekt",fieldStatistics:"F\u00e4ltstatistik",display:"Visa",chartColor:"Diagramf\u00e4rg",
horizontalAxis:"Horisontell axel",verticalAxis:"Vertikal axel",legend:"Teckenf\u00f6rklaring",position:"Position",top:"\u00d6vre",bottom:"L\u00e4ngst ned",useDataSourceSelection:"Anv\u00e4nd markering",dataSourceFilterByExtent:"Filtrera efter utbredning",changeTemplate:"\u00c4ndra mall",numberSettings:"Talinst\u00e4llningar",gaugeSettings:"M\u00e4tarinst\u00e4llningar",indicators:"Indikatorer",ifValue:"Om v\u00e4rdet",and:"och",numberOperatorIsLessThan:"\u00e4r mindre \u00e4n",numberOperatorIsGreaterThan:"\u00e4r st\u00f6rre \u00e4n",
numberOperatorIsBetween:"\u00e4r mellan",numberOperatorIsEqual:"\u00e4r lika med",numberOperatorIsNotEqual:"\u00e4r inte lika med",then:"S\u00e5",ratio:"F\u00f6rh\u00e5llande",trueValue:"v\u00e4rdet Sant",changeValueColor:"\u00e4ndrar v\u00e4rdef\u00e4rgen till",changeGaugeColor:"\u00e4ndrar m\u00e4tarf\u00e4rgen till",setIndicatorIcon:"anger indikatorikonen som",icons:"Icons",style:"Format",placement:"Placering",left:"V\u00e4nster",replace:"Ers\u00e4tt",right:"H\u00f6ger",color:"F\u00e4rg",sortBy:"Sortera efter",
labelAxis:"Etikett",valueAxis:"V\u00e4rde",minPeriod:"Minsta period",automatic:"Automatisk",periodsWithOutRecords:"Perioder utan poster",nullValue:"Null-v\u00e4rde",calculatedAsZero:"Ber\u00e4knas som noll",ignored:"Ignored",maxCategories:"Maximala kategorier",useLayerSymbology:"Anv\u00e4nd lagrets symbologi",dataRange:"Dataintervall",targetValue:"M\u00e5lv\u00e4rde",currentValue:"Aktuellt v\u00e4rde",gaugeColor:"M\u00e4tarf\u00e4rg",min:"Minimum",max:"Maximalt",displayValueIn:"Visa v\u00e4rde i",
noData:"Inga data",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Varning",noSettingWaring1:"Klicka p\u00e5 ett element f\u00f6r att ange dess egenskaper.",noSettingWaring2:"Dra f\u00f6r att \u00e4ndra storlek eller \u00e4ndra ordning f\u00f6r ett element.",donNotShowAgain:"Visa inte igen",changeTemplateWarning:"Det h\u00e4r raderar alla dina inst\u00e4llningar och \u00f6ppnar en ny tom mall.",requiredFieldWarning:"Det h\u00e4r v\u00e4rdet \u00e4r obligatoriskt:",
dataSourceNotSet:"Ange datak\u00e4lla.",addIndicatorTip:"L\u00e4gg till en indikator",chooseTemplatePopupTitle:"V\u00e4lj en mall",stringsInTemplate:{name_number:"Nummer",name_gauge:"M\u00e4tare",name_vertical_gauge:"Vertikal m\u00e4tare",name_horizontal_gauge:"Horisontell m\u00e4tare",name_pie_chart:"Cirkeldiagram",name_column_chart:"Kolumndiagram",name_bar_chart:"Stapeldiagram",name_line_chart:"Linjediagram",titleOfTheInfographic:"NAMN P\u00c5 INFOGRAFIK",description:"Beskrivning: Ytterligare information om denna infografik."},
_localized:{}}});