// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Configura\u00e7\u00f5es",titleSettings:"Configura\u00e7\u00f5es de texto",imageSettings:"Configura\u00e7\u00f5es de imagem",backgroundColor:"Cor do plano de fundo",alignment:"Alinhamento",textSize:"Tamanho de texto",textColor:"Cor de texto",dataSource:"Fonte de dados",chartSettings:"Configura\u00e7\u00f5es do gr\u00e1fico",data:"Dados",dataLabels:"R\u00f3tulos de dados",displayMode:"Modo de Visualiza\u00e7\u00e3o",featureOption:"Exibir valores fei\u00e7\u00e3o por fei\u00e7\u00e3o",
categoryOption:"Exibir valores por categoria",countOption:"Exibir contagem de fei\u00e7\u00e3o por categoria",fieldOption:"Exibir valores de atributo como gr\u00e1ficos",categoryField:"Campo de Categoria",labelField:"Campo de r\u00f3tulo",valueFields:"Campos de valores",operation:"Opera\u00e7\u00e3o",sumOption:"Soma",averageOption:"M\u00e9dia",minOption:"M\u00ednimo",maxOption:"M\u00e1ximo",dataFormat:"Formato dos dados",decimalPlaces:"Casas decimais",prefix:"Prefixo",suffix:"Sufixo",dataType:"Tipo de dados",
featureCount:"Contagem de fei\u00e7\u00f5es",fieldStatistics:"Estat\u00edstica de campo",display:"Exibir",chartColor:"Cor do gr\u00e1fico",horizontalAxis:"Eixo horizontal",verticalAxis:"Eixo vertical",legend:"Legenda",position:"Posi\u00e7\u00e3o",top:"Superior",bottom:"Inferior",useDataSourceSelection:"Utilizar sele\u00e7\u00e3o",dataSourceFilterByExtent:"Filtrar por extens\u00e3o",changeTemplate:"Alterar modelo",numberSettings:"Configura\u00e7\u00f5es de n\u00famero",gaugeSettings:"Configura\u00e7\u00f5es do Medidor",
indicators:"Indicadores",ifValue:"Se valor",and:"l",numberOperatorIsLessThan:"\u00e9 menor que",numberOperatorIsGreaterThan:"\u00e9 maior que",numberOperatorIsBetween:"est\u00e1 entre",numberOperatorIsEqual:"\u00e9 igual a",numberOperatorIsNotEqual:"n\u00e3o \u00e9 igual a",then:"Ent\u00e3o",ratio:"Taxa",trueValue:"Valor verdadeiro",changeValueColor:"altera cor de valor para",changeGaugeColor:"altere cor de medidor para",setIndicatorIcon:"configurar \u00edcone de indicador como",icons:"\u00cdcones",
style:"Estilo",placement:"Disposi\u00e7\u00e3o",left:"Esquerda",replace:"Substituir",right:"Direita",color:"Cor",sortBy:"Classificar por",labelAxis:"R\u00f3tulo",valueAxis:"Valor",minPeriod:"Per\u00edodo m\u00ednimo",automatic:"Autom\u00e1tico",periodsWithOutRecords:"Per\u00edodos sem registros",nullValue:"Valor nulo",calculatedAsZero:"Calculado como zero",ignored:"Ignorado",maxCategories:"M\u00e1ximo de categorias",useLayerSymbology:"Utilizar simbologia da camada",dataRange:"Faixa de dados",targetValue:"Valor de alvo",
currentValue:"Valor atual",gaugeColor:"Cor do medidor",min:"M\u00ednimo",max:"M\u00e1ximo",displayValueIn:"Exibe o valor em",noData:"Sem dados",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Aviso",noSettingWaring1:"Clique em um elemento para configurar suas propriedades.",noSettingWaring2:"Arraste para dimensionar ou reordenar um elemento.",donNotShowAgain:"N\u00e3o mostrar novamente",changeTemplateWarning:"Isto apagar\u00e1 todas suas configura\u00e7\u00f5es e abre um novo modelo vazio.",
requiredFieldWarning:"Este valor \u00e9 exigido:",dataSourceNotSet:"Configure a fonte de dados.",addIndicatorTip:"Adicionar um indicador",chooseTemplatePopupTitle:"Escolher um modelo",stringsInTemplate:{name_number:"N\u00famero",name_gauge:"Medidor",name_vertical_gauge:"Medidor Vertical",name_horizontal_gauge:"Medidor Horizontal",name_pie_chart:"Gr\u00e1fico de Pizza",name_column_chart:"Gr\u00e1fico de Colunas",name_bar_chart:"Gr\u00e1fico de Barras",name_line_chart:"Gr\u00e1fico de Linha",titleOfTheInfographic:"T\u00cdTULO DO INFOGR\u00c1FICO",
description:"Descri\u00e7\u00e3o: informa\u00e7\u00f5es adicionais sobre este infogr\u00e1fico."},_localized:{}}});