// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Set\u0103ri",titleSettings:"Set\u0103rile de text",imageSettings:"Set\u0103ri imagine",backgroundColor:"Culoare de fundal",alignment:"Aliniere",textSize:"Dimensiune text",textColor:"Culoare text",dataSource:"Surs\u0103 de date",chartSettings:"Set\u0103ri diagram\u0103",data:"Date",dataLabels:"Etichete date",displayMode:"Mod afi\u015faj",featureOption:"Afi\u015fare valori pentru fiecare obiecte spa\u0163ial",categoryOption:"Afi\u015fare valori pe categorii",
countOption:"Afi\u015fare num\u0103r de obiecte spa\u0163iale pe categorii",fieldOption:"Afi\u015fare valori de atribute sub form\u0103 de diagram\u0103",categoryField:"C\u00e2mp pentru categorie",labelField:"C\u00e2mp etichet\u0103",valueFields:"C\u00e2mp valoare",operation:"Opera\u0163ie",sumOption:"Sum\u0103",averageOption:"Medie",minOption:"Minim",maxOption:"Maxim",dataFormat:"Format date",decimalPlaces:"Zecimale",prefix:"Prefix",suffix:"Sufix",dataType:"Tip de date",featureCount:"Num\u0103r obiecte spa\u0163iale",
fieldStatistics:"Statistici c\u00e2mp",display:"Afi\u015fare",chartColor:"Culoare diagram\u0103",horizontalAxis:"Ax\u0103 orizontal\u0103",verticalAxis:"Ax\u0103 vertical\u0103",legend:"Legend\u0103",position:"Pozi\u0163ie",top:"Sus",bottom:"Jos",useDataSourceSelection:"Utilizare selec\u0163ie",dataSourceFilterByExtent:"Filtrare dup\u0103 extindere",changeTemplate:"Modificare \u015fablon",numberSettings:"Set\u0103ri num\u0103r",gaugeSettings:"Set\u0103ri instrument de m\u0103sur\u0103",indicators:"Indicatoare",
ifValue:"Dac\u0103 valoarea",and:"\u015fi",numberOperatorIsLessThan:"este mai mic\u0103 dec\u00e2t",numberOperatorIsGreaterThan:"este mai mare de",numberOperatorIsBetween:"este \u00eentre",numberOperatorIsEqual:"este egal cu",numberOperatorIsNotEqual:"este diferit de",then:"Atunci",ratio:"Raport",trueValue:"Valoare adev\u0103rat\u0103",changeValueColor:"modificare culoare valoare la",changeGaugeColor:"modificare culoare instrument de m\u0103sur\u0103 la",setIndicatorIcon:"setare pictogram\u0103 indicator ca",
icons:"Pictograme",style:"Stil",placement:"Amplasare",left:"St\u00e2nga",replace:"\u00cenlocuire",right:"Dreapta",color:"Culoare",sortBy:"Sortare dup\u0103",labelAxis:"Etichet\u0103",valueAxis:"Valoare",minPeriod:"Perioad\u0103 minim\u0103",automatic:"Automat",periodsWithOutRecords:"Perioade f\u0103r\u0103 \u00eenregistr\u0103ri",nullValue:"Valoare nul\u0103",calculatedAsZero:"Calculat drept zero",ignored:"Ignorat",maxCategories:"Categorii maxime",useLayerSymbology:"Utilizare simbolistic\u0103 strat tematic \u00e2\u20ac\u2122",
dataRange:"Interval date",targetValue:"Valoare \u0163int\u0103",currentValue:"Valoare curent\u0103",gaugeColor:"Culoare instrument de m\u0103sur\u0103",min:"Minim",max:"Maxim",displayValueIn:"Afi\u015fare valoare \u00een",noData:"Nu exist\u0103 date",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Avertisment",noSettingWaring1:"Face\u0163i clic pe un element pentru a-i seta propriet\u0103\u0163ile.",noSettingWaring2:"Trage\u0163i pentru a redimensiona sau reordona un element.",
donNotShowAgain:"Nu se mai afi\u015feaz\u0103",changeTemplateWarning:"Aceasta v\u0103 va \u015fterge toate set\u0103rile \u015fi va deschide un \u015fablon nou, gol.",requiredFieldWarning:"Aceast\u0103 valoare este obligatorie:",dataSourceNotSet:"Seta\u0163i sursa datelor.",addIndicatorTip:"Ad\u0103uga\u0163i un indicator",chooseTemplatePopupTitle:"Alege\u0163i un \u015fablon",stringsInTemplate:{name_number:"Num\u0103r",name_gauge:"Instrument de m\u0103sur\u0103",name_vertical_gauge:"Instrument de m\u0103surare vertical",
name_horizontal_gauge:"Instrument de m\u0103surare orizontal",name_pie_chart:"Diagram\u0103 circular\u0103",name_column_chart:"Diagram\u0103 coloane",name_bar_chart:"Diagram\u0103 cu bare",name_line_chart:"Diagram\u0103 linii",titleOfTheInfographic:"TITLUL GRAFICULUI INFORMATIV",description:"Descriere: informa\u0163ii suplimentare despre acest grafic informativ."},_localized:{}}});