// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Parametry",titleSettings:"Ustawienia tekstu",imageSettings:"Ustawienia obrazu",backgroundColor:"Kolor t\u0142a",alignment:"Wyr\u00f3wnanie",textSize:"Rozmiar tekstu",textColor:"Kolor tekstu",dataSource:"\u0179r\u00f3d\u0142o danych",chartSettings:"Ustawienia diagramu",data:"Dane",dataLabels:"Etykiety danych",displayMode:"Tryb wy\u015bwietlania",featureOption:"Wy\u015bwietlaj warto\u015bci dla ka\u017cdego kolejnego obiektu",categoryOption:"Wy\u015bwietlaj warto\u015bci wg kategorii",
countOption:"Wy\u015bwietlaj liczb\u0119 obiekt\u00f3w wg kategorii",fieldOption:"Wy\u015bwietlaj warto\u015bci atrybut\u00f3w w postaci diagram\u00f3w",categoryField:"Pole kategorii",labelField:"Pole etykiety",valueFields:"Pola warto\u015bci",operation:"Dzia\u0142anie",sumOption:"Suma",averageOption:"\u015arednia",minOption:"Minimum",maxOption:"Maksimum",dataFormat:"Format danych",decimalPlaces:"Miejsca dziesi\u0119tne",prefix:"Prefiks",suffix:"Tytu\u0142",dataType:"Typ danych",featureCount:"Liczba obiekt\u00f3w",
fieldStatistics:"Statystyka p\u00f3l",display:"Wy\u015bwietl",chartColor:"Kolor diagramu",horizontalAxis:"O\u015b pozioma",verticalAxis:"O\u015b pionowa",legend:"Legenda",position:"Po\u0142o\u017cenie",top:"G\u00f3ra",bottom:"D\u00f3\u0142",useDataSourceSelection:"U\u017cyj zaznaczenia",dataSourceFilterByExtent:"Filtruj wg zasi\u0119gu",changeTemplate:"Zmie\u0144 szablon",numberSettings:"Ustawienia liczb",gaugeSettings:"Ustawienia kontrolki",indicators:"Wska\u017aniki",ifValue:"je\u017celi warto\u015b\u0107",
and:"and",numberOperatorIsLessThan:"jest mniejsze ni\u017c",numberOperatorIsGreaterThan:"jest wi\u0119ksze ni\u017c",numberOperatorIsBetween:"pomi\u0119dzy",numberOperatorIsEqual:"jest r\u00f3wna",numberOperatorIsNotEqual:"nie jest r\u00f3wna",then:"W\u00f3wczas",ratio:"Wsp\u00f3\u0142czynnik",trueValue:"Warto\u015b\u0107 rzeczywista",changeValueColor:"zmie\u0144 kolor warto\u015bci na",changeGaugeColor:"zmie\u0144 kolor kontrolki na",setIndicatorIcon:"ustaw ikon\u0119 wska\u017anika na",icons:"Ikony",
style:"Nadaj styl",placement:"Po\u0142o\u017cenie",left:"Lewy",replace:"Zast\u0105p",right:"Prawy",color:"Kolor",sortBy:"Sortuj wed\u0142ug",labelAxis:"Etykieta",valueAxis:"Warto\u015b\u0107",minPeriod:"Okres minimalny",automatic:"Automatycznie",periodsWithOutRecords:"Okresy bez rekord\u00f3w",nullValue:"Warto\u015b\u0107 pusta",calculatedAsZero:"Obliczone jako zero",ignored:"Ignorowane",maxCategories:"Maksymalna liczba kategorii",useLayerSymbology:"Zastosuj symbole warstw",dataRange:"Zakres dat",
targetValue:"Warto\u015b\u0107 docelowa",currentValue:"Warto\u015b\u0107 bie\u017c\u0105ca",gaugeColor:"Kolor kontrolki",min:"Minimum",max:"Maksimum",displayValueIn:"Wy\u015bwietlaj warto\u015b\u0107 w",noData:"Brak danych",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Ostrze\u017cenie",noSettingWaring1:"Kliknij element, aby skonfigurowa\u0107 jego w\u0142a\u015bciwo\u015bci.",noSettingWaring2:"Przeci\u0105gnij, aby zmieni\u0107 rozmiar lub kolejno\u015b\u0107 elementu.",
donNotShowAgain:"Nie pokazuj ponownie",changeTemplateWarning:"Spowoduje to usuni\u0119cie wszystkich ustawie\u0144 i otwarcie nowego pustego szablonu.",requiredFieldWarning:"Ta warto\u015b\u0107 jest wymagana:",dataSourceNotSet:"Skonfiguruj \u017ar\u00f3d\u0142o danych.",addIndicatorTip:"Dodaj wska\u017anik",chooseTemplatePopupTitle:"Wybierz szablon",stringsInTemplate:{name_number:"Liczba",name_gauge:"Kontrolka",name_vertical_gauge:"Kontrolka pionowa",name_horizontal_gauge:"Kontrolka pozioma",name_pie_chart:"Diagram ko\u0142owy",
name_column_chart:"Diagram kolumnowy",name_bar_chart:"Diagram s\u0142upkowy grupowy",name_line_chart:"Diagram liniowy",titleOfTheInfographic:"TYTU\u0141 INFOGRAFIKI",description:"Opis: dodatkowe informacje o tej infografice."},_localized:{}}});