// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Impostazioni",titleSettings:"Impostazioni del testo",imageSettings:"Impostazioni immagine",backgroundColor:"Colore di sfondo",alignment:"Allineamento",textSize:"Dimensione testo",textColor:"Colore testo",dataSource:"Origine dati",chartSettings:"Impostazioni grafico",data:"Dati",dataLabels:"Etichette dati",displayMode:"Modalit\u00e0 visualizzazione",featureOption:"Visualizza valori feature per feature",categoryOption:"Visualizza valori per categoria",
countOption:"Visualizza conteggi feature per categoria",fieldOption:"Visualizza valori attributi come grafici",categoryField:"Campo categoria",labelField:"Campo etichetta",valueFields:"Campi valore",operation:"Operazione",sumOption:"Somma",averageOption:"Media",minOption:"Minimo",maxOption:"Massimo",dataFormat:"Formato dati",decimalPlaces:"Posizioni decimali",prefix:"Prefisso",suffix:"Suffisso",dataType:"Tipo di dati",featureCount:"Conteggio feature",fieldStatistics:"Statistiche di campo",display:"Visualizza",
chartColor:"Colore grafico",horizontalAxis:"Asse orizzontale",verticalAxis:"Asse verticale",legend:"Legenda",position:"Posizione",top:"In alto",bottom:"In basso",useDataSourceSelection:"Usa selezione",dataSourceFilterByExtent:"Filtra per estensione",changeTemplate:"Cambia modello",numberSettings:"Impostazioni numero",gaugeSettings:"Impostazioni indicatore",indicators:"Indicatori",ifValue:"Valore If",and:"and",numberOperatorIsLessThan:"\u00e8 minore di",numberOperatorIsGreaterThan:"\u00e8 maggiore di",
numberOperatorIsBetween:"\u00e8 tra",numberOperatorIsEqual:"\u00e8 uguale a",numberOperatorIsNotEqual:"\u00e8 diversa da",then:"Then",ratio:"Percentuale",trueValue:"Valore True",changeValueColor:"modifica colore valore in",changeGaugeColor:"modifica colore indicatore in",setIndicatorIcon:"imposta icona indicatore come",icons:"Icone",style:"Stile",placement:"Posizionamento",left:"A sinistra",replace:"Sostituisci",right:"A destra",color:"Colore",sortBy:"Ordina per",labelAxis:"Etichetta",valueAxis:"Valore",
minPeriod:"Periodo minimo",automatic:"Automatico",periodsWithOutRecords:"Periodi senza record",nullValue:"Valore nullo",calculatedAsZero:"Calcolato come zero",ignored:"Ignorato",maxCategories:"Categorie massime",useLayerSymbology:"Utilizza simbologia del layer",dataRange:"Gamma dati",targetValue:"Valore target",currentValue:"Valore corrente",gaugeColor:"Colore indicatore",min:"Minimo",max:"Massimo",displayValueIn:"Visualizza valore in",noData:"Nessun dato",thousandAbbreviation:"k",millionAbbreviation:"M",
billionAbbreviation:"G",warning:"Avviso",noSettingWaring1:"Fare click su un elemento per impostarne le propriet\u00e0.",noSettingWaring2:"Trascinare per ridimensionare o riordinare un elemento.",donNotShowAgain:"Non mostrare pi\u00f9",changeTemplateWarning:"Cos\u00ec facendo si annulleranno tutte le impostazioni e si aprir\u00e0 un nuovo modello vuoto.",requiredFieldWarning:"Questo valore \u00e8 obbligatorio:",dataSourceNotSet:"Impostare l'origine dati.",addIndicatorTip:"Aggiungi indicatore",chooseTemplatePopupTitle:"Scegliere un modello",
stringsInTemplate:{name_number:"Numero",name_gauge:"Indicatore di livello",name_vertical_gauge:"Indicatore verticale",name_horizontal_gauge:"Indicatore orizzontale",name_pie_chart:"Grafico a torta",name_column_chart:"Grafico a colonne",name_bar_chart:"Grafico a barre",name_line_chart:"Grafico a linea",titleOfTheInfographic:"TITOLO INFOGRAFICA",description:"Descrizione: informazioni aggiuntive su quest'infografica."},_localized:{}}});