// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Innstillinger",titleSettings:"Tekstinnstillinger",imageSettings:"Bildeinnstillinger",backgroundColor:"Bakgrunnsfarge",alignment:"Justering",textSize:"Tekstst\u00f8rrelse",textColor:"Tekstfarge",dataSource:"Datakilde",chartSettings:"Diagraminnstillinger",data:"Data",dataLabels:"Dataetikketter",displayMode:"Visningsmodus",featureOption:"Vis verdier geoobjekt for geoobjekt",categoryOption:"Vis verdier etter kategori",countOption:"Vis antall geoobjekter etter kategori",
fieldOption:"Vis attributtverdier som diagrammer",categoryField:"Kategorifelt",labelField:"P\u00e5skriftfelt",valueFields:"Verdifelter",operation:"Operasjon",sumOption:"Summer",averageOption:"Gjennomsnitt",minOption:"Minimum",maxOption:"Maksimum",dataFormat:"Datoformat",decimalPlaces:"Desimaler",prefix:"Prefiks",suffix:"Suffiks",dataType:"Datatype",featureCount:"Geoobjektantall",fieldStatistics:"Feltstatistikk",display:"Vis",chartColor:"Diagramfarge",horizontalAxis:"Horisontal akse",verticalAxis:"Vertikal akse",
legend:"Tegnforklaring",position:"Posisjon",top:"Topp",bottom:"Bunn",useDataSourceSelection:"Bruk utvalg",dataSourceFilterByExtent:"Filtrer etter utstrekning",changeTemplate:"Endre mal",numberSettings:"Tallinnstillinger",gaugeSettings:"M\u00e5lerinnstillinger",indicators:"Indikatorer",ifValue:"Verdien Hvis",and:"og",numberOperatorIsLessThan:"er mindre enn",numberOperatorIsGreaterThan:"er st\u00f8rre enn",numberOperatorIsBetween:"er mellom",numberOperatorIsEqual:"er lik",numberOperatorIsNotEqual:"er ikke lik",
then:"S\u00e5",ratio:"Forhold",trueValue:"Verdien Sann",changeValueColor:"endre verdifarge til",changeGaugeColor:"endre m\u00e5lerfarge til",setIndicatorIcon:"angi indikatorikon som",icons:"Ikoner",style:"Stil",placement:"Plassering",left:"Venstre",replace:"Erstatt",right:"H\u00f8yre",color:"Farge",sortBy:"Sorter etter",labelAxis:"Etikett",valueAxis:"Verdi",minPeriod:"Minimumsperiode",automatic:"Automatisk",periodsWithOutRecords:"Perioder uten poster",nullValue:"Null verdi",calculatedAsZero:"Beregnet som null",
ignored:"Ignorert",maxCategories:"Maksimalt antall kategorier",useLayerSymbology:"Bruk lagens symboler",dataRange:"Dataomr\u00e5de",targetValue:"M\u00e5lverdi",currentValue:"Gjeldende verdi",gaugeColor:"M\u00e5lerfarge",min:"Minimum",max:"Maksimum",displayValueIn:"Vis verdi i",noData:"Ingen data",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Advarsel",noSettingWaring1:"Klikk p\u00e5 et element for \u00e5 angi egenskaper for elementet.",noSettingWaring2:"Dra for \u00e5 endre st\u00f8rrelsen eller rekkef\u00f8lgen for et element.",
donNotShowAgain:"Ikke vis igjen",changeTemplateWarning:"Dette fjerner alle innstillinger og \u00e5pner en ny tom mal.",requiredFieldWarning:"Denne verdien er obligatorisk:",dataSourceNotSet:"Angi datakilde.",addIndicatorTip:"Legg til en indikator",chooseTemplatePopupTitle:"Velg en mal",stringsInTemplate:{name_number:"Tall",name_gauge:"M\u00e5ler",name_vertical_gauge:"Vertikal m\u00e5ler",name_horizontal_gauge:"Horisontal m\u00e5ler",name_pie_chart:"Sektordiagram",name_column_chart:"Kolonnediagram",
name_bar_chart:"Stolpediagram",name_line_chart:"Linjediagram",titleOfTheInfographic:"TITTEL P\u00c5 INFOGRAFIKK",description:"Beskrivelse: tilleggsinformasjon om denne infografikken."},_localized:{}}});