// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Seaded",titleSettings:"Tekstiseaded",imageSettings:"Pildiseaded",backgroundColor:"Taustv\u00e4rv",alignment:"Joondus",textSize:"Teksti suurus",textColor:"Teksti v\u00e4rv",dataSource:"Andmeallikas",chartSettings:"Diagrammi seaded",data:"Andmed",dataLabels:"Andmete m\u00e4rgised",displayMode:"Kuvare\u017eiim",featureOption:"Kuva v\u00e4\u00e4rtused objektide kaupa",categoryOption:"Kuva v\u00e4\u00e4rtused kategooriate kaupa",countOption:"Kuva objektide kogused kategooriate kaupa",
fieldOption:"Kuva atribuutide v\u00e4\u00e4rtused diagrammidena",categoryField:"Kategooria v\u00e4li",labelField:"M\u00e4rgise v\u00e4li",valueFields:"V\u00e4\u00e4rtuse v\u00e4ljad",operation:"Toiming",sumOption:"Summa",averageOption:"Keskmine",minOption:"Miinimum",maxOption:"Maksimum",dataFormat:"Andmevorming",decimalPlaces:"K\u00fcmnendkohad",prefix:"Eesliide",suffix:"Sufiks",dataType:"Andmete t\u00fc\u00fcp",featureCount:"Objektide arv",fieldStatistics:"V\u00e4lja statistika",display:"Kuva",chartColor:"Diagrammi v\u00e4rv",
horizontalAxis:"Horisontaaltelg",verticalAxis:"Vertikaaltelg",legend:"Legendiga kaart",position:"Asukoht",top:"\u00dclemine",bottom:"Alumine",useDataSourceSelection:"Kasuta valikut",dataSourceFilterByExtent:"Filtreeri ulatuse alusel",changeTemplate:"Muuda malli",numberSettings:"Numbriseaded",gaugeSettings:"M\u00f5\u00f5dikuseaded",indicators:"Indikaatorid",ifValue:"Kui v\u00e4\u00e4rtus",and:"ja",numberOperatorIsLessThan:"on v\u00e4iksem kui",numberOperatorIsGreaterThan:"on suurem kui",numberOperatorIsBetween:"on vahemikus",
numberOperatorIsEqual:"on v\u00f5rdne",numberOperatorIsNotEqual:"ei v\u00f5rdu",then:"Siis",ratio:"Suhe",trueValue:"Tegelik v\u00e4\u00e4rtus",changeValueColor:"muuda v\u00e4\u00e4rtuse v\u00e4rviks",changeGaugeColor:"muuda m\u00f5\u00f5diku v\u00e4rviks",setIndicatorIcon:"m\u00e4\u00e4ra indikaatori ikooniks",icons:"Ikoonid",style:"Laad",placement:"Paigutus",left:"Vasak",replace:"Asenda",right:"Parem",color:"V\u00e4rv",sortBy:"Sorteeri:",labelAxis:"M\u00e4rgis",valueAxis:"V\u00e4\u00e4rtus",minPeriod:"Miinimumperiood",
automatic:"Automaatne",periodsWithOutRecords:"Kirjeteta perioodid",nullValue:"T\u00fchiv\u00e4\u00e4rtus",calculatedAsZero:"Arvutatud nullina",ignored:"Eiratud",maxCategories:"Maksimaalselt kategooriaid",useLayerSymbology:"Kasuta kihi s\u00fcmboolikat",dataRange:"Kuup\u00e4evavahemik",targetValue:"Sihtv\u00e4\u00e4rtus",currentValue:"Praegune v\u00e4\u00e4rtus",gaugeColor:"M\u00f5\u00f5diku v\u00e4rv",min:"Miinimum",max:"Maksimum",displayValueIn:"Kuva v\u00e4\u00e4rtust",noData:"Andmed puuduvad",
thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Hoiatus",noSettingWaring1:"Elemendi atribuutide m\u00e4\u00e4ramiseks kl\u00f5psake seda.",noSettingWaring2:"Elemendi suuruse muutmiseks v\u00f5i \u00fcmberj\u00e4rjestamiseks lohistage seda.",donNotShowAgain:"\u00c4ra seda enam kuva",changeTemplateWarning:"See kustutab k\u00f5ik teie seadistused ja avab uue malli.",requiredFieldWarning:"V\u00e4\u00e4rtus on n\u00f5utud:",dataSourceNotSet:"M\u00e4\u00e4ra andmeallikas.",
addIndicatorTip:"Lisa indikaator",chooseTemplatePopupTitle:"Vali mall",stringsInTemplate:{name_number:"Number",name_gauge:"M\u00f5\u00f5dik",name_vertical_gauge:"Vertikaalne m\u00f5\u00f5dik",name_horizontal_gauge:"Horisontaalne m\u00f5\u00f5dik",name_pie_chart:"Sektordiagramm",name_column_chart:"Tulpdiagramm",name_bar_chart:"Lintdiagramm",name_line_chart:"Joondiagramm",titleOfTheInfographic:"INFOGRAAFIKA PEALKIRI",description:"Kirjeldus: t\u00e4iendav teave selle infograafika kohta."},_localized:{}}});