// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Postavke",titleSettings:"Postavke teksta",imageSettings:"Postavke slike",backgroundColor:"Boja pozadine",alignment:"Poravnanje",textSize:"Veli\u010dina teksta",textColor:"Boja teksta",dataSource:"Izvor podataka",chartSettings:"Postavke grafikona",data:"Podaci",dataLabels:"Oznake podataka",displayMode:"Na\u010din prikaza",featureOption:"Prika\u017ei vrijednosti geoobjekata po geoobjektu",categoryOption:"Prika\u017ei vrijednosti po kategoriji",
countOption:"Prika\u017ei broj geoobjekata po kategoriji",fieldOption:"Prika\u017ei atributne vrijednosti kao grafikone",categoryField:"Polje kategorije",labelField:"Polje oznake",valueFields:"Polja vrijednosti",operation:"Radnja",sumOption:"Zbroj",averageOption:"Prosje\u010dno",minOption:"Minimum",maxOption:"Maksimum",dataFormat:"Format podataka",decimalPlaces:"Decimalna mjesta",prefix:"Prefiks",suffix:"Sufiks",dataType:"Vrsta podataka",featureCount:"Broj geoobjekata",fieldStatistics:"Statistika polja",
display:"Prika\u017ei",chartColor:"Boja grafikona",horizontalAxis:"Vodoravna os",verticalAxis:"Okomita os",legend:"Legenda",position:"Polo\u017eaj",top:"Vrh",bottom:"Dno",useDataSourceSelection:"Upotrijebi odabir",dataSourceFilterByExtent:"Filtriraj prema obuhvatu",changeTemplate:"Promijeni predlo\u017eak",numberSettings:"Postavke broja",gaugeSettings:"Postavke mjera\u010da",indicators:"Pokazatelji",ifValue:"Vrijednost ako",and:"i",numberOperatorIsLessThan:"manje je od",numberOperatorIsGreaterThan:"ve\u0107e je od",
numberOperatorIsBetween:"je izme\u0111u",numberOperatorIsEqual:"jednako je",numberOperatorIsNotEqual:"nije jednako",then:"Onda",ratio:"Omjer",trueValue:"Prava vrijednost",changeValueColor:"promijeni boju vrijednosti u",changeGaugeColor:"promijeni boju mjera\u010da u",setIndicatorIcon:"postavi ikonu pokazatelja kao",icons:"Ikone",style:"Stil",placement:"Raspored",left:"Lijevo",replace:"Zamijeni",right:"Desno",color:"Boja",sortBy:"Sortiraj prema",labelAxis:"Oznaka",valueAxis:"Vrijednost",minPeriod:"Minimalno razdoblje",
automatic:"Automatski",periodsWithOutRecords:"Razdoblja bez zapisa",nullValue:"Nema vrijednosti",calculatedAsZero:"Izra\u010dunato kao nula",ignored:"Zanemareno",maxCategories:"Maksimalne kategorije",useLayerSymbology:"Upotrijebi simbologiju sloja",dataRange:"Raspon podataka",targetValue:"Ciljna vrijednost",currentValue:"Trenutna vrijednost",gaugeColor:"Boja mjera\u010da",min:"Minimum",max:"Maksimum",displayValueIn:"Prika\u017ei vrijednosti u",noData:"Nema podataka",thousandAbbreviation:"k",millionAbbreviation:"M",
billionAbbreviation:"G",warning:"Upozorenje",noSettingWaring1:"Kliknite na element za postavljanje njegovih svojstava.",noSettingWaring2:"Povucite za mijenjanje veli\u010dine ili redoslijeda elementa.",donNotShowAgain:"Ne prikazuj ponovo",changeTemplateWarning:"Ovo \u0107e izbrisati sve va\u0161e postavke i otvoriti novi prazni predlo\u017eak.",requiredFieldWarning:"Ova je vrijednosti potrebna:",dataSourceNotSet:"Postavite izvor podataka.",addIndicatorTip:"Dodajte pokazatelja",chooseTemplatePopupTitle:"Odaberite predlo\u017eak",
stringsInTemplate:{name_number:"Broj",name_gauge:"Mjera\u010d",name_vertical_gauge:"Okomiti mjera\u010d",name_horizontal_gauge:"Vodoravni mjera\u010d",name_pie_chart:"Tortni grafikon",name_column_chart:"Stup\u010dasti grafikon",name_bar_chart:"Trakasti grafikon",name_line_chart:"Linijski grafikon",titleOfTheInfographic:"NASLOV INFOGRAFIKE",description:"Opis: dodatne informacije o infografici."},_localized:{}}});