// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Defini\u00e7\u00f5es",titleSettings:"Defini\u00e7\u00f5es de texto",imageSettings:"Defini\u00e7\u00f5es de imagem",backgroundColor:"Cor de fundo",alignment:"Alinhamento",textSize:"Tamanho do texto",textColor:"Cor do texto",dataSource:"Fonte de Dados",chartSettings:"Defini\u00e7\u00f5es de gr\u00e1ficos",data:"Dados",dataLabels:"R\u00f3tulos de dados",displayMode:"Modo de exibi\u00e7\u00e3o",featureOption:"Exibir valores elemento a elemento",
categoryOption:"Exibir valores por categoria",countOption:"Exibir contagens de elementos por categoria",fieldOption:"Exibir valores de atributos como gr\u00e1ficos",categoryField:"Campo de categoria",labelField:"Campo de r\u00f3tulo",valueFields:"Campos de valor",operation:"Opera\u00e7\u00e3o",sumOption:"Soma",averageOption:"M\u00e9dia",minOption:"M\u00ednimo",maxOption:"M\u00e1ximo",dataFormat:"Formato de dados",decimalPlaces:"Casas decimais",prefix:"Prefixo",suffix:"Sufixo",dataType:"Tipo de Dados",
featureCount:"Contagem de elementos",fieldStatistics:"Estat\u00edsticas de campos",display:"Exibir",chartColor:"Cor do gr\u00e1fico",horizontalAxis:"Eixo horizontal",verticalAxis:"Eixo vertical",legend:"Legenda",position:"Posi\u00e7\u00e3o",top:"Superior",bottom:"Inferior",useDataSourceSelection:"Utilizar sele\u00e7\u00e3o",dataSourceFilterByExtent:"Filtrar por extens\u00e3o",changeTemplate:"Alterar modelo",numberSettings:"Defini\u00e7\u00f5es de n\u00fameros",gaugeSettings:"Defini\u00e7\u00f5es de medidor",
indicators:"Indicadores",ifValue:"Valor If",and:"e",numberOperatorIsLessThan:"\u00e9 inferior a",numberOperatorIsGreaterThan:"\u00e9 superior a",numberOperatorIsBetween:"\u00e9 entre",numberOperatorIsEqual:"\u00e9 igual a",numberOperatorIsNotEqual:"n\u00e3o \u00e9 igual a",then:"Portanto",ratio:"R\u00e1cio",trueValue:"Valor real",changeValueColor:"Alterar cor do valor para",changeGaugeColor:"Alterar cor do medidor para",setIndicatorIcon:"Definir \u00edcone de indicador como",icons:"\u00cdcones",style:"Estilo",
placement:"Coloca\u00e7\u00e3o",left:"Esquerda",replace:"Substituir",right:"Direita",color:"Cor",sortBy:"Ordenar por",labelAxis:"R\u00f3tulo",valueAxis:"Valor",minPeriod:"Per\u00edodo m\u00ednimo",automatic:"Autom\u00e1tico",periodsWithOutRecords:"Per\u00edodos sem registos",nullValue:"Valor nulo",calculatedAsZero:"Calculado como zero",ignored:"Ignorado",maxCategories:"M\u00e1ximo de categorias",useLayerSymbology:"Utilizar simbologia da camada",dataRange:"Intervalo de datas",targetValue:"Valor alvo",
currentValue:"Valor atual",gaugeColor:"Cor do medidor",min:"M\u00ednimo",max:"M\u00e1ximo",displayValueIn:"Exibir valor em",noData:"Sem dados",thousandAbbreviation:"q",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Aviso",noSettingWaring1:"Clique num elemento para definir as respetivas propriedades.",noSettingWaring2:"Arraste para redimensionar ou reordenar um elemento.",donNotShowAgain:"N\u00e3o exibir novamente",changeTemplateWarning:"Esta a\u00e7\u00e3o ir\u00e1 apagar todas as suas defini\u00e7\u00f5es e abrir\u00e1 um novo modelo vazio",
requiredFieldWarning:"Este valor \u00e9 exigido:",dataSourceNotSet:"Por favor, defina a fonte de dados.",addIndicatorTip:"Adicionar um indicador",chooseTemplatePopupTitle:"Seleccione um modelo",stringsInTemplate:{name_number:"N\u00famero",name_gauge:"Medidor",name_vertical_gauge:"Medidor Vertical",name_horizontal_gauge:"Medidor Horizontal",name_pie_chart:"Gr\u00e1fico Circular",name_column_chart:"Gr\u00e1fico de Colunas",name_bar_chart:"Gr\u00e1fico de Barras",name_line_chart:"Gr\u00e1fico de Linhas",
titleOfTheInfographic:"T\u00cdTULO DA INFOGRAFIA",description:"Descri\u00e7\u00e3o: informa\u00e7\u00f5es adicionais dobre esta infografia."},_localized:{}}});