// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Indstillinger",titleSettings:"Tekstindstillinger",imageSettings:"Billedindstillinger",backgroundColor:"Baggrundsfarve",alignment:"Justering",textSize:"Tekstst\u00f8rrelse",textColor:"Tekstfarve",dataSource:"Datakilde",chartSettings:"Diagramindstillinger",data:"Data",dataLabels:"Dataetiketter",displayMode:"Visningstilstand",featureOption:"Vis v\u00e6rdier objekt for objekt",categoryOption:"Vis v\u00e6rdier efter kategori",countOption:"Vis objektantal efter kategori",
fieldOption:"Vis attributv\u00e6rdier som diagrammer",categoryField:"Kategorifelt",labelField:"Etiketfelt",valueFields:"V\u00e6rdifelter",operation:"Handling",sumOption:"Sum",averageOption:"Gennemsnit",minOption:"Minimum",maxOption:"Maksimum",dataFormat:"Dataformat",decimalPlaces:"Decimalpladser",prefix:"Pr\u00e6fiks",suffix:"Suffix",dataType:"Datatype",featureCount:"Objektt\u00e6lling",fieldStatistics:"Feltstatistik",display:"Visning",chartColor:"Diagramfarve",horizontalAxis:"Horisontal akse",verticalAxis:"Vertikal akse",
legend:"Signaturforklaring",position:"Position",top:"Top",bottom:"Bund",useDataSourceSelection:"Brug markering",dataSourceFilterByExtent:"Filtr\u00e9r efter udstr\u00e6kning",changeTemplate:"Redig\u00e9r skabelon",numberSettings:"Talindstillinger",gaugeSettings:"M\u00e5leindstillinger",indicators:"Indikatorer",ifValue:"Hvis v\u00e6rdi",and:"og",numberOperatorIsLessThan:"er mindre end",numberOperatorIsGreaterThan:"er st\u00f8rre end",numberOperatorIsBetween:"er mellem",numberOperatorIsEqual:"er lig med",
numberOperatorIsNotEqual:"er ikke lig med",then:"S\u00e5",ratio:"Forhold",trueValue:"Sand v\u00e6rdi",changeValueColor:"skift v\u00e6rdifarve til",changeGaugeColor:"skift m\u00e5lefarve til",setIndicatorIcon:"indstil indikatorikon som",icons:"Ikoner",style:"Type",placement:"Placering",left:"Venstre",replace:"Erstat",right:"H\u00f8jre",color:"Farve",sortBy:"Sort\u00e9r efter",labelAxis:"M\u00e6rke",valueAxis:"V\u00e6rdi",minPeriod:"Minimumsperiode",automatic:"Automatisk",periodsWithOutRecords:"Perioder uden poster",
nullValue:"Nulv\u00e6rdi",calculatedAsZero:"Beregnet som nul",ignored:"Ignored",maxCategories:"Maksimumkategorier",useLayerSymbology:"Brug lagets symbologi",dataRange:"Datainterval",targetValue:"M\u00e5lv\u00e6rdi",currentValue:"Aktuel v\u00e6rdi",gaugeColor:"M\u00e5lefarve",min:"Minimum",max:"Maksimum",displayValueIn:"Vis v\u00e6rdi i",noData:"Ingen data",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Advarsel",noSettingWaring1:"Klik p\u00e5 et element for at angive dets egenskaber.",
noSettingWaring2:"Tr\u00e6k for at \u00e6ndre st\u00f8rrelse p\u00e5 eller r\u00e6kkef\u00f8lge for et element.",donNotShowAgain:"Vis ikke igen",changeTemplateWarning:"Dette vil slette alle dine indstillinger og \u00e5bne en ny, tom skabelon.",requiredFieldWarning:"Denne v\u00e6rdi er obligatorisk:",dataSourceNotSet:"Angiv datakilde.",addIndicatorTip:"Tilf\u00f8j en indikator",chooseTemplatePopupTitle:"V\u00e6lg en skabelon",stringsInTemplate:{name_number:"Nummer",name_gauge:"M\u00e5ler",name_vertical_gauge:"Vertikal m\u00e5ling",
name_horizontal_gauge:"Horisontal m\u00e5ling",name_pie_chart:"Cirkeldiagram",name_column_chart:"Kolonnediagram",name_bar_chart:"S\u00f8jlediagram",name_line_chart:"Linjediagram",titleOfTheInfographic:"TITEL P\u00c5 INFOGRAFIK",description:"Beskrivelse: Flere oplysninger om denne infografik."},_localized:{}}});