// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Postavke",titleSettings:"Postavke teksta",imageSettings:"Postavke snimka",backgroundColor:"Boja pozadine",alignment:"Poravnanje",textSize:"Veli\u010dina teksta",textColor:"Boja teksta",dataSource:"Izvor podataka",chartSettings:"Postavke grafikona",data:"Podaci",dataLabels:"Oznake podataka",displayMode:"Re\u017eim prikaza",featureOption:"Prika\u017ei vrednosti geoobjekat po geoobjekat",categoryOption:"Prika\u017ei vrednosti po kategoriji",
countOption:"Prika\u017ei broj geoobjekata po kategoriji",fieldOption:"Prika\u017ei vrednosti atributa kao grafikon",categoryField:"Polje kategorije",labelField:"Polje oznake",valueFields:"Polje vrednosti",operation:"Radnja",sumOption:"Zbir",averageOption:"Prose\u010dno",minOption:"Minimum",maxOption:"Maksimum",dataFormat:"Format podataka",decimalPlaces:"Decimale",prefix:"Prefiks",suffix:"Sufiks",dataType:"Tip podataka",featureCount:"Broja\u010d geoobjekata",fieldStatistics:"Statistika polja",display:"Prikaz",
chartColor:"Boja grafikona",horizontalAxis:"Horizontalna osa",verticalAxis:"Vertikalna osa",legend:"Legenda",position:"Pozicija",top:"Vrh",bottom:"Dno",useDataSourceSelection:"Koristite selekciju",dataSourceFilterByExtent:"Filtriraj po obuhvatu",changeTemplate:"Promeni \u0161ablon",numberSettings:"Postavke broja",gaugeSettings:"Postavke mera\u010da",indicators:"Indikatori",ifValue:"Ako je vrednost",and:"i",numberOperatorIsLessThan:"je manje od",numberOperatorIsGreaterThan:"je ve\u0107e od",numberOperatorIsBetween:"je izme\u0111u",
numberOperatorIsEqual:"je jednako",numberOperatorIsNotEqual:"nije jednako",then:"Onda",ratio:"Odnos",trueValue:"Prava vrednost",changeValueColor:"promeni boju vrednosti na",changeGaugeColor:"promeni boju mera\u010da na",setIndicatorIcon:"postavi ikonu indikatora kao",icons:"Ikone",style:"Stil",placement:"Polo\u017eaj",left:"Levo",replace:"Zameni",right:"Desno",color:"Boja",sortBy:"Sortiraj po",labelAxis:"Oznaka",valueAxis:"Vrednost",minPeriod:"Minimalni period",automatic:"Automatski",periodsWithOutRecords:"Periodi bez zapisa",
nullValue:"Bez vrednosti",calculatedAsZero:"Izra\u010dunato kao nula",ignored:"Zanemareno",maxCategories:"Maksimalne kategorije",useLayerSymbology:"Koristi simbologiju sloja",dataRange:"Opseg datuma",targetValue:"Ciljna vrednost",currentValue:"Trenutna vrednost",gaugeColor:"Boja mera\u010da",min:"Minimum",max:"Maksimum",displayValueIn:"Prika\u017ei vrednost u",noData:"Nema podataka",thousandAbbreviation:"k",millionAbbreviation:"S",billionAbbreviation:"G",warning:"Upozorenje",noSettingWaring1:"Kliknite na element kako biste postavili njegova svojstva.",
noSettingWaring2:"Prevucite da biste promenili veli\u010dinu ili preuredili element.",donNotShowAgain:"Ne prikazuj ponovo",changeTemplateWarning:"Ovo \u0107e obrisati sve va\u0161e postavke i otvoriti nov prazan \u0161ablon.",requiredFieldWarning:"Ova vrednost je obavezna:",dataSourceNotSet:"Postavite izvor podataka.",addIndicatorTip:"Dodaj indikator",chooseTemplatePopupTitle:"Odaberite \u0161ablon",stringsInTemplate:{name_number:"Broj",name_gauge:"Mera\u010d",name_vertical_gauge:"Vertikalni mera\u010d",
name_horizontal_gauge:"Horizontalni mera\u010d",name_pie_chart:"Kru\u017eni grafikon",name_column_chart:"Stubi\u010dasti grafikon",name_bar_chart:"Trakasti grafikon",name_line_chart:"Linijski grafikon",titleOfTheInfographic:"NASLOV INFOGRAFIKE",description:"Opis: dodatne informacije u vezi sa ovom infografikom."},_localized:{}}});