// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Nastaven\u00ed",titleSettings:"Nastaven\u00ed textu",imageSettings:"Nastaven\u00ed obr\u00e1zku",backgroundColor:"Barva pozad\u00ed",alignment:"Zarovn\u00e1n\u00ed",textSize:"Velikost textu",textColor:"Barva textu",dataSource:"Zdroj dat",chartSettings:"Nastaven\u00ed grafu",data:"Data",dataLabels:"Popisky dat",displayMode:"Re\u017eim zobrazen\u00ed",featureOption:"Zobrazit hodnoty prvek po prvku",categoryOption:"Zobrazit hodnoty podle kategorie",
countOption:"Zobrazit po\u010dty prvk\u016f podle kategorie",fieldOption:"Zobrazit hodnoty atribut\u016f jako grafy",categoryField:"Pole kategorie",labelField:"Pole popisk\u016f",valueFields:"Pole hodnot",operation:"Operace",sumOption:"Suma",averageOption:"Pr\u016fm\u011br",minOption:"Minimum",maxOption:"Maximum",dataFormat:"Form\u00e1t dat",decimalPlaces:"Desetinn\u00e1 m\u00edsta",prefix:"P\u0159edpona",suffix:"Titul",dataType:"Typ dat",featureCount:"Po\u010det prvk\u016f",fieldStatistics:"Statistiky pole",
display:"Zobrazen\u00ed",chartColor:"Barva grafu",horizontalAxis:"Vodorovn\u00e1 osa",verticalAxis:"Svisl\u00e1 osa",legend:"Legenda",position:"Pozice",top:"Naho\u0159e",bottom:"Dole",useDataSourceSelection:"Pou\u017e\u00edt v\u00fdb\u011br",dataSourceFilterByExtent:"Filtrovat podle rozsahu",changeTemplate:"Zm\u011bnit \u0161ablonu",numberSettings:"Nastaven\u00ed \u010d\u00edsel",gaugeSettings:"Nastaven\u00ed m\u011b\u0159i\u010de",indicators:"Ukazatele",ifValue:"Pokud hodnota",and:"a",numberOperatorIsLessThan:"je men\u0161\u00ed ne\u017e",
numberOperatorIsGreaterThan:"je v\u011bt\u0161\u00ed ne\u017e",numberOperatorIsBetween:"je mezi",numberOperatorIsEqual:"rovn\u00e1 se",numberOperatorIsNotEqual:"nerovn\u00e1 se",then:"Pak",ratio:"Pom\u011br",trueValue:"Hodnota True",changeValueColor:"zm\u011bnit barvu hodnoty na",changeGaugeColor:"zm\u011bnit barvu m\u011b\u0159i\u010de na",setIndicatorIcon:"nastavit ukazatel ikony jako",icons:"Ikony",style:"Styl",placement:"Um\u00edst\u011bn\u00ed",left:"Vlevo",replace:"Nahradit",right:"Vpravo",
color:"Barva",sortBy:"Se\u0159adit podle",labelAxis:"Popisek",valueAxis:"Hodnota",minPeriod:"Minim\u00e1ln\u00ed obdob\u00ed",automatic:"Automaticky",periodsWithOutRecords:"Obdob\u00ed bez z\u00e1znam\u016f",nullValue:"Nulov\u00e1 hodnota",calculatedAsZero:"Vypo\u010dteno jako nula",ignored:"Ignorov\u00e1no",maxCategories:"Maximum kategori\u00ed",useLayerSymbology:"Pou\u017e\u00edt symboliku vrstev",dataRange:"Rozmez\u00ed dat",targetValue:"C\u00edlov\u00e1 hodnota",currentValue:"Sou\u010dasn\u00e1 hodnota",
gaugeColor:"Barva m\u011b\u0159i\u010de",min:"Minimum",max:"Maximum",displayValueIn:"Zobrazit hodnotu v",noData:"\u017d\u00e1dn\u00e1 data",thousandAbbreviation:"k",millionAbbreviation:"m",billionAbbreviation:"G",warning:"Varov\u00e1n\u00ed",noSettingWaring1:"Kliknut\u00edm na prvek nastav\u00edte jeho vlastnosti.",noSettingWaring2:"P\u0159eta\u017een\u00edm zm\u011bn\u00edte velikost nebo po\u0159ad\u00ed prvku.",donNotShowAgain:"Znovu nezobrazovat",changeTemplateWarning:"Ve\u0161ker\u00e9 va\u0161e nastaven\u00ed bude vymaz\u00e1no a otev\u0159e se nov\u00e1 pr\u00e1zdn\u00e1 \u0161ablona.",
requiredFieldWarning:"Tato hodnota je povinn\u00e1:",dataSourceNotSet:"Nastavte zdroj dat.",addIndicatorTip:"P\u0159idat ukazatel",chooseTemplatePopupTitle:"Vybrat \u0161ablonu",stringsInTemplate:{name_number:"\u010c\u00edslo",name_gauge:"M\u011b\u0159i\u010d",name_vertical_gauge:"Svisl\u00fd m\u011b\u0159i\u010d",name_horizontal_gauge:"Vodorovn\u00fd m\u011b\u0159i\u010d",name_pie_chart:"V\u00fdse\u010dov\u00fd graf",name_column_chart:"Sloupcov\u00fd graf",name_bar_chart:"Pruhov\u00fd graf",name_line_chart:"Spojnicov\u00fd graf",
titleOfTheInfographic:"N\u00c1ZEV INFOGRAFIKY",description:"Popis: dal\u0161\u00ed informace o t\u00e9to infografice."},_localized:{}}});