// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/Deferred dojo/query ./utils dijit/_TemplatedMixin dijit/_WidgetBase esri/undoManager esri/OperationBase esri/graphic esri/tasks/query esri/tasks/QueryTask esri/tasks/RelationshipQuery esri/layers/FeatureLayer esri/dijit/AttributeInspector esri/dijit/Popup esri/dijit/PopupTemplate jimu/SelectionManager jimu/ConfigManager jimu/dijit/DropdownMenu jimu/dijit/LoadingIndicator jimu/LayerInfos/LayerInfos".split(" "),
function(n,f,l,g,m,k,q,p,w,x,y,z,A,r,t,B,C,D,E,F,u,G,H,I,J){var h=n([x,w],{baseClass:"related-records-editor",templateString:"\x3cdiv\x3e\x3cdiv class\x3d'operation-box' data-dojo-attach-point\x3d'operationBox'\x3e\x3cdiv class\x3d'previos-btn feature-action' data-dojo-attach-point\x3d'previouBtn'data-dojo-attach-event\x3d'click:_onPreviouBtnClick'\x3e\x3c/div\x3e\x3cdiv class\x3d'operation-title' data-dojo-attach-point\x3d'operationTitle'\x3e\x3c/div\x3e\x3cdiv class\x3d'add-new-btn' data-dojo-attach-point\x3d'addNewBtn'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'content-box' data-dojo-attach-point\x3d'contentBox'\x3e\x3c/div\x3e\x3c/div\x3e",
editorATI:null,originalFeature:null,originalLayer:null,originalJimuLayerInfo:null,layerInfosObj:null,undoManager:null,refDomNode:null,_temporaryData:null,tableInfosParam:null,postCreate:function(){this._init();g.place(this.domNode,this.refDomNode,"after");window.isRTL?g.addClass(this.previouBtn,"icon-arrow-forward"):g.addClass(this.previouBtn,"icon-arrow-back");this.loading=(new I({hidden:!0})).placeAt(this.domNode);this._clearPage();this.showFirstPage({feature:this.originalFeature,oriJimuLayerInfo:this.originalJimuLayerInfo})},
_init:function(){this.refDomNode=this.editorATI.domNode;this.originalLayer=this.originalFeature.getLayer();this.layerInfosObj=J.getInstanceSync();this.originalJimuLayerInfo=this.layerInfosObj.getLayerOrTableInfoById(this.originalLayer.id);this.undoManager=new y;this._temporaryData={eventHandles:[],dijits:[]};this._tempPopup=new E({},g.create("div"));this._tempPopup.show()},destroy:function(){this._clearPage();this._tempPopup.destroy();this.inherited(arguments)},_getRelatedTableInfoArray:function(a){var b=
new k,c=[];a.getRelatedTableInfoArray("esriRelRoleOrigin").then(f.hitch(this,function(a){l.forEach(a,function(a){this._findTableInfoFromTableInfosParam(a)&&c.push(a)},this);b.resolve(c)}));return b},_getRelatedRecordsByQuery:function(a){var b=new k,c=new r,e=new t(a.destJimuLayerInfo.getUrl()),d=a.destJimuLayerInfo.layerObject.relationships.keyField,v=a.oriJimuLayerInfo.layerObject.objectIdField;c.where=d?d+" \x3d "+a.feature.attributes[d]:v+" \x3d "+a.feature.attributes[v];c.outFields=["*"];e.execute(c,
f.hitch(this,function(a){b.resolve(a)}));return b},_getRelatedRecordsByRelatedQuery:function(a){var b=new k,c=new B,e=this._getOriRelationshipByDestLayer(a);c.outFields=["*"];c.relationshipId=e.id;var d=a.feature.attributes[a.oriJimuLayerInfo.layerObject.objectIdField];c.objectIds=[d];a.oriJimuLayerInfo.layerObject.queryRelatedFeatures(c,f.hitch(this,function(a){(a=a[d]&&a[d].features)?b.resolve(a):b.resolve([])}),f.hitch(this,function(){b.resolve([])}));return b},_getOriRelationshipByDestLayer:function(a){var b=
null;l.some(a.oriJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===a.destJimuLayerInfo.layerObject.layerId)return b=c,!0},this);return b},_getDestRelationshipByDestLayer:function(a){var b=null;l.some(a.destJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===a.oriJimuLayerInfo.layerObject.layerId)return b=c,!0},this);return b},_createATI:function(a){var b=null,c=this._findTableInfoFromTableInfosParam(a.destJimuLayerInfo);c&&(b=new h.ATI({layerInfos:[c],
hideNavButtons:!0},g.create("div")),b.startup(),this._temporaryData.dijits.push(b));c=m(b,"delete",f.hitch(this,this._onDeleteBtnClick,a));this._temporaryData.eventHandles.push(c);c=m(b,"attribute-change",f.hitch(this,this._onAttributeChange,a));this._temporaryData.eventHandles.push(c);return b},_findTableInfoFromTableInfosParam:function(a){var b=null;l.some(this.tableInfosParam,function(c){if(c.featureLayer.id===a.id)return b=c,!0},this);return b},_addNewRelatedRecord:function(a){var b=new k,c=a.destJimuLayerInfo.layerObject,
e=this._getTemplateFromLayerObject(c),e=f.mixin({},e?e.prototype.attributes:{}),d=this._getOriRelationshipByDestLayer(a),g=this._getDestRelationshipByDestLayer(a);d.keyField&&g&&g.keyField?(d=p.ignoreCaseToGetFieldKey(a.oriJimuLayerInfo.layerObject,d.keyField),g=p.ignoreCaseToGetFieldKey(a.destJimuLayerInfo.layerObject,g.keyField),d&&g&&(e[g]=a.feature.attributes[d])):d.keyField&&(d=p.ignoreCaseToGetFieldKey(a.oriJimuLayerInfo.layerObject,d.keyField))&&(e[d]=a.feature.attributes[d]);var h=new A(null,
null,e,null);c.applyEdits([h],null,null,f.hitch(this,function(a){var d=a[0];if(d.success&&d.objectId){a=new r;var e=new t(c.url);a.where=c.objectIdField+" \x3d "+d.objectId;a.outFields=["*"];e.execute(a,f.hitch(this,function(a){(a=a.features[0])?b.resolve(a):(h.attributes[c.objectIdField]=d.objectId,b.resolve(h))}),f.hitch(this,function(){b.reject()}))}else b.reject()}),f.hitch(this,function(){b.reject()}));return b},_deleteRelatedRecord:function(a){var b=new k;a.destJimuLayerInfo.layerObject.applyEdits(null,
null,[a.relatedFeature],f.hitch(this,function(){b.resolve()}),f.hitch(this,function(){b.reject()}));return b},_updateRelatedRecord:function(a,b){var c=new k,e=a.destJimuLayerInfo.layerObject,d=a.relatedFeature;d.attributes[b.fieldName]=b.fieldValue;e.applyEdits(null,[d],null,f.hitch(this,function(){b.target&&b.target._selection&&b.target._selection[0]&&(b.target._selection[0].attributes[b.fieldName]=b.fieldValue,b.fieldName===e.typeIdField&&(e.ownershipBasedAccessControlForFeatures=!0,b.target.refresh(),
e.ownershipBasedAccessControlForFeatures=!1));c.resolve()}),f.hitch(this,function(){c.reject()}));return c},_getDisplayTitleOfRelatedRecord:function(a,b,c){var e=a.getInfoTemplate();return(a="popupTitle"===c&&e?"function"===typeof e.title?e.title(b):e.title:this._getDisplayTitleFromPopup(a,b,c))?a:""},_getDisplayTitleFromPopup:function(a,b,c){(a=this._getPopupTemplateWithOnlyDisplayField(a,c))?(b.setInfoTemplate(a),this._tempPopup.setFeatures([b]),c=(c=q("td.attrValue",this._tempPopup.domNode)[0])&&
c.innerHTML,b.setInfoTemplate(null)):c=p.getAttrByFieldKey(b,c);return c},_getPopupTemplateWithOnlyDisplayField:function(a,b){var c=a._getCustomPopupInfo(a.layerObject,[b]);return new F(c)},_getTemplateFromLayerObject:function(a){var b=null;a.templates&&a.templates[0]?b=a.templates[0]:a.types&&a.types[0]&&a.types[0].templates[0]&&(b=a.types[0].templates[0]);return b},showRelatedRecords:function(a){this._changeRefDomNode();var b=f.getObject("_wabProperties.originalLayerName",!1,a.destJimuLayerInfo.layerObject)||
a.destJimuLayerInfo.title;this._setOperationTitle(b);this._clearPage();this.loading.show();this._getRelatedRecordsByRelatedQuery(a).then(f.hitch(this,function(b){this._showAddNewBtn(a);0<b.length?this._setTitle(window.jimuNls.popup.relatedRecords):this._setTitle(window.jimuNls.popup.noRelatedRecotds,"font-normal");var c=this._showFieldSelector(a.destJimuLayerInfo);l.forEach(b,function(b,e){b._layer=a.destJimuLayerInfo.layerObject;var d=this._getDisplayTitleOfRelatedRecord(a.destJimuLayerInfo,b,c),
d=g.create("div",{"class":"item record-item "+(0===e%2?"oddLine":"evenLine"),innerHTML:d},this.contentBox);d.relatedRecord=b;d=m(d,"click",f.hitch(this,function(){this._addOperation(h.OPERATION_SHOW_RELATED_RECORDS,a);this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,b))}));this._temporaryData.eventHandles.push(d)},this);this.loading.hide()}))},showInspector:function(a){this._changeRefDomNode();var b=a.destJimuLayerInfo.layerObject,c=f.getObject("_wabProperties.originalLayerName",
!1,b)||a.destJimuLayerInfo.title,b=f.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",!1,b),e=this._getDisplayTitleOfRelatedRecord(a.destJimuLayerInfo,a.relatedFeature,b);"popupTitle"!==b&&(e=c+": "+e);this._setOperationTitle(e);this._clearPage();this.loading.show();(c=this._createATI(a))&&g.place(c.domNode,this.contentBox);c=a.destJimuLayerInfo.layerObject.objectIdField;b=new r;b.where=c+" \x3d "+a.relatedFeature.attributes[c];a.destJimuLayerInfo.layerObject.selectFeatures(b,
C.SELECTION_NEW,f.hitch(this,function(){this.loading.hide();var b=a.destJimuLayerInfo.layerObject.getSelectedFeatures();b&&b[0]&&b[0].geometry&&this._activeGraphicEdit(b[0],a.oriJimuLayerInfo)}));this.showRelatedTables(this._createOperationData(a.relatedFeature,a.destJimuLayerInfo,null,null),a)},showRelatedTables:function(a,b){this._getRelatedTableInfoArray(a.oriJimuLayerInfo).then(f.hitch(this,function(c){0<c.length&&this._setTitle(window.jimuNls.popup.relatedTables);l.forEach(c,function(c,d){var e=
g.create("div",{"class":"item table-item "+(0===d%2?"oddLine":"evenLine"),innerHTML:c.title},this.contentBox),e=m(e,"click",f.hitch(this,function(){c.getLayerObject().then(f.hitch(this,function(){b?this._addOperation(h.OPERATION_SHOW_INSPECTOR,b):this._addOperation(h.OPERATION_FIRST,a);this.showRelatedRecords(this._createOperationData(a.feature,a.oriJimuLayerInfo,c,null))}))}));this._temporaryData.eventHandles.push(e)},this)}))},showFirstPage:function(a,b){this._clearPage();this._revertRefDomNode();
this.showRelatedTables(a);b&&(l.forEach(this._editWidget._jimuLayerInfos.getLayerInfoArray(),function(a){a.layerObject&&a.layerObject.clearSelection&&a.id!==this.originalJimuLayerInfo.id&&u.getInstance().clearSelection(a.layerObject)},this),this.originalFeature.setSymbol(this.originalLayer.getSelectionSymbol()),this._activeGraphicEdit(this.originalFeature))},_activeGraphicEdit:function(a,b){b&&(b.id===this.originalJimuLayerInfo.id?this.originalFeature.setSymbol(null,!0):u.getInstance().clearSelection(b.layerObject));
var c;this._editWidget.editor._editVertices=!0;this._editWidget.editor._activateEditToolbar(a);a.geometry&&(c="point"===a.geometry.type?a.geometry:a.geometry.getExtent().getCenter());this._editWidget.map.infoWindow.show(c)},_onAddNewBtnClick:function(a){this.loading.show();this._addNewRelatedRecord(a).then(f.hitch(this,function(b){this.loading.hide();this._addOperation(h.OPERATION_SHOW_RELATED_RECORDS,a);this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,
b))}),f.hitch(this,function(){this.loading.hide()}))},_onDeleteBtnClick:function(a){this.loading.show();this._deleteRelatedRecord(a).then(f.hitch(this,function(){this.loading.hide();this._onPreviouBtnClick()}),f.hitch(this,function(){this.loading.hide()}))},_onAttributeChange:function(a,b){this.loading.show();this._updateRelatedRecord(a,b).then(f.hitch(this,function(){this.loading.hide()}),f.hitch(this,function(){this.loading.hide()}))},_createOperationData:function(a,b,c,e){return{feature:a,oriJimuLayerInfo:b,
destJimuLayerInfo:c,relatedFeature:e}},_addOperation:function(a,b){this.undoManager.add(new h.Operation(a,b,this))},_onPreviouBtnClick:function(){this.undoManager.undo()},_clearPage:function(){g.empty(this.contentBox);g.setStyle(this.addNewBtn,"display","none");l.forEach(this._temporaryData.eventHandles,function(a){a&&a.remove&&a.remove()},this);this._temporaryData.eventHandles=[];l.forEach(this._temporaryData.dijits,function(a){a&&a.destroy&&a.destroy()},this);this._temporaryData.dijits=[]},_changeRefDomNode:function(){g.setStyle(this.refDomNode,
"display","none");g.setStyle(this.operationBox,"display","block");g.addClass(this.domNode,"fix-height-mode");this.previouBtn.title=window.jimuNls.common.back;this.addNewBtn.title=window.jimuNls.common.newText;this.undoManager.peekUndo()?g.setStyle(this.previouBtn,"display","block"):g.setStyle(this.previouBtn,"display","none")},_revertRefDomNode:function(){g.setStyle(this.refDomNode,"display","block");g.setStyle(this.operationBox,"display","none");g.removeClass(this.domNode,"fix-height-mode")},_showAddNewBtn:function(a){var b=
a.destJimuLayerInfo.layerObject;"Table"===b.type&&b.getEditCapabilities&&b.getEditCapabilities().canCreate&&(g.setStyle(this.addNewBtn,"display","block"),a=m(this.addNewBtn,"click",f.hitch(this,this._onAddNewBtnClick,a)),this._temporaryData.eventHandles.push(a))},_setTitle:function(a,b){a&&g.create("div",{"class":"title-box "+(b?b:""),innerHTML:a},this.contentBox)},_setOperationTitle:function(a){g.setAttr(this.operationTitle,"innerHTML",a);g.setAttr(this.operationTitle,"title",a)},_showFieldSelector:function(a){var b=
"objecid",c=q(".title-box",this.contentBox)[0],e=a.layerObject,d=[];if(!c||!a)return b;var g=a.getPopupInfo();g&&g.title&&d.push({label:window.jimuNls.popup.saveAsPopupTitle,value:"popupTitle"});l.forEach(e.fields,function(a){"globalid"!==a.name.toLowerCase()&&"shape"!==a.name.toLowerCase()&&d.push({label:a.alias||a.name,value:a.name})});c=(new H({items:d})).placeAt(c);c.domNode.title=window.jimuNls.popup.chooseFieldTip;var h=f.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",
!1,e),k=p.ignoreCaseToGetFieldObject(a.layerObject,a.layerObject.displayField||a.layerObject.objectIdField),n=G.getInstance().getAppConfig();h?b=h:"2.3"===n.configWabVersion&&k&&k.name?b=k.name:g&&g.title?b="popupTitle":k&&k.name?b=k.name:0<d.length&&(b=d[0].value);b&&(c.setHighlightValue(b),f.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",b,e));this._temporaryData.dijits.push(c);a=m(c,"click-item",f.hitch(this,function(a,b){q(".item.record-item",this.contentBox).forEach(f.hitch(this,
function(c){f.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",b,e);var d=this._getDisplayTitleOfRelatedRecord(a,c.relatedRecord,b);c.innerHTML=d}))},a));this._temporaryData.eventHandles.push(a);return b}});h.Operation=n([z],{constructor:function(a,b,c){this.operationName=a;this.operationData=b;this.relatedRecordsEditor=c},performUndo:function(){switch(this.operationName){case h.OPERATION_SHOW_RELATED_TABLES:return this.relatedRecordsEditor.showRelatedTables(this.operationData);
case h.OPERATION_SHOW_RELATED_RECORDS:return this.relatedRecordsEditor.showRelatedRecords(this.operationData);case h.OPERATION_SHOW_INSPECTOR:return this.relatedRecordsEditor.showInspector(this.operationData);default:return this.relatedRecordsEditor.showFirstPage(this.operationData,!0)}}});h.ATI=n([D],{constructor:function(){this._aiConnects=[];this._selection=[];this._toolTips=[]}});f.mixin(h,{OPERATION_SHOW_RELATED_TABLES:"showRelatedTables",OPERATION_SHOW_RELATED_RECORDS:"showRelatedRecords",OPERATION_SHOW_INSPECTOR:"showInspector",
OPERATION_FIRST:"first"});return h});