// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/json ./constants ./geometry-utils ./labeling-utils ./mgrs ./NonPolarGridZone ./VisibleGridZone ./GridPolygon esri/geometry/geometryEngine esri/graphic esri/geometry/Point esri/geometry/Polyline esri/geometry/Polygon esri/symbols/SimpleLineSymbol esri/symbols/TextSymbol esri/symbols/Font esri/Color".split(" "),function(O,u,y,E,v,Q,R,S,I,F,J,M,P,G,K,H,L){return{_ZonesDictionary:function(){var a,d,b,g="CDEFGHJKLMNPQRSTUVWX".split(""),k={};for(a=1;60>=a;a++)for(d=0;d<g.length;d++){var h=
b=b=void 0,f=void 0,z=void 0,n=a+g[d];"32X"===n||"34X"===n||"36X"===n?b=null:("31V"===n?b={xmin:0,ymin:56,xmax:3,ymax:64,id:n}:"32V"===n?b={xmin:3,ymin:56,xmax:12,ymax:64,id:n}:"31X"===n?b={xmin:0,ymin:72,xmax:9,ymax:84,id:n}:"33X"===n?b={xmin:9,ymin:72,xmax:21,ymax:84,id:n}:"35X"===n?b={xmin:21,ymin:72,xmax:33,ymax:84,id:n}:"37X"===n?b={xmin:33,ymin:72,xmax:42,ymax:84,id:n}:(b=(a-1)*u.ZONE_WIDTH_DEGREES-180,h=a*u.ZONE_WIDTH_DEGREES-180,f=d*u.ZONE_HEIGHT_DEGREES+u.MIN_MGRS_LATITUDE,z=(d+1)*u.ZONE_HEIGHT_DEGREES+
u.MIN_MGRS_LATITUDE,b=180===b?u.POSITIVE_180:b,b=-180===b?u.NEGATIVE_180:b,h=180===h?u.POSITIVE_180:h,h=-180===h?u.NEGATIVE_180:h,80===z&&(z=u.MAX_MGRS_LATITUDE),b={xmin:b,ymin:f,xmax:h,ymax:z,id:n}),b=new Q(b));b&&(k[b.id]=b)}return k}(),getInterval:function(a,d,b){var g,k,h,f=0;g=d.getResolutionInMeters()*a;k=d.extent.getCenter();h=d.toMap(d.toScreen(k).offset(0,a/2));for(g=d.toMap(d.toScreen(k).offset(0,-a/2));84<=h.getLatitude()||84<=g.getLatitude();)f++,h=d.toMap(d.toScreen(k).offset(0,a/2+f*
a)),g=d.toMap(d.toScreen(k).offset(0,-a/2+f*a));for(;-80>=h.getLatitude()||-80>=g.getLatitude();)f++,h=d.toMap(d.toScreen(k).offset(0,a/2-f*a)),g=d.toMap(d.toScreen(k).offset(0,-a/2-f*a));a=h.getLatitude();d=h.getLongitude();h=g.getLatitude();f=g.getLongitude();g=v.getZoneNumber(a,d);g=Math.abs(v.LLtoUTM(a,d,g)[1]-v.LLtoUTM(h,f,g)[1]);a=Math.log10(g);switch(b){case "more":b=Math.floor(a);break;case "less":case "strict":b=Math.ceil(a);break;default:b=Math.round(a)}b=Math.pow(10,b);g>2*b&&(b*=10);return 1E5<
b?!1:b},zonesFromExtent:function(a){var d,b,g,k,h,f,z,n,m,v,p,e;b=a.map.extent;var r=b.spatialReference.isWebMercator()?u.WEBMERCATOR_360:u.GEOGRAPHIC_360,l={xOffset:a.getCornerLabelXOffset(),yOffset:a.getCornerLabelYOffset(),rotation:0,color:a.getColor(0),fontFamily:a.getFontFamily(),fontSize:a.getFontSize(0)},q="CDEFGHJKLMNPQRSTUVWX".split(""),t=[];if(b.xmax-b.xmin>r)return t;var r=y.extentToPolygon(b),r=y.toWebMercator(r),w=y.pointToGeographic(new J([b.xmin,b.ymin],b.spatialReference)),A=y.pointToGeographic(new J([b.xmax,
b.ymax],b.spatialReference));b=w.y;k=A.y;p=w.offsetX;e=A.offsetX;for(var x=p;x<=e;x++)for(d=x>p?u.NEGATIVE_180:w.x,g=x<e?u.POSITIVE_180:A.x,h=Math.min(Math.max(Math.floor((b+80)/u.ZONE_HEIGHT_DEGREES),0),19),f=Math.min(Math.floor((k+80)/u.ZONE_HEIGHT_DEGREES),19),d=Math.floor((d+180)/u.ZONE_WIDTH_DEGREES),g=Math.min(Math.floor((g+180)/u.ZONE_WIDTH_DEGREES)+2,60);d<=g;d++)for(var D=h;D<=f;D++)if(z=q[D],z=d+z,this._ZonesDictionary[z]){n=O.parse(O.stringify(this._ZonesDictionary[z]._rings));for(m=0;m<
n[0].length;m++)n[0][m][0]+=x*u.GEOGRAPHIC_360;m=new P({rings:n});v=new M({paths:n});if(n=I.intersect(y.toWebMercator(m),r))m=I.intersect(y.toWebMercator(v),r),t.push(new R({map:a.map,polyline:m,polygon:n,offset:x,nonPolarGridZone:this._ZonesDictionary[z],labelParameters:l}))}return t},processZonePolygons:function(a,d){for(var b={},g=d.getInterval(),k=0;k<a.length;k++){var h=a[k];h&&(this.handleZonePolygon(h,d),g&&(b[h.nonPolarGridZone.utmZone]?b[h.nonPolarGridZone.utmZone].polygon=I.union([y.toWebMercator(h.polygon),
b[h.nonPolarGridZone.utmZone].polygon]):b[h.nonPolarGridZone.utmZone]={polygon:y.toWebMercator(h.polygon),offset:h.offset}))}if(g)for(k=Object.keys(b),h=0;h<k.length;h++){var f=k[h],u=b[f].polygon,n=b[f].offset,m=y.toGeographic(u.getExtent()),C=v.LLtoUTM(m.ymin,m.xmin,f),p=v.LLtoUTM(m.ymin,m.xmax,f),e=v.LLtoUTM(m.ymax,m.xmax,f),m=v.LLtoUTM(m.ymax,m.xmin,f),f={minE:Math.min(C[0],p[0],e[0],m[0]),maxE:Math.max(C[0],p[0],e[0],m[0]),minN:Math.min(C[1],p[1],e[1],m[1]),maxN:Math.max(C[1],p[1],e[1],m[1]),
utmZone:f,polygon:u,offset:n,grid:d};this.handle100kGrids(f);1E5>g&&this.handleIntervals(f)}},handleZonePolygon:function(a,d){var b,g,k;b=a.polyline;g=d.getColor(0);k=d.getLineWidth(0);d._lineGraphics0.push(new F(b,new G(G.STYLE_SOLID,new L(g),k)));if(!(4>d.map.getZoom()))if(5>=d.map.getZoom())d._labelGraphics.push(a.getCenterLabel());else for(b=a.getLabels(),g=0;g<b.length;g++)d._labelGraphics.push(b[g])},handle100kGrids:function(a){var d=a.polygon,b=a.offset,g=a.utmZone,k=a.minE,h=a.maxE,f=a.minN,
z=a.maxN;a=a.grid;for(var n=a.getColor(1),m=a.getLineWidth(1),C=a.getMap(),p,e,r,l,q,f=1E5*Math.floor(f/1E5);f<z;f+=1E5)for(p=1E5*Math.floor(k/1E5);p<h;p+=1E5){q=v.findGridLetters(g,0>f+5E4?1E7+(f+5E4):f+5E4,p+5E4);r=[];for(e=p;e<=p+1E5;e+=1E4)l=v.UTMtoLL(f,e,g),r.push([l.lon,l.lat]);for(e=f;e<f+1E5;e+=1E4)l=v.UTMtoLL(e,p+1E5,g),r.push([l.lon,l.lat]);for(e=p+1E5;e>=p;e-=1E4)l=v.UTMtoLL(f+1E5,e,g),r.push([l.lon,l.lat]);for(e=f+1E5;e>=f;e-=1E4)l=v.UTMtoLL(e,p,g),r.push([l.lon,l.lat]);for(e=0;e<r.length;e++)r[e][0]+=
b*u.GEOGRAPHIC_360;r=new P([r]);e=y.polygonToPolyline(r);l=I.intersect(y.toWebMercator(r),y.toWebMercator(d));e=I.intersect(y.toWebMercator(e),y.toWebMercator(d));if(l&&(q={clippedPolygon:l,unclippedPolygon:r,map:C,xmin:p%1E6,ymin:f%1E6,xmax:(p+1E5)%1E6,ymax:(f+1E5)%1E6,minMaxType:"utm",utmZone:g,text:q,labelParameters:{xOffset:10,yOffset:10,rotation:0,color:a.getColor(1),fontFamily:a.getFontFamily(),fontSize:a.getFontSize(1)}},q=new S(q),!(7>a.map.getZoom())))for(q=9>C.getZoom()?[q.getCenterLabel(!0)]:
q.getLabels(),e&&a._lineGraphics1.push(new F(e,new G(G.STYLE_SOLID,new L(n),m))),e=0;e<q.length;e++)a._labelGraphics.push(q[e])}},handleIntervals:function(a){var d=a.polygon,b=a.utmZone,g=a.offset,k=a.minE,h=a.maxE,f=a.minN,z=a.maxN;a=a.grid;var n=a.getFontFamily(),m=a.getIntervalLabelXOffset(),C=a.getIntervalLabelYOffset(),p=a.getInterval(),e=a.getMap(),r=a.getVerticalLabels(),l,q,t,w,A,x,D,B,c,N;for(l=Math.floor(f/p)*p;l<=z;l+=p)if(0!==l%1E5){0===l%1E4?(t=2,w=a._lineGraphics2):0===l%1E3?(t=3,w=
a._lineGraphics3):0===l%100?(t=4,w=a._lineGraphics4):(t=5,w=a._lineGraphics5);A=a.getColor(t);x=a.getLineWidth(t);t=a.getFontSize(t);D=new H(t,H.STYLE_NORMAL,H.VARIANT_NORMAL,H.WEIGHT_BOLD,n);c=[];q=v.UTMtoLL(l,k,b);B=v.UTMtoLL(l,h,b);for(q=0;q<h;q+=1E4)N=v.UTMtoLL(l,k+q,b),c.push([N.lon,N.lat]);c.push([B.lon,B.lat]);for(q=0;q<c.length;q++)c[q][0]+=g*u.GEOGRAPHIC_360;if(B=I.intersect(y.toWebMercator(new M([c])),y.toWebMercator(d))){x=new F(B,new G(G.STYLE_SOLID,new L(A),x));w.push(x);w=E.padZero((0>
f?1E7+l:l)%1E5/p,5-Math.log10(p));c=B.paths[0];q=new J({x:c[0][0]+.001,y:c[0][1],spatialReference:B.spatialReference});B=new J({x:c[c.length-1][0]-.001,y:c[c.length-1][1],spatialReference:B.spatialReference});x=E.screenDistanceBetweenPoints(q,B,e).horizontal;c=E.distanceFromMapEdge(q,e).horizontal;if(2>c||200<c&&300<x)c=(new K(w)).setAngle(0).setColor(A).setOffset(m,-(t/1.333)/2).setAlign("start").setFont(D),c=new F(q,c),a._labelGraphics.push(c);c=E.distanceFromMapEdge(B,e).horizontal;if(2>c||200<
c&&300<x)c=(new K(w)).setAngle(0).setColor(A).setOffset(-m,-(t/1.333)/2).setAlign("end").setFont(D),c=new F(B,c),a._labelGraphics.push(c)}}for(k=Math.floor(k/p)*p;k<=h;k+=p)if(0!==k%1E5){0===k%1E4?(t=2,w=a._lineGraphics2):0===k%1E3?(t=3,w=a._lineGraphics3):0===k%100?(t=4,w=a._lineGraphics4):(t=5,w=a._lineGraphics5);A=a.getColor(t);x=a.getLineWidth(t);t=a.getFontSize(t);D=new H(t,H.STYLE_NORMAL,H.VARIANT_NORMAL,H.WEIGHT_BOLD,n);c=[];l=v.UTMtoLL(f-1E4,k,b);m=v.UTMtoLL(z+1E4,k,b);c.push([l.lon,l.lat]);
c.push([m.lon,m.lat]);for(q=0;q<c.length;q++)c[q][0]+=g*u.GEOGRAPHIC_360;if(m=I.intersect(y.toWebMercator(new M([c])),y.toWebMercator(d))){l=new F(m,new G(G.STYLE_SOLID,new L(A),x));w.push(l);w=E.padZero(k%1E5/p,5-Math.log10(p));c=m.paths[0];l=new J({x:c[0][0],y:c[0][1]+.001,spatialReference:{wkid:102100}});m=new J({x:c[c.length-1][0],y:c[c.length-1][1]-.001,spatialReference:{wkid:102100}});x=E.screenDistanceBetweenPoints(l,m,e).vertical;c=E.distanceFromMapEdge(l,e).vertical;if(2>c||200<c&&300<x)c=
(new K(w)).setAngle(r?90:0).setColor(A).setOffset(r?-(t/1.333)/2:0,C).setAlign(r?"end":"middle").setFont(D),c=new F(l,c),a._labelGraphics.push(c);c=E.distanceFromMapEdge(m,e).vertical;if(2>c||200<c&&300<x)c=(new K(w)).setAngle(r?90:0).setColor(A).setOffset(r?-(t/1.333)/2:0,r?-C:-C-t/1.333).setAlign(r?"start":"middle").setFont(D),c=new F(m,c),a._labelGraphics.push(c)}}}}});