// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Screening/setting/nls/strings":{units:{standardUnit:"Standard\u00fchik",metricUnit:"Meeterm\u00f5\u00f5dustiku \u00fchik"},analysisTab:{analysisTabLabel:"Anal\u00fc\u00fcs",selectAnalysisLayerLabel:"Vali anal\u00fc\u00fcsi kihid",addLayerLabel:"Lisa kihid",noValidLayersForAnalysis:"Valitud veebikaardilt ei leitud kehtivaid kihte.",noValidFieldsForAnalysis:"Valitud veebikaardilt ei leitud kehtivaid v\u00e4lju. Eemaldage valitud kiht.",addLayersHintText:"Vihje: aruandes anal\u00fc\u00fcsimiseks ja kuvamiseks valitud kihid ja v\u00e4ljad",
addLayerNameTitle:"Kihi nimi",addFieldsLabel:"Lisa v\u00e4li",addFieldsPopupTitle:"Vali v\u00e4ljad",addFieldsNameTitle:"V\u00e4ljanimed",aoiToolsLegendLabel:"AOI t\u00f6\u00f6vahendid",aoiToolsDescriptionLabel:"Lubab t\u00f6\u00f6vahendid huvipakkuvate alade loomiseks ja nende m\u00e4rgiste m\u00e4\u00e4ramiseks",placenameLabel:"Koha nimi",drawToolsLabel:"Joonistamise t\u00f6\u00f6vahendid",uploadShapeFileLabel:"Shape-faili \u00fcleslaadimine",coordinatesLabel:"Koordinaadid",coordinatesDrpDwnHintText:"Vihje: valige \u00fchik sisestatud l\u00e4bimiste kuvamiseks",
coordinatesBearingDrpDwnHintText:"Vihje: valige kurss sisestatud l\u00e4bimiste kuvamiseks",allowShapefilesUploadLabel:"Luba Shape-failide \u00fcleslaadimine anal\u00fc\u00fcsiks",areaUnitsLabel:"N\u00e4ita pindalasid/pikkusi j\u00e4rgmiselt",allowShapefilesUploadLabelHintText:"Vihje: kuvab vahekaardil Aruanne s\u00e4tet \u201eLae Shape-fail \u00fcles anal\u00fc\u00fcsiks\u201d",maxFeatureForAnalysisLabel:"Max objektid anal\u00fc\u00fcsiks",maxFeatureForAnalysisHintText:"Vihje: m\u00e4\u00e4rake maksimaalne objektide arv anal\u00fc\u00fcsiks",
searchToleranceLabelText:"Otsingu tolerants (jalgades)",searchToleranceHint:"Vihje: otsingu tolerantsi kasutatakse ainult punktide ja joonte sisendi anal\u00fc\u00fcsimiseks",placenameButtonText:"Koha nimi",drawToolsButtonText:"Joonista",shapefileButtonText:"Shape fail",coordinatesButtonText:"Koordinaadid"},downloadTab:{downloadLegend:"Allalaadimiss\u00e4tted",reportLegend:"Aruande s\u00e4tted",downloadTabLabel:"Allalaadimine",syncEnableOptionLabel:"Objektikihid",syncEnableOptionHint:"Vihje: kasutatakse huvialaga l\u00f5ikuvate objektide info allalaadimiseks m\u00e4rgitud vormingutes.",
syncEnableOptionNote:"M\u00e4rkus: suvandid Faili geoandmebaas n\u00f5uab lubatud s\u00fcnkroonimisega objektiteenuseid.",extractDataTaskOptionLabel:"Andmete v\u00e4ljav\u00f5tte toiminguga geot\u00f6\u00f6tlusteenus",extractDataTaskOptionHint:"Vihje: kasutage avaldatud andmete v\u00e4ljav\u00f5tte toiminguga geot\u00f6\u00f6tlusteenust huvialaga l\u00f5ikuvate objektide allalaadimiseks Faili geoandmebaasi v\u00f5i Shape-faili vormingus.",cannotDownloadOptionLabel:"Keela allalaadimine",syncEnableTableHeaderTitle:{layerNameLabel:"Kihi nimi",
csvFileFormatLabel:"CSV",fileGDBFormatLabel:"Faili geoandmebaas",allowDownloadLabel:"Luba allalaadimine"},setButtonLabel:"M\u00e4\u00e4ra",GPTaskLabel:"M\u00e4\u00e4rake geot\u00f6\u00f6tlusteenuse URL",printGPServiceLabel:"Printimise teenuse URL",setGPTaskTitle:"M\u00e4\u00e4rake n\u00f5utud geot\u00f6\u00f6tlusteenuse URL",logoLabel:"Logo",logoChooserHint:"Vihje: kl\u00f5psake pildi muutmiseks pildi ikooni",footnoteLabel:"Joonealune m\u00e4rkus",columnTitleColorPickerLabel:"Tulpade pealkirjade v\u00e4rv",
reportTitleLabel:"Aruande pealkiri",errorMessages:{invalidGPTaskURL:"Vale geot\u00f6\u00f6tlusteenus. Valige geot\u00f6\u00f6tlusteenus, mis sisaldab andmete v\u00e4ljav\u00f5tte toimingut.",noExtractDataTaskURL:"Valige m\u00f5ni geot\u00f6\u00f6tlusteenus, mis sisaldab andmete v\u00e4ljav\u00f5tte toimingut."}},generalTab:{generalTabLabel:"\u00dcldine",tabLabelsLegend:"Paneeli m\u00e4rgised",tabLabelsHint:"Vihje: m\u00e4\u00e4rake m\u00e4rgised",AOITabLabel:"Huviala paneel",ReportTabLabel:"Aruande paneel",
bufferSettingsLegend:"Puhvri seaded",defaultBufferDistanceLabel:"Puhvri vaikeulatus",defaultBufferUnitsLabel:"Puhvri \u00fchikud",generalBufferSymbologyHint:"Vihje: m\u00e4\u00e4rake s\u00fcmboloogia puhvrite kuvamiseks m\u00e4\u00e4ratletud huvialade \u00fcmber",aoiGraphicsSymbologyLegend:"AOI graafika s\u00fcmboloogia",aoiGraphicsSymbologyHint:"Vihje: m\u00e4\u00e4rake s\u00fcmboloogia punkt-, joon- ja pol\u00fcgoonhuvialade m\u00e4\u00e4ratlemiseks",pointSymbologyLabel:"Punkt",previewLabel:"Eelvaade",
lineSymbologyLabel:"Joon",polygonSymbologyLabel:"Pol\u00fcgoon",aoiBufferSymbologyLabel:"Puhvri s\u00fcmboloogia",pointSymbolChooserPopupTitle:"Aadressi v\u00f5i asukoha s\u00fcmbol",polygonSymbolChooserPopupTitle:"Vali pol\u00fcgooni esilet\u00f5stmiseks s\u00fcmbol",lineSymbolChooserPopupTitle:"Vali joone esilet\u00f5stmiseks s\u00fcmbol",aoiSymbolChooserPopupTitle:"M\u00e4\u00e4ra puhvri s\u00fcmbol",aoiTabText:"AOI",reportTabText:"Aruanne"},searchSourceSetting:{searchSourceSettingTabTitle:"Otsinguallika seaded",
searchSourceSettingTitle:"Otsinguallika seaded",searchSourceSettingTitleHintText:"Lisa ja seadista geokodeerimise teenuseid v\u00f5i objektikihte otsinguallikatena. Need allikad m\u00e4\u00e4ravad, mis info on leitav otsingukasti kaudu",addSearchSourceLabel:"Lisa otsinguallikas",featureLayerLabel:"Objektikiht",geocoderLabel:"Geokodeerija",generalSettingLabel:"\u00dcldseade",allPlaceholderLabel:"Kohat\u00e4ite tekst k\u00f5igi otsimiseks:",allPlaceholderHintText:"Vihje: k\u00f5igi kihtide ja geokodeerija otsimiseks sisestage tekst kohat\u00e4itena kuvatavana",
generalSettingCheckboxLabel:"Kuva leitud objekti v\u00f5i asukoha h\u00fcpikaken",countryCode:"Riigi v\u00f5i piirkonna kood(id)",countryCodeEg:"nt ",countryCodeHint:"Kui j\u00e4tate selle v\u00e4lja t\u00fchjaks, teostatakse otsing k\u00f5ikides riikides ja piirkondades",questionMark:"?",searchInCurrentMapExtent:"Otsi ainult praegusest kaardiulatusest",zoomScale:"Suumiskaala",locatorUrl:"Geokodeerija URL",locatorName:"Geokodeerija nimi",locatorExample:"N\u00e4ide",locatorWarning:"Seda geokodeerimisteenuse versiooni ei toetata. Vidin toetab geokodeerimisteenust alates versioonist 10.0 ja uuemates versioonides.",
locatorTips:"Soovitused pole saadaval, sest geokodeerimisteenus ei toeta soovituste v\u00f5imalust.",layerSource:"Kihi allikas",setLayerSource:"M\u00e4\u00e4ra kihi allikas",setGeocoderURL:"M\u00e4\u00e4ra geokodeerija URL",searchLayerTips:"Soovitused pole saadaval, sest objektiteenus ei toeta lehek\u00fcljelise jaotuse v\u00f5imalust.",placeholder:"Kohat\u00e4itja tekst",searchFields:"Otsinguv\u00e4ljad",displayField:"Kuvamise v\u00e4li",exactMatch:"T\u00e4pne vaste",maxSuggestions:"Maksimaalsed soovitused",
maxResults:"Maksimaalsed tulemused",enableLocalSearch:"Luba kohalik otsing",minScale:"Min m\u00f5\u00f5tkava",minScaleHint:"Kui kaardi m\u00f5\u00f5kava on sellest m\u00f5\u00f5tkavast suurem, rakendatakse kohalik otsing",radius:"Raadius",radiusHint:"M\u00e4\u00e4rab praeguse kaardi keskpunkti \u00fcmber asuva ala raadiuse, mida kasutatakse geokodeerimise kandidaatide j\u00e4rjestuse v\u00f5imendamiseks nii, et asukohale l\u00e4himad kandidaadid tagastatakse esimesena",setSearchFields:"M\u00e4\u00e4ra otsinguv\u00e4ljad",
set:"M\u00e4\u00e4ra",invalidUrlTip:"URL ${URL} ei sobi v\u00f5i pole k\u00e4ttesaadav.",invalidSearchSources:"Otsinguallika sobimatud seaded"},errorMsg:{textboxFieldsEmptyErrorMsg:"T\u00e4itke n\u00f5utavad v\u00e4ljad",bufferDistanceFieldsErrorMsg:"Sisestage kehtivad v\u00e4\u00e4rtused",invalidSearchToleranceErrorMsg:"Sisestage otsingu tolerantsi jaoks kehtiv v\u00e4\u00e4rtus",atLeastOneCheckboxCheckedErrorMsg:"Vigane konfiguratsioon",noLayerAvailableErrorMsg:"\u00dchtegi kihti pole saadaval",
layerNotSupportedErrorMsg:"Ei ole toetatud ",noFieldSelected:"Kasutage anal\u00fc\u00fcsiks v\u00e4ljade valimiseks muutmise toimingut.",duplicateFieldsLabels:'Duplikaatm\u00e4rgis "${labelText}" lisatud : "${itemNames}"',noLayerSelected:"Valige anal\u00fc\u00fcsiks v\u00e4hemalt \u00fcks kiht",errorInSelectingLayer:"Kihi valimise toimingut ei saa l\u00f5pule viia. Proovige uuesti.",errorInMaxFeatureCount:"Sisestage anal\u00fc\u00fcsiks kehtiv max objektide arv."},_localized:{}}});