// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dijit/_WidgetBase dojo/_base/lang dojo/dom-style dojo/dom-geometry dojo/Evented libs/echarts/echarts jimu/utils ./_chartUtils ./_Gauge libs/echarts/light libs/echarts/dark".split(" "),function(l,n,g,k,p,q,r,e,f,t){return l([n,q],{baseClass:"jimu-dijit-chart",templateString:"\x3cdiv\x3e\x3c/div\x3e",declaredClass:"jimu.dijit.chart",config:null,validConfig:{type:"column bar line pie radar funnel gauge".split(" "),common:"type title labels legend confine toolbox color theme backgroundColor scale dataZoom events series advanceOption".split(" "),
axisChart:["stack","axisPointer","hidexAxis","hideyAxis"],pie:["innerRadius","labelLine"],funnel:["min","max","funnelSort"],gauge:["shape","min","max","gaugeOption"],radar:["radarShape","indicator"]},defaultConfiguration:{series:{pieSeries:[{type:"pie",radius:[0,"70%"],labelLine:{normal:{show:!0,length:5,length2:5}},data:[]}],funnelSeries:[{type:"funnel",minSize:"0%",maxSize:"100%",sort:"descending",data:[]}]},toolboxs:{dataView:{title:"Data view",readOnly:!1},magicType:{title:{line:"switch to line",
bar:"switch to bar",stack:"switch to stack",tiled:"switch to tiled"},type:["line","bar","stack","tiled"]},restore:{title:"restore"},saveAsImage:{title:"save as image"}}},postCreate:function(){this.inherited(arguments);if(this.chartDom){var a=p.getMarginBox(this.chartDom);0===a.w&&(a.w=10);0===a.h&&(a.h=10);k.set(this.domNode,{width:a.w+"px",height:a.h+"px"})}else console.warn("No valid chart dom!"),k.set(this.domNode,{width:"10px",height:"10px"});this.gauge=new t;this.chart=r.init(this.domNode,this.config.theme||
"light");this.gauge.setChart(this.chart);this.setConfig()},updateConfig:function(a){return e.isNotEmptyObject(a)?(g.mixin(this.config,a),a=this._chartFactory(this.config),this.chart.setOption(a),this.config.shape&&"curved"!==this.config.shape&&this.gauge._resetGraphic(this.config),!0):!1},setConfig:function(a){e.isNotEmptyObject(a)?this.config=a:this.config=this.config||{};if(!this._checkConfig(this.config))return!1;this._customTheme();this.clear();this.chart.setOption(this._chartFactory(this.config));
this._resize();return!0},_showInitChart:function(a){var b;b="column"===a.type||"horizontal"===a.shape||"vertical"===a.shape?"bar":a.type;var c={series:[{data:[{name:"0",value:0}]}]};f.isAxisChart(a)&&(c.xAxis={data:["0"]},c.yAxis={});c.series[0].type=b;this.chart.setOption(c,!1)},_mockChartDataWhenNoData:function(a){a&&Array.isArray(a.labels)&&0===a.labels.length&&(a.labels.push(0),a&&Array.isArray(a.series)&&0<a.series.length&&a.series.forEach(function(a){a&&Array.isArray(a.data)&&0===a.data.length&&
a.data.push(0)}));return a},_chartFactory:function(a){a=this._mockChartDataWhenNoData(a);var b=this.chart.getWidth();a=g.clone(a);var c=g.clone(this.defaultConfiguration),d=this.option={},d=this._settingDefaultGrid(d,a),d=this._settingRenderOption(d,a),d=this._settingTitle(d,a),d=this._settingBackgroundColor(d,a),d=this._settingColor(d,a),d=this._settingToolTip(d,a);f.isAxisChart(a)?(d=this._settingAxisChartAxis(d,a),d=this._settingToolBox(d,a,c),d=this._settingSeries(d,a),d=this._settingStack(d,
a),d=this._settingAxisDisplay(d,a)):f.isAxisChart(a)||(d=this._settingToolBox(d,a,c,"magicType"),d=this._settingNoAxisCharts(d,a,c));d=this._settingLegend(d,a);d=this._settingScale(d,a);d=this._handleChartRtl(d,a);d=this._avoidTitleToolBoxOverlap(d,a);d=this._pieChartAvoidLegendLabelOverLap(d,a);d=this._settingFixedPosition(d,a,b);d=this._settingAdvanceOption(d,a);d=this._avoidAdjoiningColorSameForPie(d,a);this._bindEvents(a);return d},_avoidAdjoiningColorSameForPie:function(a,b){if("pie"!==b.type||
!a.color||2>=a.color.length)return a;e.isNotEmptyObject(a.series,!0)&&a.series.forEach(g.hitch(this,function(b){var c=b.data.length;0===(c-1)%a.color.length&&(b=b.data[c-1],b.itemStyle||(b.itemStyle={}),b.itemStyle.normal||(b.itemStyle.normal={}),b.itemStyle.normal.color||(b.itemStyle.normal.color=a.color[1]))}));return a},_pieChartAvoidLegendLabelOverLap:function(a,b){if("pie"!==b.type)return a;var c=b.labelLine?.75:.85;b.legend&&(c-=.12);a.series[0].radius[1]=100*c+"%";return a},_settingDefaultGrid:function(a,
b){f.isAxisChart(b)&&(a.grid={top:20,bottom:10,left:10,right:10,containLabel:!0});return a},_settingRenderOption:function(a,b){if("curved"===b.shape)return a.animationThreshold=99999999,a.hoverLayerThreshold=99999,a.progressiveThreshold=99999,a;a.hoverLayerThreshold=500;a.progressiveThreshold=500;a.progressive=100;a.animationThreshold=500;return a},clear:function(){this.chart.clear()},resize:function(a,b){k.set(this.domNode,{width:a||"100%",height:b||"100%"});this.chart.resize();this._resize()},_resize:function(){this.config.shape&&
"curved"!==this.config.shape&&(this.gauge._resetGrid(this.config),this.gauge._resetGraphic(this.config))},_settingFixedPosition:function(a,b,c){b.shape||this._showInitChart(b);f.isAxisChart(b)&&(a=this._settingDataZoom(a,b,c),a=this._settingGrid(a,b));return a},destroy:function(){this.chart.clear();e.isNotEmptyObject(this.config.events)&&this.config.events.forEach(g.hitch(this,function(a){this.chart.off(a.name)}));this.inherited(arguments)},_settingAxisDisplay:function(a,b){if(!f.isAxisChart(b))return a;
a.xAxis.show=!b.hidexAxis;a.yAxis.show=!b.hideyAxis;a.grid.containLabel=!b.hideyAxis;return a},_handleChartRtl:function(a,b){if(!window.isRTL)return a;if(f.isAxisChart(b)||"vertical"===b.shape||"horizontal"===b.shape)a.xAxis.inverse=!0,a.yAxis.position="right";return a},_settingTitle:function(a,b){b.title&&(a.title={textStyle:{fontSize:16}},a.title.text=b.title);return a},_settingColor:function(a,b){e.isNotEmptyObject(b.color)&&(a.color=b.color);return a},_settingBackgroundColor:function(a,b){b.backgroundColor&&
(a.backgroundColor=b.backgroundColor);return a},_settingToolTip:function(a,b){a.tooltip={};if(b.axisPointer){if(a.tooltip.trigger="axis","column"===b.type||"bar"===b.type)a.tooltip.axisPointer={type:"shadow"}}else a.tooltip.axisPointer={type:""};return a},_settingAxisChartAxis:function(a,b){a.xAxis={};a.yAxis={};"column"===b.type||"line"===b.type&&b.labels?(a.xAxis.data=b.labels,a.xAxis.type="category"):"bar"===b.type&&b.labels&&(a.yAxis.data=b.labels,a.yAxis.type="category");return a},_settingToolBox:function(a,
b,c,d){a.toolbox={};d||(d="");e.isNotEmptyObject(b.toolbox)&&(a.toolbox.feature={},b.toolbox.forEach(function(e){e!==d&&(b.stack&&(c.toolboxs.magicType.type=["line","bar","stack","tiled"]),a.toolbox.feature[e]=c.toolboxs[e])}));return a=this._handleToolBoxRTL(a,b)},_settingSeries:function(a,b){if(e.isNotEmptyObject(b.series))e.isNotEmptyObject(a.series)||(a.series=b.series);else return console.log("No series!"),a;b.series.forEach(g.hitch(this,function(c,d){var e="",e=c.type?c.type:b.type;c.data=c.data.map(g.hitch(this,
function(a,c){this._handleChartBorderWidth(a);if(f.isAxisChart(b))return a;var d={};a||"number"===typeof a?(d.value=a.value?a.value:a,a.itemStyle&&(d.itemStyle=a.itemStyle)):d.value=a;d.name=b.labels[c]||"";return d}));a.series[d].name=c.name||"";a.series[d].type="column"===e?"bar":e;a.series[d].data=c.data}));return a},_settingNoAxisCharts:function(a,b,c){if("pie"===b.type)a=this._settingPie(a,b,c);else if("funnel"===b.type)a=this._settingFunnel(a,b,c);else if("radar"===b.type)a=this._settingRadar(a,
b);else if("gauge"===b.type)return this.gauge._settingGaugeSeries(a,b);return this._settingSeries(a,b)},_settingScale:function(a,b){if(!b.scale)return a;"bar"===b.type?a.xAxis.scale=!0:"line"===b.type||"column"===b.type?a.yAxis.scale=!0:"radar"===b.type&&(a.radar.scale=!0);return a},_settingAdvanceOption:function(a,b){b.advanceOption&&("object"===typeof b.advanceOption?g.mixin(a,b.advanceOption):"function"===typeof b.advanceOption&&b.advanceOption(a));return a},_bindEvents:function(a){e.isNotEmptyObject(a.events)&&
a.events.forEach(g.hitch(this,function(a){this.chart.on(a.name,a.callback)}))},_settingLegend:function(a,b){if(!b.legend)return a;a.legend={type:"scroll",orient:"horizontal",x:"left",pageButtonPosition:"end",pageTextStyle:{color:"#939393"},bottom:20,y:"bottom",data:[]};f.isAxisChart(b)||"gauge"===b.type?a.series.forEach(function(b){a.legend.data.push(b.name)}):"pie"!==b.type&&"funnel"!==b.type&&"radar"!==b.type||a.series[0].data.forEach(function(b){a.legend.data.push(b.name)});return a=this._handleLegendRTL(a,
b)},_handleDataZoomStyle:function(a,b){b.showDataShadow=!1;b.realtime=!1;b.bottom=a.legend?30:"auto";"bar"===a.type&&a.legend&&(b.bottom=50);return b},_showDataZoom:function(a,b,c){c=c||this.chart.getWidth();var d=b.series[0].data.length*b.series.length,e=f.getAxisZeroPosition.call(this,b);c="bar"!==b.type?window.isRTL?e.left:c-e.left-a.grid.right:e.top;this.showDataZoom=8>c/d;var h=c/(8*d),h=parseFloat(100*h,10).toFixed(3),h=100<h?100:h,h=0===h?.1:h;c=[];var m="bar"===b.type?"xAxis":"yAxis",k="bar"===
b.type?"yAxisIndex":"xAxisIndex",l="bar"===b.type?"width":"height";a=this._initAxisOfDataZoom(a,m);c=b.dataZoom.map(g.hitch(this,function(a){a={type:a,start:0,show:this.showDataZoom};a[k]=[0];a[l]=15;a.end=h;"xAxis"===m&&window.isRTL&&(a.left="10");return a=this._handleDataZoomStyle(b,a)}));a.dataZoom=c;return a},_settingDataZoom:function(a,b,c){if(!e.isNotEmptyObject(b.dataZoom))return{dataZoom:[]};b.dataZoom?a=this._showDataZoom(a,b,c):(this.showDataZoom=!1,a.dataZoom=[]);return a},_avoidTitleToolBoxOverlap:function(a,
b){if("gauge"===b.type)return a;var c=10;b.title&&(c+=20);e.isNotEmptyObject(b.toolbox,!0)&&(c+=20);e.isNotEmptyObject(b.toolbox,!0)&&b.title&&(a.toolbox.top=20);f.isAxisChart(b)&&a.grid&&(a.grid.top=c);return a},_settingGrid:function(a,b){if(!f.isAxisChart(b))return a;var c=10;b.title&&(c+=20);e.isNotEmptyObject(b.toolbox,!0)&&(c+=20);e.isNotEmptyObject(b.toolbox,!0)&&b.title&&(a.toolbox.top=20);a.grid&&(a.grid.top=c);var c=10,d=43;b.hideyAxis&&(c=20,d=63);var g=0,h=10;b.legend&&(g=this.showDataZoom?
10:20,h+=20);"line"===b.type&&b.legend&&!this.showDataZoom&&(c+=7);"bar"===b.type?(window.isRTL?a.grid.left=this.showDataZoom?30:10:a.grid.right=this.showDataZoom?30:10,b.hideyAxis&&b.legend&&(h+=20),a.grid.bottom=h):a.grid.bottom=this.showDataZoom?d+g:c+g;return a},_handleLegendRTL:function(a,b){if(!b.legend)return a;var c={};window.isRTL?(c.x="right",c.pageButtonPosition="start"):(c.x="left",c.pageButtonPosition="end");a.legend=g.mixin(a.legend,c);return a},_handleToolBoxRTL:function(a,b){if(!b.toolbox)return a;
var c={top:0};window.isRTL?c.right=0:c.left=0;a.toolbox=g.mixin(a.toolbox,c);return a},_initAxisOfDataZoom:function(a,b){a[b].type="value";a.xAxis.splitLine={show:!0,lineStyle:{type:"dashed"}};a.yAxis.splitLine={show:!0,lineStyle:{type:"dashed"}};return a},_settingStack:function(a,b){if(!f.isAxisChart(b))return a;a.series=a.series.map(function(a){b.stack&&(a.stack="stack","line"===b.type&&(a.areaStyle={normal:{}},a.smooth=!0));return a});return a},_settingPie:function(a,b,c){if("pie"!==b.type)return a;
a.series=c.series.pieSeries;b.innerRadius&&(a.series[0].radius[0]=b.innerRadius);a.series[0].labelLine.normal.show="undefined"===typeof b.labelLine?!0:b.labelLine;return a},_settingFunnel:function(a,b,c){if("funnel"!==b.type)return a;a.series=c.series.funnelSeries;e.isNotEmptyObject(b.funnel)&&(a.series[0].min=b.min||0,a.series[0].max=b.max||100,a.series[0].sort=b.funnelSort||"descending");return a},_settingRadar:function(a,b){if("radar"!==b.type)return a;a.radar={nameGap:6,radius:"70%"};b.radarShape&&
(a.radar.shape=b.radarShape);b.indicator?a.radar.indicator=b.indicator:console.error("No radar indicator");a.series=[{}];a.series[0].label={normal:{show:!0,formatter:function(a){return f.tryLocaleNumber(a.value)}}};var c=[];b.series[0].data.forEach(function(a,e){c[e]={tooltip:"\x3cspan\x3e"+b.labels[e]+"\x3c/span\x3e"};a.forEach(function(a,d){c[e].tooltip+="\x3cbr/\x3e\x3cspan\x3e"+b.indicator[d].name+"\x3c/span\x3e : \x3cspan\x3e"+a+"\x3c/span\x3e"})});a.tooltip={trigger:"item",formatter:function(a){return'\x3cspan class\x3d"colorEl marginRight5" style\x3d"background-color:'+
e.encodeHTML(a.color)+'"\x3e\x3c/span\x3e'+c[a.dataIndex].tooltip}};this.config.confine&&(a.tooltipconfine=!0);return a},_handleChartBorderWidth:function(a){var b=!1;a&&a.itemStyle&&a.itemStyle.normal&&"undefined"!==typeof a.itemStyle.normal.borderColor&&(b=!0);e.isNotEmptyObject(this.chart._theme)||(this.chart._theme={});a=this.chart._theme;var c=0;b&&(c=.3);a.bar&&a.bar.itemStyle&&(a.bar.itemStyle.normal&&(a.bar.itemStyle.normal.barBorderWidth=c),a.bar.itemStyle.emphasis&&(a.bar.itemStyle.emphasis.barBorderWidth=
c));a.pie&&a.pie.itemStyle&&(a.pie.itemStyle.normal&&(a.pie.itemStyle.normal.borderWidth=c),a.pie.itemStyle.emphasis&&(a.pie.itemStyle.emphasis.borderWidth=c))},_customTheme:function(){e.isNotEmptyObject(this.chart._theme)||(this.chart._theme={});e.isNotEmptyObject(this.config.color)&&(this.chart._theme.color=this.config.color);e.isNotEmptyObject(this.chart._theme.tooltip)||(this.chart._theme.tooltip={});this.config.confine&&(this.chart._theme.tooltip.confine=!0);this.chart._theme.tooltip.axisPointer=
{type:"cross",label:{show:!0,precision:2,formatter:function(a){return"number"===typeof a.value?(a=parseFloat(a.value).toFixed(2),f.tryLocaleNumber(a)):a.value}},lineStyle:{color:"#27727B",type:"dashed"},crossStyle:{color:"#27727B"},shadowStyle:{color:"rgba(200,200,200,0.3)"}};this.chart._theme.tooltip.formatter=function(a){return f.handleToolTip(a,null,!0)}.bind(this);e.isNotEmptyObject(this.chart._theme.valueAxis)||(this.chart._theme.valueAxis={});e.isNotEmptyObject(this.chart._theme.valueAxis.axisLabel)||
(this.chart._theme.valueAxis.axisLabel={});this.chart._theme.valueAxis.axisLabel.formatter=function(a){return e.localizeNumber(a)}},_checkConfig:function(a){var b=!0;e.isNotEmptyObject(a)||(console.error("Empty config"),b=!1);if(!a.type||0>this.validConfig.type.indexOf(a.type))console.error("Invaild chart type!"),b=!1;var c=g.clone(this.validConfig),d=c.common,f=[],f="column"===a.type||"bar"===a.type||"line"===a.type?d.concat(c.axisChart):d.concat(c[a.type]);Object.keys(a).forEach(function(a){0>f.indexOf(a)&&
(b=!1,console.error("Invalid configuration parameter: "+a))});return b}})});