// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/Evented dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/_base/lang dojo/_base/html dojo/on dojo/_base/Color dojo/query jimu/dijit/ColorChooser jimu/dijit/ColorPicker jimu/dijit/ColorRecords dijit/popup jimu/utils dijit/a11yclick".split(" "),function(g,h,k,l,m,d,c,e,b,n,p,q,r,t,u,v){return h([k,m,l,g],{templateString:"\x3cdiv\x3e\x3c/div\x3e",baseClass:"jimu-color-palette",declaredClass:"jimu.dijit.ColorPalette",_TRANSPARENT_STR:"rgba(0, 0, 0, 0)",
value:"",_defaultAppearance:{showTransparent:!0,showColorPalette:!0,showColorPickerOK:!1,showCoustom:!0,showCoustomRecord:!0},recordUID:"",postMixInProperties:function(){this.nls=window.jimuNls.colorPalette},postCreate:function(){this.inherited(arguments);this.value=this.value?new b(this.value):new b("#fff");this._createContent()},_createContent:function(){this.appearance=d.mixin(this._defaultAppearance,this.appearance);var a=c.create("div",{"class":"jimu-colorpalette"},this.domNode);this.appearance.showTransparent&&
this._createSpecialColors(a);this.appearance.showColorPalette&&this._createColorChooser(a);this.appearance.showCoustom&&this._createJimuColorPicker(a);this.appearance.showCoustom&&this.appearance.showCoustomRecord&&this._createCoustomRecord(a)},setColor:function(a){this._isColorEqual(a)||(this.value=new b(a),this._setSpatialColor(this.value),"undefined"!==typeof this.value.a&&0===this.value.a?(this.colorChooser.setColor(new b("transparent"),!1),this.picker.setColor(new b("#fff"),!1)):(this.colorChooser.setColor(this.value.toHex(),
!1),this.picker.setColor(this.value,!1)),this.colorRecords&&this.colorRecords.selecteColor(this.value))},getColor:function(){return this.value},changeColor:function(){if("undefined"!==typeof this.value.a&&0===this.value.a)this.onChange(this.value);else this.onChange(this.value.toHex())},refreshRecords:function(){this.colorRecords&&this.colorRecords.refresh()},destroy:function(){t.close(this.tooltipDialog);this.picker.destroy();this.inherited(arguments)},_createSpecialColors:function(a){a=c.create("div",
{"class":"special-color"},a);this.transparentBtn=c.create("div",{"class":"transparent btn",innerHTML:'\x3cdiv class\x3d"btn-wapper"\x3e\x3cdiv class\x3d"transparent icon jimu-float-leading"\x3e\x3c/div\x3e\x3cdiv class\x3d"transparent text jimu-float-leading"\x3e'+this.nls.transparent+"\x3c/div\x3e\x3c/div\x3e"},a);this.own(e(this.transparentBtn,v,d.hitch(this,this._onTransparentClick)))},_onTransparentClick:function(){this.setColor(new b("transparent"));this.changeColor()},_setSpatialColor:function(a){if(this.transparentBtn){var f=
n(".btn-wapper",this.transparentBtn)[0];c.removeClass(f,"selected");a&&a.toString&&a.toString()===this._TRANSPARENT_STR&&c.addClass(f,"selected")}},_createColorChooser:function(a){this.colorChooser=new p({});this.colorChooser.placeAt(a);this.own(e(this.colorChooser,"change",d.hitch(this,function(a){a=new b(a);this.setColor(a);this.changeColor()})))},_createJimuColorPicker:function(a){this.coustomtBtn=c.create("div",{"class":"coustom btn"},a);a='\x3cdiv class\x3d"btn-wapper"\x3e\x3cdiv class\x3d"custom icon jimu-float-leading"\x3e\x3c/div\x3e\x3cdiv class\x3d"custom text jimu-float-leading"\x3e'+
this.nls.custom+"\x3c/div\x3e\x3c/div\x3e";this.picker=new q({ensureMode:!0,showOk:this.appearance.showColorPickerOK,showLabel:!1,value:this.value.toHex(),onChange:d.hitch(this,function(a){a=new b(a);this.setColor(a);this.changeColor();this.colorRecords&&this.colorRecords.push&&this.colorRecords.push(a)}),onClose:d.hitch(this,function(){this.emit("jimuColorPicker-popupClose")})});this.picker.placeAt(this.coustomtBtn);this.picker.setLabel(a);this.picker.setColor(this.value)},isJimuColorPickerTooltipDialogOpened:function(){return this.picker.isTooltipDialogOpened()},
_createCoustomRecord:function(a){this.colorRecords=new r({recordsLength:10,uid:this.recordUID||""});this.colorRecords.placeAt(a);this.own(e(this.colorRecords,"choose",d.hitch(this,function(a){this.setColor(new b(a));this.changeColor()})))},_isColorEqual:function(a){return this.value.toString()===(new b(a)).toString()?!0:!1},_changeLabel:function(a){c.empty(this.domNode);c.create("span",{innerHTML:a.toHex(),className:"color-label",style:{color:u.invertColor(a.toHex())}},this.domNode)},getPickerTooltipDialog:function(){var a=
null;this.picker&&this.picker.tooltipDialog&&(a=this.picker.tooltipDialog);return a}})});