// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/Evented dojo/_base/lang dojo/_base/html dojo/_base/array dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin jimu/dijit/TabContainer3 jimu/dijit/_FeaturelayerChooserWithButtons jimu/dijit/_QueryableLayerChooserWithButtons jimu/dijit/QueryableServiceChooserFromPortal jimu/dijit/_QueryableServiceChooserContent jimu/dijit/_FrameworkDataSourceChooserWithButtons".split(" "),function(l,m,d,n,e,p,q,r,t,u,v,w,x,y,z){var f=window.jimuNls.queryableLayerSource,
b=p([q,r,t,m],{templateString:"\x3cdiv\x3e\x3c/div\x3e",baseClass:"jimu-dijit-data-source",declaredClass:"jimu.dijit.DataSource",nls:null,dijits:null,types:null,postMixInProperties:function(){this.nls=f;this.dijits=[]},postCreate:function(){this.inherited(arguments);this._initSelf()},_initSelf:function(){var a=[];e.forEach(this.types,d.hitch(this,function(k,f){var h=k.type,g=b[h+"_CLASS_INFO"];if(g){var c=null;if(g.defaultOptions)var e=d.clone(g.defaultOptions),c=d.mixin(e,k.options);else c=k.options;
c||(c={});c.style={width:"100%",height:"100%"};e=h+"_"+f;c=new g.className(c);n.addClass(c.domNode,"hidden");c._dsType=h;c._dataSourceId=e;c._classInfo=g;this.own(l(c,"ok",d.hitch(this,function(){var a=this.getSelectedItems();a&&0<a.length&&this.emit("ok",a)})));this.own(l(c,"cancel",d.hitch(this,function(){this.emit("cancel")})));this.dijits.push(c);a.push({title:g.defaultTitle,content:c})}else console.error("Unsupported data source type:",h)}));this.tab=new u({tabs:a});this.tab.placeAt(this.domNode)},
_getSelectedDijit:function(){var a=this.tab.getSelectedIndex();return this.dijits[a]},getSelectedSourceType:function(){var a=this._getSelectedDijit();return a?a._classInfo.sourceType:""},getSelectedItems:function(){var a=[],b=this._getSelectedDijit();b&&(a=b.getSelectedItems())&&0<a.length&&e.forEach(a,d.hitch(this,function(a){a.dataSourceType=b._dsType}));return a},destroy:function(){this.dijits&&0<this.dijits.length&&e.forEach(this.dijits,d.hitch(this,function(a){a.destroy();a=null}));this.dijits=
null;this.inherited(arguments)}});b.DATA_SOURCE_FEATURE_LAYER_FROM_MAP="DATA_SOURCE_FEATURE_LAYER_FROM_MAP";b.DATA_SOURCE_QUERYABLE_LAYER_FROM_MAP="DATA_SOURCE_QUERYABLE_LAYER_FROM_MAP";b.DATA_SOURCE_QUERYABLE_LAYER_FROM_PORTAL="DATA_SOURCE_QUERYABLE_LAYER_FROM_PORTAL";b.DATA_SOURCE_QUERYABLE_LAYER_FROM_URL="DATA_SOURCE_QUERYABLE_LAYER_FROM_URL";b.DATA_SOURCE_FROM_FRAMEWORK="DATA_SOURCE_FROM_FRAMEWORK";b.DATA_SOURCE_FEATURE_LAYER_FROM_MAP_CLASS_INFO={className:v,defaultTitle:f.selectFromMap,defaultOptions:{multiple:!1},
sourceType:"map"};b.DATA_SOURCE_QUERYABLE_LAYER_FROM_MAP_CLASS_INFO={className:w,defaultTitle:f.selectFromMap,defaultOptions:{multiple:!1},sourceType:"map"};b.DATA_SOURCE_QUERYABLE_LAYER_FROM_PORTAL_CLASS_INFO={className:x,defaultTitle:f.selectFromPortal,defaultOptions:{multiple:!1},sourceType:"portal"};b.DATA_SOURCE_QUERYABLE_LAYER_FROM_URL_CLASS_INFO={className:y,defaultTitle:f.addServiceUrl,defaultOptions:{multiple:!1},sourceType:"url"};b.DATA_SOURCE_FROM_FRAMEWORK_CLASS_INFO={className:z,defaultTitle:window.jimuNls.frameworkDatasource.customDataSource,
defaultOptions:null,sourceType:"framework"};b.createQueryableLayerTypes=function(a){return[{type:b.DATA_SOURCE_QUERYABLE_LAYER_FROM_MAP,options:{createMapResponse:a.createMapResponse,onlyShowWebMapLayers:!0}},{type:b.DATA_SOURCE_QUERYABLE_LAYER_FROM_PORTAL,options:{portalUrl:a.portalUrl}},{type:b.DATA_SOURCE_QUERYABLE_LAYER_FROM_URL}]};b.createInfographicTypes=function(a){return[{type:b.DATA_SOURCE_FEATURE_LAYER_FROM_MAP,options:{createMapResponse:a.createMapResponse,types:["point","polyline","polygon"],
showLayerFromFeatureSet:!0,showTable:!1,mustSupportStatistics:!1,ignoreVirtualLayer:!0,onlyShowWebMapLayers:!0}},{type:b.DATA_SOURCE_FROM_FRAMEWORK,options:{appConfig:a.appConfig}}]};return b});