// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/Evented dojo/Deferred dojo/promise/all dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/_base/lang dojo/_base/html dojo/_base/array dojo/query dijit/registry jimu/filterUtils jimu/utils ./_SingleFilterParameter ./_filter/ValueProviderFactory".split(" "),function(p,q,r,t,u,v,w,x,f,m,k,n,y,z,A,B,C){return u([v,w,x,q],{baseClass:"jimu-filter-parameters",templateString:'\x3cdiv\x3e\x3ctable style\x3d"width:100%;border-collapse:collapse;"\x3e\x3ctbody data-dojo-attach-point\x3d"tbody"\x3e\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e',
_filterUtils:null,_spObj:null,nls:null,partsObj:null,layerInfo:null,OPERATORS:null,url:null,featureLayerId:null,postMixInProperties:function(){this.nls=window.jimuNls.filterBuilder;this._filterUtils=new z;this.OPERATORS=f.clone(this._filterUtils.OPERATORS);this._spObj={}},destroy:function(){this.clear();this._filterUtils=null;this.inherited(arguments)},getFilterExpr:function(){var a=this._getNewValidPartsObj(this.partsObj,!0);return a?this._getFilterExprByPartsObj(a):null},getValueProviders:function(){for(var a=
[],d=this._getAllInteractiveSinglePartArray(this.partsObj),b=0;b<d.length;b++){var e=d[b].spId;e&&(e=this._getSingleFilterParameterBySpId(e),a.push(e))}return a},_getNewValidPartsObj:function(a,d){a=f.clone(a);for(var b={logicalOperator:a.logicalOperator,parts:[]},e=f.hitch(this,function(a){if(a.spId){var b=this._getSingleFilterParameterBySpId(a.spId);a.valueObj=b.getValueObject();return b.getStatus()}return a.valueObj?1:-1}),c=f.hitch(this,function(a){var d=e(a);0<d&&b.parts.push(a);return d}),g=
f.hitch(this,function(a){var d=[];a.parts=k.filter(a.parts,f.hitch(this,function(a){a=e(a);d.push(a);return 0<a}));1===a.parts.length?b.parts.push(a.parts[0]):2<=a.parts.length&&b.parts.push(a);return Math.min.apply(d,d)}),h=0;h<a.parts.length;h++){var l=a.parts[h];if(l.parts){if(0>g(l)&&d)return null}else if(0>c(l)&&d)return null}return b},_getFilterExprByPartsObj:function(a){this._filterUtils.isHosted=A.isHostedService(this.url);return this._filterUtils.getExprByFilterObj(a)},_getSingleFilterParameterBySpId:function(a){return this._spObj[a]},
_getCascadeFilterExpr:function(a){var d="1\x3d1",b={logicalOperator:this.partsObj.logicalOperator,parts:[]},e=f.clone(this.partsObj),c,g,h;c="none";a.interactiveObj&&a.interactiveObj.cascade&&(c=a.interactiveObj.cascade);if("previous"===c)for(c=0;c<e.parts.length;c++)g=e.parts[c],g.majorCascadeIndex<a.majorCascadeIndex?b.parts.push(g):g.parts&&g.majorCascadeIndex===a.majorCascadeIndex&&(h=f.clone(g),h.parts=k.filter(h.parts,f.hitch(this,function(b){return b.minorCascadeIndex<a.minorCascadeIndex})),
b.parts.push(h));else if("all"===c)for(c=0;c<e.parts.length;c++)g=e.parts[c],g.majorCascadeIndex!==a.majorCascadeIndex?b.parts.push(g):g.majorCascadeIndex===a.majorCascadeIndex&&g.parts&&(h=f.clone(g),k.some(g.parts,f.hitch(this,function(b){return b.spId===a.spId}))&&(h.parts=k.filter(h.parts,f.hitch(this,function(b){return b.minorCascadeIndex!==a.minorCascadeIndex})),b.parts.push(h)));(b=this._getNewValidPartsObj(b,!1))&&(d=this._getFilterExprByPartsObj(b));d||(d="1\x3d1");return d},clear:function(){this.featureLayerId=
this.url=null;var a=n(".jimu-widget-query-single-parameter",this.tbody);k.forEach(a,f.hitch(this,function(a){y.byNode(a).destroy()}));m.empty(this.tbody);this.layerInfo=this.partsObj=null},build:function(a,d,b,e){var c=new r;this.clear();this.url=a;this.layerInfo=d;this.partsObj=f.clone(b);this.partsObj=this._updatePartsObj(this.partsObj);this.featureLayerId=e;this._setCascadeIndexForPartsObj(this.partsObj);a=this._getAllInteractiveSinglePartArray(this.partsObj);if(0<a.length){var g=new C({url:this.url,
layerDefinition:d,featureLayerId:this.featureLayerId});a=k.map(a,f.hitch(this,function(a){var b=m.create("tr",{innerHTML:"\x3ctd\x3e\x3c/td\x3e"},this.tbody),b=n("td",b)[0],c=this._getFieldInfo(a.fieldObj.name,this.layerInfo),c=new B({nls:this.nls,url:this.url,layerDefinition:d,fieldInfo:c,part:a,valueProviderFactory:g});this.own(p(c,"change",f.hitch(this,this._onSingleFilterParameterChanged)));c.placeAt(b);c.startup();a.spId=c.id;return this._spObj[c.id]=c}));k.forEach(a,f.hitch(this,function(a){a.valueProvider.getCascadeFilterExpr=
f.hitch(this,this._getCascadeFilterExpr,a.part)}));a=k.map(a,f.hitch(this,function(a){return a.init()}));t(a).then(f.hitch(this,function(){c.resolve()}),f.hitch(this,function(){c.reject()}))}else c.resolve();return c},_updatePartsObj:function(a){k.forEach(a,f.hitch(this,function(a){a.parts?k.forEach(a.parts,f.hitch(this,function(a){a.interactiveObj&&!0===a.interactiveObj.cascade?a.interactiveObj.cascade="previous":!1===a.interactiveObj.cascade&&(a.interactiveObj.cascade="none")})):a.interactiveObj&&
!0===a.interactiveObj.cascade?a.interactiveObj.cascade="previous":!1===a.interactiveObj.cascade&&(a.interactiveObj.cascade="none")}));return a},_setCascadeIndexForPartsObj:function(a){for(var d=0;d<a.parts.length;d++){var b=a.parts[d];b.majorCascadeIndex="AND"===a.logicalOperator?d:0;b.minorCascadeIndex=0;b.cascadeIndex=b.majorCascadeIndex;if(b.parts)for(var e=0;e<b.parts.length;e++){var c=b.parts[e];c.majorCascadeIndex=b.majorCascadeIndex;c.minorCascadeIndex="AND"===b.logicalOperator?e:0;c.cascadeIndex=
parseFloat(c.majorCascadeIndex+"."+c.minorCascadeIndex)}}},_getFieldInfo:function(a,d){for(var b=d.fields,e=0;e<b.length;e++){var c=b[e];if(a===c.name)return c}return null},_getAllInteractiveSinglePartArray:function(a){for(var d=[],b=0;b<a.parts.length;b++){var e=a.parts[b];if(e.parts)for(var c=0;c<e.parts.length;c++){var f=e.parts[c];f.interactiveObj&&d.push(f)}else e.interactiveObj&&d.push(e)}return d},_onSingleFilterParameterChanged:function(){this.emit("change",this.getFilterExpr(!1))}})});