// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:jimu/dijit/templates/ImageChooser.html":'\x3cdiv class\x3d"jimu-image-chooser js-fileapi-wrapper"\x3e\r\n  \x3cdiv class\x3d"hint" data-dojo-attach-point\x3d"hintText"\x3e\r\n\t\t\x3cspan class\x3d"display-text" data-dojo-attach-point\x3d"displayText"\x3e\x3c/span\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"hint" data-dojo-attach-point\x3d"hintImage"\x3e\r\n\t\t\x3cimg class\x3d"display-image" data-dojo-attach-point\x3d"selfImg"\x3e\r\n  \x3c/div\x3e\r\n  \x3cform data-dojo-attach-point\x3d"fileForm"\x3e\r\n    \x3clabel data-dojo-attach-point\x3d"mask"\x3e\x3c/label\x3e\r\n    \x3cinput type\x3d"file" data-dojo-attach-point\x3d"fileInput"\x3e\r\n  \x3c/form\x3e\r\n\x3c/div\x3e'}});
define("dojo/Evented dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dojo/_base/lang dojo/_base/html dojo/on dojo/text!./templates/ImageChooser.html dojo/sniff dojo/request esri/lang ../utils ./_CropImage jimu/dijit/Popup jimu/dijit/Message jimu/dijit/LoadingShelter".split(" "),function(g,m,n,p,d,b,k,q,e,r,t,c,u,v,h,w){var l=0;g=m([n,p,g],{templateString:q,declaredClass:"jimu.dijit.ImageChooser",cropImage:!0,displayImg:null,defaultSelfSrc:null,showSelfImg:!1,label:null,showTip:!0,goldenWidth:400,
goldenHeight:400,maxSize:1024,format:null,imageData:null,postMixInProperties:function(){this.inherited(arguments);this.nls=window.jimuNls.imageChooser;this.nls.common=window.jimuNls.common;this.nls.readError=this.nls.readError||"Failed to read the file."},postCreate:function(){this._initial();c.file.supportHTML5()||e("safari")||!c.file.isEnabledFlash()||c.file.loadFileAPI().then(d.hitch(this,function(){b.setStyle(this.mask,"zIndex",1)}))},setImageSize:function(a){this.goldenWidth=a.width;this.goldenHeight=
a.height},disableChooseImage:function(){b.setStyle(this.fileForm,"display","none");this.label&&"string"===typeof this.label&&b.addClass(this.displayText,"disable-label");b.removeAttr(this.domNode,"title")},enableChooseImage:function(){b.setStyle(this.fileForm,"display","block");this.label&&"string"===typeof this.label&&b.removeClass(this.displayText,"disable-label");this._addTip()},setDefaultSelfSrc:function(a){this.defaultSelfSrc=a;this.imageData=this.selfImg.src=a},getImageData:function(){return this.imageData},
_initial:function(){this._processProperties();this._porcessMaskClick();this._setupFileInput();this._addTip()},_processProperties:function(){this.fileProperty={};this.label&&"string"===typeof this.label&&(this.displayText.innerHTML=this.label,b.setStyle(this.hintText,"display","block"));this.showSelfImg&&b.setStyle(this.hintImage,"display","block");this.defaultSelfSrc&&(this.imageData=this.selfImg.src=this.defaultSelfSrc);if(this.format){var a="image/*";"string"===typeof this.format&&/^image\/./.test(this.format)?
a=this.format:"[object Array]"===Object.prototype.toString.call(this.format)&&0<this.format.length&&(a=this.format.join(","));b.setAttr(this.fileInput,"accept",a)}c.file.supportHTML5()||e("safari")||!c.file.isEnabledFlash()||b.setStyle(this.fileInput,{width:"100%",height:"100%",position:"absolute",left:0,top:0,opacity:0,zIndex:9})},_porcessMaskClick:function(){b.setAttr(this.fileInput,"id","imageChooser_"+l);b.setAttr(this.mask,"for","imageChooser_"+l);l++;this.maskHandle=k(this.mask,"click",d.hitch(this,
function(a){a.stopPropagation();if(e("safari")&&7>e("safari"))new h({message:this.nls.unsupportReaderAPI}),a.preventDefault();else{if(!c.file.supportHTML5()){if(!c.file.isEnabledFlash()){var x=b.create("a",{href:"http://helpx.adobe.com/flash-player.html",innerHTML:this.nls.enableFlash,target:"_blank"});new h({message:x});a.preventDefault();return}if(!c.file.supportFileAPI()){new h({message:this.nls.unsupportReaderAPI});a.preventDefault();return}}b.setStyle(this.fileInput,"display","none");setTimeout(d.hitch(this,
function(){b.setStyle(this.fileInput,"display","block")}),200)}}))},_addTip:function(){if(this.showTip){var a=t.substitute({width:this.goldenWidth||40,height:this.goldenHeight||40},this.nls.toolTip);b.setAttr(this.domNode,"title",a)}else b.setAttr(this.domNode,"title","")},_setupFileInput:function(){if(9>=e("ie"))this.own(k(this.fileInput,"change",d.hitch(this,this._onFileInputChange)));else k.once(this.fileInput,"change",d.hitch(this,this._onFileInputChange))},_onFileInputChange:function(a){var b=
a.target.files&&a.target.files[0]||a.files&&a.files[0];if(this.format&&-1===this.format.indexOf(b.type))new h({message:this.nls.invalidType}),(!e("ie")||9<e("ie"))&&this._recreateFileForm();else{var f=9>e("ie")?23552:1024*this.maxSize;c.file.readFile(a,"image/*",f,d.hitch(this,function(a,d,c){a?(d=this.nls[a.errCode],"exceed"===a.errCode&&(d=d.replace("1024",f/1024)),new h({message:d})):(this.fileProperty.fileName=d,window.isXT&&this.cropImage&&"image/gif"!==b.type?this._cropImageByUser(c):this._readFileData(c));
(!e("ie")||9<e("ie"))&&this._recreateFileForm()}))}},_recreateFileForm:function(){var a=d.clone(this.mask),c=d.clone(this.fileInput);b.destroy(this.mask);b.destroy(this.fileInput);var f=d.clone(this.fileForm);b.place(a,f);b.place(c,f);b.place(f,this.fileForm,"replace");this.maskHandle.remove();this.mask=a;this.fileInput=c;b.destroy(this.fileForm);this.fileForm=f;this._porcessMaskClick();this._setupFileInput()},_readFileData:function(a){this.onImageChange(a,this.fileProperty);this.displayImg&&b.setAttr(this.displayImg,
"src",a);this.showSelfImg&&(this.selfImg?b.setAttr(this.selfImg,"src",a):this.selfImg.src=a,(a=b.getMarginBox(this.hintImage))&&a.w&&a.h&&(b.style(this.selfImg,"maxWidth",a.w+"px"),b.style(this.selfImg,"maxHeight",a.h+"px")))},_cropImageByUser:function(a){var c=new u({imageSrc:a,nls:d.clone(this.nls),realWidth:this.goldenWidth,realHeight:this.goldenHeight}),f=new w({hidden:!0}),e=new v({titleLabel:this.nls.cropImage,content:c,width:500,height:480,buttons:[{label:this.nls.common.ok,onClick:d.hitch(this,
function(){var b=c.getImageSize(),g=c.getCropSize();f.show();r("/webappbuilder/rest/cropimage",{data:{imageData:a,imageDisplaySize:b.w+","+b.h,cropRectangle:g.w+","+g.h+","+g.t+","+g.l},method:"POST",handleAs:"json",headers:{"X-Requested-With":null}}).then(d.hitch(this,function(a){a.success?(this._readFileData(a.imageData),e.close()):(new h({message:this.nls.unknowError}),f.hide())}),d.hitch(this,function(a){console.error(a);new h({message:this.nls.unknowError});f.hide()}))})}]});f.placeAt(e.domNode);
c.startup();b.addClass(e.domNode,"image-chooser-crop-popup")},onImageChange:function(a){this.imageData=a;this.emit("imageChange",this.imageData,this.fileProperty);this.emit("change",this.imageData,this.fileProperty)}});g.GIF="image/gif";g.JPEG="image/jpeg";g.PNG="image/png";return g});