// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/Evented dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/store/Memory dojo/Deferred dojo/store/Observable dijit/tree/ObjectStoreModel dojo/promise/all dojo/_base/lang dojo/_base/html dojo/_base/array jimu/utils jimu/dijit/_Tree jimu/LayerInfos/LayerInfos jimu/dijit/LoadingIndicator".split(" "),function(r,t,u,v,w,x,y,n,z,A,l,b,p,h,m,B,C,D){var g=u([v,w,x,t],{templateString:'\x3cdiv style\x3d"width:100%;"\x3e\x3cdiv data-dojo-attach-point\x3d"errorTipSection" class\x3d"error-tip-section"\x3e\x3cspan class\x3d"jimu-icon jimu-icon-error"\x3e\x3c/span\x3e\x3cspan class\x3d"jimu-state-error-text" data-dojo-attach-point\x3d"errTip"\x3e${nls.noLayersTip}\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e',
_store:null,_id:0,_treeClass:"layer-chooser-tree",createMapResponse:null,multiple:!1,onlyShowVisible:!1,updateWhenLayerInfosIsShowInMapChanged:!1,onlyShowWebMapLayers:!1,postMixInProperties:function(){this.nls=window.jimuNls.basicLayerChooserFromMap},postCreate:function(){this.inherited(arguments);p.addClass(this.domNode,"jimu-basic-layer-chooser-from-map");this.multiple=!!this.multiple;this.shelter=new D({hidden:!0});this.shelter.placeAt(this.domNode);this.shelter.startup();this._createTree();this.basicFilter=
b.hitch(this,this.basicFilter);this.filter=g.andCombineFilters([this.basicFilter,this.filter]);this.createMapResponse&&this.setCreateMapResponse(this.createMapResponse)},basicFilter:function(a){var c=new n;this.onlyShowVisible?c.resolve(a.isShowInMap()):c.resolve(!0);return c},filter:function(a){a=new n;a.resolve(!0);return a},getSelectedItems:function(){var a=this.tree.getSelectedItems();return h.map(a,b.hitch(this,function(a){return this.getHandledItem(a)}))},getAllItems:function(){var a=this.tree.getAllItems(),
c=[];h.forEach(a,b.hitch(this,function(a){"root"!==a.id&&(a=this.getHandledItem(a),c.push(a))}));return c},getHandledItem:function(a){return{name:a.name,layerInfo:a.layerInfo}},_isLeafItem:function(a){return a.isLeaf},setCreateMapResponse:function(a){this.createMapResponse=a;C.getInstance(this.createMapResponse.map,this.createMapResponse.itemInfo).then(b.hitch(this,function(a){this.layerInfosObj=a;this.own(r(this.layerInfosObj,"layerInfosChanged",b.hitch(this,this._onLayerInfosChanged)));this.updateWhenLayerInfosIsShowInMapChanged&&
this.own(r(this.layerInfosObj,"layerInfosIsShowInMapChanged",b.hitch(this,this._onLayerInfosIsShowInMapChanged)));this._buildTree(this.layerInfosObj)}))},_onLayerInfosChanged:function(a,c){this._buildTree(this.layerInfosObj);this.emit("update")},_onLayerInfosIsShowInMapChanged:function(a){this._buildTree(this.layerInfosObj);this.emit("update")},_buildTree:function(a){this._clear();p.setStyle(this.errorTipSection,"display","block");var c=[];this.onlyShowWebMapLayers?(c=a.getLayerInfoArrayOfWebmap(),
c=c.concat(a.getTableInfoArrayOfWebmap())):(c=a.getLayerInfoArray(),c=c.concat(a.getTableInfoArray()));0!==c.length&&(p.setStyle(this.errorTipSection,"display","none"),h.forEach(c,b.hitch(this,function(a){this._addDirectLayerInfo(a)})))},_addDirectLayerInfo:function(a){a&&a.getLayerObject().then(b.hitch(this,function(){this._addItem("root",a)}),b.hitch(this,function(a){console.error(a)}))},_clear:function(){var a=this._store.query({parent:"root"});h.forEach(a,b.hitch(this,function(a){a&&"root"!==
a.id&&this._store.remove(a.id)}))},_addItem:function(a,c){var d=null,f=c.getLayerType(),k=this.filter(c);l({layerType:f,valid:k}).then(b.hitch(this,function(k){if(k.valid){var f=b.hitch(this,function(f,e){this._id++;d={name:c.title||"",parent:a,layerInfo:c,type:k.layerType,layerClass:c.layerObject.declaredClass,id:this._id.toString(),isLeaf:f,hasChildren:e};this._store.add(d)}),q=c.getSubLayers(),e=0===q.length;e?f(e,!1):(q=h.map(q,b.hitch(this,function(a){return this.filter(a)})),l(q).then(b.hitch(this,
function(a){(a=h.some(a,function(a){return a}))&&f(e,a)})))}}))},_getRootItem:function(){return{id:"root",name:"Map Root",type:"root",isLeaf:!1,hasChildren:!0}},_createTree:function(){var a=this._getRootItem(),a=new y({data:[a],getChildren:function(a){return this.query({parent:a.id})}});this._store=new z(a);a=new A({store:this._store,query:{id:"root"},mayHaveChildren:b.hitch(this,this._mayHaveChildren)});this.tree=new B({multiple:this.multiple,model:a,showRoot:!1,isLeafItem:b.hitch(this,this._isLeafItem),
style:{width:"100%"},onOpen:b.hitch(this,function(a,d){"root"!==a.id&&this._onTreeOpen(a,d)}),onClick:b.hitch(this,function(a,d,f){this._onTreeClick(a,d,f);this.emit("tree-click",a,d,f)}),getIconStyle:b.hitch(this,function(a,d){var c=null;if(!a||"root"===a.id)return null;var k={width:"20px",height:"20px",backgroundRepeat:"no-repeat",backgroundPosition:"center center",backgroundImage:""},e=window.location.protocol+"//"+window.location.host+require.toUrl("jimu"),b=this._getIconImageName(a,d);b&&(k.backgroundImage=
"url("+e+"/css/images/"+b+")",c=k);return c})});p.addClass(this.tree.domNode,this._treeClass);this.tree.placeAt(this.shelter.domNode,"before")},_mayHaveChildren:function(a){return a.hasChildren},_getIconImageName:function(a,c){var d="";if("ArcGISDynamicMapServiceLayer"===a.type||"ArcGISTiledMapServiceLayer"===a.type)d=c?"mapserver_open.png":"mapserver_close.png";else if("GroupLayer"===a.type)d=c?"group_layer2.png":"group_layer1.png";else if("FeatureLayer"===a.type){var f=m.getTypeByGeometryType(a.layerInfo.layerObject.geometryType);
"point"===f?d="point_layer1.png":"polyline"===f?d="line_layer1.png":"polygon"===f&&(d="polygon_layer1.png")}else d="Table"===a.type?"table.png":"ArcGISImageServiceLayer"===a.type||"ArcGISImageServiceVectorLayer"===a.type?"image_layer.png":c?"mapserver_open.png":"mapserver_close.png";return d},_onTreeOpen:function(a,c){if("root"!==a.id){var d=[],f=[],d=a.layerInfo.getSubLayers();a.checked||(this.shelter.show(),f=h.map(d,b.hitch(this,function(a){return a.getLayerObject()})),l(f).then(b.hitch(this,function(){this.domNode&&
(h.forEach(d,b.hitch(this,function(c){this._addItem(a.id,c)})),a.checked=!0,this.shelter.hide())}),b.hitch(this,function(a){console.error(a);this.shelter.hide()})))}},_onTreeClick:function(a,c,d){},destroy:function(){this.shelter&&this.shelter.destroy();this.tree&&this.tree.destroy();this.shelter=null;this.tree.destroy();this.inherited(arguments)}});g.createFilterByLayerType=function(a){b.isArrayLike(a)||(a=[]);return function(c){var d=new n;if(0===a.length)d.resolve(!0);else{var f=[];c.traversal(function(a){f.push(a.getLayerType())});
l(f).then(function(c){for(var e=0;e<c.length;e++)for(var f=0;f<a.length;f++)if(c[e]===a[f]){d.resolve(!0);return}d.resolve(!1)},function(a){console.error(a);d.reject(a)})}return d}};g.createFeaturelayerFilter=function(a,c,d,f){var b=["point","polyline","polygon"];a&&0<a.length?(a=h.filter(a,function(a){return 0<=b.indexOf(a)}),0===a.length&&(a=b)):a=b;return function(b){var e=b.getLayerType();b=b.getLayerObject();return l({layerType:e,layerObject:b}).then(function(b){var e=b.layerType;b=b.layerObject;
if("ArcGISDynamicMapServiceLayer"===e||"ArcGISTiledMapServiceLayer"===e||"GroupLayer"===e||"FeatureCollection"===e)return!0;if("FeatureLayer"===e){var e=m.getTypeByGeometryType(b.geometryType),e=0<=h.indexOf(a,e),k=g._shouldPassStatisticsCheck(f,b);return b.url?(b=m.isFeaturelayerUrlSupportQuery(b.url,b.capabilities),e&&b&&k):c&&e}return"Table"===e?(e=m.isFeaturelayerUrlSupportQuery(b.url,b.capabilities),b=g._shouldPassStatisticsCheck(f,b),d&&e&&b):!1})}};g.createImageServiceLayerFilter=function(a,
b){return function(c){var d=c.getLayerType();c=c.getLayerObject();return l({layerType:d,layerObject:c}).then(function(c){var e=c.layerType,d=c.layerObject;return"ArcGISImageServiceLayer"===e||"ArcGISImageServiceVectorLayer"===e?a?m.isImageServiceSupportQuery(c.layerObject.capabilities)?b?g._shouldPassStatisticsCheck(b,d):!0:!1:!0:!1})}};g._shouldPassStatisticsCheck=function(a,c){if(a){var b=!1;return b=c.advancedQueryCapabilities?!!c.advancedQueryCapabilities.supportsStatistics:!!c.supportsStatistics}return!0};
g.createQueryableLayerFilter=function(a){var c=g.createFeaturelayerFilter(["point","polyline","polygon"],!1,!0,a);a=g.createImageServiceLayerFilter(!0,a);return g.orCombineFilters([c,a])};g.andCombineFilters=function(a){return g._combineFilters(a,!0)};g.orCombineFilters=function(a){return g._combineFilters(a,!1)};g._combineFilters=function(a,c){return function(b){var d=new n,g=h.map(a,function(a){return a(b)});l(g).then(function(a){var b=!1,b=c?h.every(a,function(a){return a}):h.some(a,function(a){return a});
d.resolve(b)},function(a){console.error(a);d.reject(a)});return d}};return g});